package com.el.client;

import org.springframework.stereotype.Component;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-09-23T11:39:53.585+08:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://cmic.el.com/", name = "EmpWsService")
@XmlSeeAlso({ObjectFactory.class})
@Component("testEmpWsService")
public interface EmpWsService {

    @WebMethod
    @RequestWrapper(localName = "reqEmps", targetNamespace = "http://cmic.el.com/", className = "com.el.client.ReqEmps")
    @ResponseWrapper(localName = "reqEmpsResponse", targetNamespace = "http://cmic.el.com/", className = "com.el.client.ReqEmpsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<Emp> reqEmps();

    @WebMethod
    @RequestWrapper(localName = "reqEmpString", targetNamespace = "http://cmic.el.com/", className = "com.el.client.ReqEmpString")
    @ResponseWrapper(localName = "reqEmpStringResponse", targetNamespace = "http://cmic.el.com/", className = "com.el.client.ReqEmpStringResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String reqEmpString(
            @WebParam(name = "info", targetNamespace = "")
                    String info
    );
}
