package com.el.cfg.mapper;

import com.el.cfg.domain.F4211;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

public interface F4211Mapper {
    @Select({
        "select",
        "SDDOCO, SDDCTO, SDKCOO, SDLNID, SDSFXO, SDMCU, SDCO, SDOKCO, SDOORN, SDOCTO, ",
        "SDOGNO, SDRKCO, SDRORN, SDRCTO, SDRLLN, SDDMCT, SDDMCS, SDAN8, SDSHAN, SDPA8, ",
        "SDDRQJ, SDTRDJ, SDPDDJ, SDADDJ, SDIVD, SDCNDJ, SDDGL, SDRSDJ, SDPEFJ, SDPPDJ, ",
        "SDVR01, SDVR02, SDITM, SDLITM, SDAITM, SDLOCN, SDLOTN, SDFRGD, SDTHGD, SDFRMP, ",
        "SDTHRP, SDEXDP, SDDSC1, SDDSC2, SDLNTY, SDNXTR, SDLTTR, SDEMCU, SDRLIT, SDKTLN, ",
        "SDCPNT, SDRKIT, SDKTP, SDSRP1, SDSRP2, SDSRP3, SDSRP4, SDSRP5, SDPRP1, SDPRP2, ",
        "SDPRP3, SDPRP4, SDPRP5, SDUOM, SDUORG, SDSOQS, SDSOBK, SDSOCN, SDSONE, SDUOPN, ",
        "SDQTYT, SDQRLV, SDCOMM, SDOTQY, SDUPRC, SDAEXP, SDAOPN, SDPROV, SDTPC, SDAPUM, ",
        "SDLPRC, SDUNCS, SDECST, SDCSTO, SDTCST, SDINMG, SDPTC, SDRYIN, SDDTBS, SDTRDC, ",
        "SDFUN2, SDASN, SDPRGR, SDCLVL, SDCADC, SDKCO, SDDOC, SDDCT, SDODOC, SDODCT, ",
        "SDOKC, SDPSN, SDDELN, SDTAX1, SDTXA1, SDEXR1, SDATXT, SDPRIO, SDRESL, SDBACK, ",
        "SDSBAL, SDAPTS, SDLOB, SDEUSE, SDDTYS, SDNTR, SDVEND, SDCARS, SDMOT, SDROUT, ",
        "SDSTOP, SDZON, SDCNID, SDFRTH, SDSHCM, SDSHCN, SDSERN, SDUOM1, SDPQOR, SDUOM2, ",
        "SDSQOR, SDUOM4, SDITWT, SDWTUM, SDITVL, SDVLUM, SDRPRC, SDORPR, SDORP, SDCMGP, ",
        "SDGLC, SDCTRY, SDFY, SDSO01, SDSO02, SDSO03, SDSO04, SDSO05, SDSO06, SDSO07, ",
        "SDSO08, SDSO09, SDSO10, SDSO11, SDSO12, SDSO13, SDSO14, SDSO15, SDACOM, SDCMCG, ",
        "SDRCD, SDGRWT, SDGWUM, SDSBL, SDSBLT, SDLCOD, SDUPC1, SDUPC2, SDUPC3, SDSWMS, ",
        "SDUNCD, SDCRMD, SDCRCD, SDCRR, SDFPRC, SDFUP, SDFEA, SDFUC, SDFEC, SDURCD, SDURDT, ",
        "SDURAT, SDURAB, SDURRF, SDTORG, SDUSER, SDPID, SDJOBN, SDUPMJ, SDTDAY, SDSO16, ",
        "SDSO17, SDSO18, SDSO19, SDSO20, SDIR01, SDIR02, SDIR03, SDIR04, SDIR05, SDSOOR, ",
        "SDVR03, SDDEID, SDPSIG, SDRLNU, SDPMDT, SDRLTM, SDRLDJ, SDDRQT, SDADTM, SDOPTT, ",
        "SDPDTT, SDPSTM, SDXDCK, SDXPTY, SDDUAL, SDBSC, SDCBSC, SDCORD, SDDVAN, SDPEND, ",
        "SDRFRV, SDMCLN, SDSHPN, SDRSDT, SDPRJM, SDOSEQ, SDMERL, SDHOLD, SDHDBU, SDDMBU, ",
        "SDBCRC, SDODLN, SDOPDJ, SDXKCO, SDXORN, SDXCTO, SDXLLN, SDXSFX, SDPOE, SDPMTO, ",
        "SDANBY, SDPMTN, SDNUMB, SDAAID, SDSPATTN, SDPRAN8, SDPRCIDLN, SDCCIDLN, SDSHCCIDLN, ",
        "SDOPPID, SDOSTP, SDUKID, SDCATNM, SDALLOC, SDFULPID, SDALLSTS, SDOSCORE, SDOSCOREO, ",
        "SDCMCO, SDKITID, SDKITAMTDOM, SDKITAMTFOR, SDKITDIRTY, SDOCITT, SDOCCARDNO, ",
        "SDPMPN, SDPNS",
        "from F4211",
        "where SDDOCO = #{sddoco,jdbcType=DECIMAL}",
          "and SDDCTO = #{sddcto,jdbcType=NCHAR}",
          "and SDKCOO = #{sdkcoo,jdbcType=NCHAR}",
          "and SDLNID = #{sdlnid,jdbcType=DECIMAL}"
    })
    @Results({
        @Result(column="SDDOCO", property="sddoco", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="SDDCTO", property="sddcto", jdbcType=JdbcType.NCHAR, id=true),
        @Result(column="SDKCOO", property="sdkcoo", jdbcType=JdbcType.NCHAR, id=true),
        @Result(column="SDLNID", property="sdlnid", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="SDSFXO", property="sdsfxo", jdbcType=JdbcType.NCHAR),
        @Result(column="SDMCU", property="sdmcu", jdbcType=JdbcType.NCHAR),
        @Result(column="SDCO", property="sdco", jdbcType=JdbcType.NCHAR),
        @Result(column="SDOKCO", property="sdokco", jdbcType=JdbcType.NCHAR),
        @Result(column="SDOORN", property="sdoorn", jdbcType=JdbcType.NCHAR),
        @Result(column="SDOCTO", property="sdocto", jdbcType=JdbcType.NCHAR),
        @Result(column="SDOGNO", property="sdogno", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDRKCO", property="sdrkco", jdbcType=JdbcType.NCHAR),
        @Result(column="SDRORN", property="sdrorn", jdbcType=JdbcType.NCHAR),
        @Result(column="SDRCTO", property="sdrcto", jdbcType=JdbcType.NCHAR),
        @Result(column="SDRLLN", property="sdrlln", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDDMCT", property="sddmct", jdbcType=JdbcType.NCHAR),
        @Result(column="SDDMCS", property="sddmcs", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDAN8", property="sdan8", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDSHAN", property="sdshan", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDPA8", property="sdpa8", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDDRQJ", property="sddrqj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDTRDJ", property="sdtrdj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDPDDJ", property="sdpddj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDADDJ", property="sdaddj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDIVD", property="sdivd", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDCNDJ", property="sdcndj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDDGL", property="sddgl", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDRSDJ", property="sdrsdj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDPEFJ", property="sdpefj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDPPDJ", property="sdppdj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDVR01", property="sdvr01", jdbcType=JdbcType.NCHAR),
        @Result(column="SDVR02", property="sdvr02", jdbcType=JdbcType.NCHAR),
        @Result(column="SDITM", property="sditm", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDLITM", property="sdlitm", jdbcType=JdbcType.NCHAR),
        @Result(column="SDAITM", property="sdaitm", jdbcType=JdbcType.NCHAR),
        @Result(column="SDLOCN", property="sdlocn", jdbcType=JdbcType.NCHAR),
        @Result(column="SDLOTN", property="sdlotn", jdbcType=JdbcType.NCHAR),
        @Result(column="SDFRGD", property="sdfrgd", jdbcType=JdbcType.NCHAR),
        @Result(column="SDTHGD", property="sdthgd", jdbcType=JdbcType.NCHAR),
        @Result(column="SDFRMP", property="sdfrmp", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDTHRP", property="sdthrp", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDEXDP", property="sdexdp", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDDSC1", property="sddsc1", jdbcType=JdbcType.NCHAR),
        @Result(column="SDDSC2", property="sddsc2", jdbcType=JdbcType.NCHAR),
        @Result(column="SDLNTY", property="sdlnty", jdbcType=JdbcType.NCHAR),
        @Result(column="SDNXTR", property="sdnxtr", jdbcType=JdbcType.NCHAR),
        @Result(column="SDLTTR", property="sdlttr", jdbcType=JdbcType.NCHAR),
        @Result(column="SDEMCU", property="sdemcu", jdbcType=JdbcType.NCHAR),
        @Result(column="SDRLIT", property="sdrlit", jdbcType=JdbcType.NCHAR),
        @Result(column="SDKTLN", property="sdktln", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDCPNT", property="sdcpnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDRKIT", property="sdrkit", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDKTP", property="sdktp", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDSRP1", property="sdsrp1", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSRP2", property="sdsrp2", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSRP3", property="sdsrp3", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSRP4", property="sdsrp4", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSRP5", property="sdsrp5", jdbcType=JdbcType.NCHAR),
        @Result(column="SDPRP1", property="sdprp1", jdbcType=JdbcType.NCHAR),
        @Result(column="SDPRP2", property="sdprp2", jdbcType=JdbcType.NCHAR),
        @Result(column="SDPRP3", property="sdprp3", jdbcType=JdbcType.NCHAR),
        @Result(column="SDPRP4", property="sdprp4", jdbcType=JdbcType.NCHAR),
        @Result(column="SDPRP5", property="sdprp5", jdbcType=JdbcType.NCHAR),
        @Result(column="SDUOM", property="sduom", jdbcType=JdbcType.NCHAR),
        @Result(column="SDUORG", property="sduorg", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDSOQS", property="sdsoqs", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDSOBK", property="sdsobk", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDSOCN", property="sdsocn", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDSONE", property="sdsone", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDUOPN", property="sduopn", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDQTYT", property="sdqtyt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDQRLV", property="sdqrlv", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDCOMM", property="sdcomm", jdbcType=JdbcType.NCHAR),
        @Result(column="SDOTQY", property="sdotqy", jdbcType=JdbcType.NCHAR),
        @Result(column="SDUPRC", property="sduprc", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDAEXP", property="sdaexp", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDAOPN", property="sdaopn", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDPROV", property="sdprov", jdbcType=JdbcType.NCHAR),
        @Result(column="SDTPC", property="sdtpc", jdbcType=JdbcType.NCHAR),
        @Result(column="SDAPUM", property="sdapum", jdbcType=JdbcType.NCHAR),
        @Result(column="SDLPRC", property="sdlprc", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDUNCS", property="sduncs", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDECST", property="sdecst", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDCSTO", property="sdcsto", jdbcType=JdbcType.NCHAR),
        @Result(column="SDTCST", property="sdtcst", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDINMG", property="sdinmg", jdbcType=JdbcType.NCHAR),
        @Result(column="SDPTC", property="sdptc", jdbcType=JdbcType.NCHAR),
        @Result(column="SDRYIN", property="sdryin", jdbcType=JdbcType.NCHAR),
        @Result(column="SDDTBS", property="sddtbs", jdbcType=JdbcType.NCHAR),
        @Result(column="SDTRDC", property="sdtrdc", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDFUN2", property="sdfun2", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDASN", property="sdasn", jdbcType=JdbcType.NCHAR),
        @Result(column="SDPRGR", property="sdprgr", jdbcType=JdbcType.NCHAR),
        @Result(column="SDCLVL", property="sdclvl", jdbcType=JdbcType.NCHAR),
        @Result(column="SDCADC", property="sdcadc", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDKCO", property="sdkco", jdbcType=JdbcType.NCHAR),
        @Result(column="SDDOC", property="sddoc", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDDCT", property="sddct", jdbcType=JdbcType.NCHAR),
        @Result(column="SDODOC", property="sdodoc", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDODCT", property="sdodct", jdbcType=JdbcType.NCHAR),
        @Result(column="SDOKC", property="sdokc", jdbcType=JdbcType.NCHAR),
        @Result(column="SDPSN", property="sdpsn", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDDELN", property="sddeln", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDTAX1", property="sdtax1", jdbcType=JdbcType.NCHAR),
        @Result(column="SDTXA1", property="sdtxa1", jdbcType=JdbcType.NCHAR),
        @Result(column="SDEXR1", property="sdexr1", jdbcType=JdbcType.NCHAR),
        @Result(column="SDATXT", property="sdatxt", jdbcType=JdbcType.NCHAR),
        @Result(column="SDPRIO", property="sdprio", jdbcType=JdbcType.NCHAR),
        @Result(column="SDRESL", property="sdresl", jdbcType=JdbcType.NCHAR),
        @Result(column="SDBACK", property="sdback", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSBAL", property="sdsbal", jdbcType=JdbcType.NCHAR),
        @Result(column="SDAPTS", property="sdapts", jdbcType=JdbcType.NCHAR),
        @Result(column="SDLOB", property="sdlob", jdbcType=JdbcType.NCHAR),
        @Result(column="SDEUSE", property="sdeuse", jdbcType=JdbcType.NCHAR),
        @Result(column="SDDTYS", property="sddtys", jdbcType=JdbcType.NCHAR),
        @Result(column="SDNTR", property="sdntr", jdbcType=JdbcType.NCHAR),
        @Result(column="SDVEND", property="sdvend", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDCARS", property="sdcars", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDMOT", property="sdmot", jdbcType=JdbcType.NCHAR),
        @Result(column="SDROUT", property="sdrout", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSTOP", property="sdstop", jdbcType=JdbcType.NCHAR),
        @Result(column="SDZON", property="sdzon", jdbcType=JdbcType.NCHAR),
        @Result(column="SDCNID", property="sdcnid", jdbcType=JdbcType.NCHAR),
        @Result(column="SDFRTH", property="sdfrth", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSHCM", property="sdshcm", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSHCN", property="sdshcn", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSERN", property="sdsern", jdbcType=JdbcType.NCHAR),
        @Result(column="SDUOM1", property="sduom1", jdbcType=JdbcType.NCHAR),
        @Result(column="SDPQOR", property="sdpqor", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDUOM2", property="sduom2", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSQOR", property="sdsqor", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDUOM4", property="sduom4", jdbcType=JdbcType.NCHAR),
        @Result(column="SDITWT", property="sditwt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDWTUM", property="sdwtum", jdbcType=JdbcType.NCHAR),
        @Result(column="SDITVL", property="sditvl", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDVLUM", property="sdvlum", jdbcType=JdbcType.NCHAR),
        @Result(column="SDRPRC", property="sdrprc", jdbcType=JdbcType.NCHAR),
        @Result(column="SDORPR", property="sdorpr", jdbcType=JdbcType.NCHAR),
        @Result(column="SDORP", property="sdorp", jdbcType=JdbcType.NCHAR),
        @Result(column="SDCMGP", property="sdcmgp", jdbcType=JdbcType.NCHAR),
        @Result(column="SDGLC", property="sdglc", jdbcType=JdbcType.NCHAR),
        @Result(column="SDCTRY", property="sdctry", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDFY", property="sdfy", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDSO01", property="sdso01", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSO02", property="sdso02", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSO03", property="sdso03", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSO04", property="sdso04", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSO05", property="sdso05", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSO06", property="sdso06", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSO07", property="sdso07", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSO08", property="sdso08", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSO09", property="sdso09", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSO10", property="sdso10", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSO11", property="sdso11", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSO12", property="sdso12", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSO13", property="sdso13", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSO14", property="sdso14", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSO15", property="sdso15", jdbcType=JdbcType.NCHAR),
        @Result(column="SDACOM", property="sdacom", jdbcType=JdbcType.NCHAR),
        @Result(column="SDCMCG", property="sdcmcg", jdbcType=JdbcType.NCHAR),
        @Result(column="SDRCD", property="sdrcd", jdbcType=JdbcType.NCHAR),
        @Result(column="SDGRWT", property="sdgrwt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDGWUM", property="sdgwum", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSBL", property="sdsbl", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSBLT", property="sdsblt", jdbcType=JdbcType.NCHAR),
        @Result(column="SDLCOD", property="sdlcod", jdbcType=JdbcType.NCHAR),
        @Result(column="SDUPC1", property="sdupc1", jdbcType=JdbcType.NCHAR),
        @Result(column="SDUPC2", property="sdupc2", jdbcType=JdbcType.NCHAR),
        @Result(column="SDUPC3", property="sdupc3", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSWMS", property="sdswms", jdbcType=JdbcType.NCHAR),
        @Result(column="SDUNCD", property="sduncd", jdbcType=JdbcType.NCHAR),
        @Result(column="SDCRMD", property="sdcrmd", jdbcType=JdbcType.NCHAR),
        @Result(column="SDCRCD", property="sdcrcd", jdbcType=JdbcType.NCHAR),
        @Result(column="SDCRR", property="sdcrr", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDFPRC", property="sdfprc", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDFUP", property="sdfup", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDFEA", property="sdfea", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDFUC", property="sdfuc", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDFEC", property="sdfec", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDURCD", property="sdurcd", jdbcType=JdbcType.NCHAR),
        @Result(column="SDURDT", property="sdurdt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDURAT", property="sdurat", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDURAB", property="sdurab", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDURRF", property="sdurrf", jdbcType=JdbcType.NCHAR),
        @Result(column="SDTORG", property="sdtorg", jdbcType=JdbcType.NCHAR),
        @Result(column="SDUSER", property="sduser", jdbcType=JdbcType.NCHAR),
        @Result(column="SDPID", property="sdpid", jdbcType=JdbcType.NCHAR),
        @Result(column="SDJOBN", property="sdjobn", jdbcType=JdbcType.NCHAR),
        @Result(column="SDUPMJ", property="sdupmj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDTDAY", property="sdtday", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDSO16", property="sdso16", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSO17", property="sdso17", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSO18", property="sdso18", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSO19", property="sdso19", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSO20", property="sdso20", jdbcType=JdbcType.NCHAR),
        @Result(column="SDIR01", property="sdir01", jdbcType=JdbcType.NCHAR),
        @Result(column="SDIR02", property="sdir02", jdbcType=JdbcType.NCHAR),
        @Result(column="SDIR03", property="sdir03", jdbcType=JdbcType.NCHAR),
        @Result(column="SDIR04", property="sdir04", jdbcType=JdbcType.NCHAR),
        @Result(column="SDIR05", property="sdir05", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSOOR", property="sdsoor", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDVR03", property="sdvr03", jdbcType=JdbcType.NCHAR),
        @Result(column="SDDEID", property="sddeid", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDPSIG", property="sdpsig", jdbcType=JdbcType.NCHAR),
        @Result(column="SDRLNU", property="sdrlnu", jdbcType=JdbcType.NCHAR),
        @Result(column="SDPMDT", property="sdpmdt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDRLTM", property="sdrltm", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDRLDJ", property="sdrldj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDDRQT", property="sddrqt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDADTM", property="sdadtm", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDOPTT", property="sdoptt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDPDTT", property="sdpdtt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDPSTM", property="sdpstm", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDXDCK", property="sdxdck", jdbcType=JdbcType.NCHAR),
        @Result(column="SDXPTY", property="sdxpty", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDDUAL", property="sddual", jdbcType=JdbcType.NCHAR),
        @Result(column="SDBSC", property="sdbsc", jdbcType=JdbcType.NCHAR),
        @Result(column="SDCBSC", property="sdcbsc", jdbcType=JdbcType.NCHAR),
        @Result(column="SDCORD", property="sdcord", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDDVAN", property="sddvan", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDPEND", property="sdpend", jdbcType=JdbcType.NCHAR),
        @Result(column="SDRFRV", property="sdrfrv", jdbcType=JdbcType.NCHAR),
        @Result(column="SDMCLN", property="sdmcln", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDSHPN", property="sdshpn", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDRSDT", property="sdrsdt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDPRJM", property="sdprjm", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDOSEQ", property="sdoseq", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDMERL", property="sdmerl", jdbcType=JdbcType.NCHAR),
        @Result(column="SDHOLD", property="sdhold", jdbcType=JdbcType.NCHAR),
        @Result(column="SDHDBU", property="sdhdbu", jdbcType=JdbcType.NCHAR),
        @Result(column="SDDMBU", property="sddmbu", jdbcType=JdbcType.NCHAR),
        @Result(column="SDBCRC", property="sdbcrc", jdbcType=JdbcType.NCHAR),
        @Result(column="SDODLN", property="sdodln", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDOPDJ", property="sdopdj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDXKCO", property="sdxkco", jdbcType=JdbcType.NCHAR),
        @Result(column="SDXORN", property="sdxorn", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDXCTO", property="sdxcto", jdbcType=JdbcType.NCHAR),
        @Result(column="SDXLLN", property="sdxlln", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDXSFX", property="sdxsfx", jdbcType=JdbcType.NCHAR),
        @Result(column="SDPOE", property="sdpoe", jdbcType=JdbcType.NCHAR),
        @Result(column="SDPMTO", property="sdpmto", jdbcType=JdbcType.NCHAR),
        @Result(column="SDANBY", property="sdanby", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDPMTN", property="sdpmtn", jdbcType=JdbcType.NCHAR),
        @Result(column="SDNUMB", property="sdnumb", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDAAID", property="sdaaid", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDSPATTN", property="sdspattn", jdbcType=JdbcType.NCHAR),
        @Result(column="SDPRAN8", property="sdpran8", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDPRCIDLN", property="sdprcidln", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDCCIDLN", property="sdccidln", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDSHCCIDLN", property="sdshccidln", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDOPPID", property="sdoppid", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDOSTP", property="sdostp", jdbcType=JdbcType.NCHAR),
        @Result(column="SDUKID", property="sdukid", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDCATNM", property="sdcatnm", jdbcType=JdbcType.NCHAR),
        @Result(column="SDALLOC", property="sdalloc", jdbcType=JdbcType.NCHAR),
        @Result(column="SDFULPID", property="sdfulpid", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDALLSTS", property="sdallsts", jdbcType=JdbcType.NCHAR),
        @Result(column="SDOSCORE", property="sdoscore", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDOSCOREO", property="sdoscoreo", jdbcType=JdbcType.NCHAR),
        @Result(column="SDCMCO", property="sdcmco", jdbcType=JdbcType.NCHAR),
        @Result(column="SDKITID", property="sdkitid", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDKITAMTDOM", property="sdkitamtdom", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDKITAMTFOR", property="sdkitamtfor", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDKITDIRTY", property="sdkitdirty", jdbcType=JdbcType.NCHAR),
        @Result(column="SDOCITT", property="sdocitt", jdbcType=JdbcType.NCHAR),
        @Result(column="SDOCCARDNO", property="sdoccardno", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDPMPN", property="sdpmpn", jdbcType=JdbcType.NCHAR),
        @Result(column="SDPNS", property="sdpns", jdbcType=JdbcType.DECIMAL)
    })
    F4211 selectByPrimaryKey(@Param("sddoco") BigDecimal sddoco, @Param("sddcto") String sddcto, @Param("sdkcoo") String sdkcoo, @Param("sdlnid") BigDecimal sdlnid);

    @Select({
        "select",
        "SDDOCO, SDDCTO, SDKCOO, SDLNID, SDSFXO, SDMCU, SDCO, SDOKCO, SDOORN, SDOCTO, ",
        "SDOGNO, SDRKCO, SDRORN, SDRCTO, SDRLLN, SDDMCT, SDDMCS, SDAN8, SDSHAN, SDPA8, ",
        "SDDRQJ, SDTRDJ, SDPDDJ, SDADDJ, SDIVD, SDCNDJ, SDDGL, SDRSDJ, SDPEFJ, SDPPDJ, ",
        "SDVR01, SDVR02, SDITM, SDLITM, SDAITM, SDLOCN, SDLOTN, SDFRGD, SDTHGD, SDFRMP, ",
        "SDTHRP, SDEXDP, SDDSC1, SDDSC2, SDLNTY, SDNXTR, SDLTTR, SDEMCU, SDRLIT, SDKTLN, ",
        "SDCPNT, SDRKIT, SDKTP, SDSRP1, SDSRP2, SDSRP3, SDSRP4, SDSRP5, SDPRP1, SDPRP2, ",
        "SDPRP3, SDPRP4, SDPRP5, SDUOM, SDUORG, SDSOQS, SDSOBK, SDSOCN, SDSONE, SDUOPN, ",
        "SDQTYT, SDQRLV, SDCOMM, SDOTQY, SDUPRC, SDAEXP, SDAOPN, SDPROV, SDTPC, SDAPUM, ",
        "SDLPRC, SDUNCS, SDECST, SDCSTO, SDTCST, SDINMG, SDPTC, SDRYIN, SDDTBS, SDTRDC, ",
        "SDFUN2, SDASN, SDPRGR, SDCLVL, SDCADC, SDKCO, SDDOC, SDDCT, SDODOC, SDODCT, ",
        "SDOKC, SDPSN, SDDELN, SDTAX1, SDTXA1, SDEXR1, SDATXT, SDPRIO, SDRESL, SDBACK, ",
        "SDSBAL, SDAPTS, SDLOB, SDEUSE, SDDTYS, SDNTR, SDVEND, SDCARS, SDMOT, SDROUT, ",
        "SDSTOP, SDZON, SDCNID, SDFRTH, SDSHCM, SDSHCN, SDSERN, SDUOM1, SDPQOR, SDUOM2, ",
        "SDSQOR, SDUOM4, SDITWT, SDWTUM, SDITVL, SDVLUM, SDRPRC, SDORPR, SDORP, SDCMGP, ",
        "SDGLC, SDCTRY, SDFY, SDSO01, SDSO02, SDSO03, SDSO04, SDSO05, SDSO06, SDSO07, ",
        "SDSO08, SDSO09, SDSO10, SDSO11, SDSO12, SDSO13, SDSO14, SDSO15, SDACOM, SDCMCG, ",
        "SDRCD, SDGRWT, SDGWUM, SDSBL, SDSBLT, SDLCOD, SDUPC1, SDUPC2, SDUPC3, SDSWMS, ",
        "SDUNCD, SDCRMD, SDCRCD, SDCRR, SDFPRC, SDFUP, SDFEA, SDFUC, SDFEC, SDURCD, SDURDT, ",
        "SDURAT, SDURAB, SDURRF, SDTORG, SDUSER, SDPID, SDJOBN, SDUPMJ, SDTDAY, SDSO16, ",
        "SDSO17, SDSO18, SDSO19, SDSO20, SDIR01, SDIR02, SDIR03, SDIR04, SDIR05, SDSOOR, ",
        "SDVR03, SDDEID, SDPSIG, SDRLNU, SDPMDT, SDRLTM, SDRLDJ, SDDRQT, SDADTM, SDOPTT, ",
        "SDPDTT, SDPSTM, SDXDCK, SDXPTY, SDDUAL, SDBSC, SDCBSC, SDCORD, SDDVAN, SDPEND, ",
        "SDRFRV, SDMCLN, SDSHPN, SDRSDT, SDPRJM, SDOSEQ, SDMERL, SDHOLD, SDHDBU, SDDMBU, ",
        "SDBCRC, SDODLN, SDOPDJ, SDXKCO, SDXORN, SDXCTO, SDXLLN, SDXSFX, SDPOE, SDPMTO, ",
        "SDANBY, SDPMTN, SDNUMB, SDAAID, SDSPATTN, SDPRAN8, SDPRCIDLN, SDCCIDLN, SDSHCCIDLN, ",
        "SDOPPID, SDOSTP, SDUKID, SDCATNM, SDALLOC, SDFULPID, SDALLSTS, SDOSCORE, SDOSCOREO, ",
        "SDCMCO, SDKITID, SDKITAMTDOM, SDKITAMTFOR, SDKITDIRTY, SDOCITT, SDOCCARDNO, ",
        "SDPMPN, SDPNS",
        "from F4211"
    })
    @Results({
        @Result(column="SDDOCO", property="sddoco", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="SDDCTO", property="sddcto", jdbcType=JdbcType.NCHAR, id=true),
        @Result(column="SDKCOO", property="sdkcoo", jdbcType=JdbcType.NCHAR, id=true),
        @Result(column="SDLNID", property="sdlnid", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="SDSFXO", property="sdsfxo", jdbcType=JdbcType.NCHAR),
        @Result(column="SDMCU", property="sdmcu", jdbcType=JdbcType.NCHAR),
        @Result(column="SDCO", property="sdco", jdbcType=JdbcType.NCHAR),
        @Result(column="SDOKCO", property="sdokco", jdbcType=JdbcType.NCHAR),
        @Result(column="SDOORN", property="sdoorn", jdbcType=JdbcType.NCHAR),
        @Result(column="SDOCTO", property="sdocto", jdbcType=JdbcType.NCHAR),
        @Result(column="SDOGNO", property="sdogno", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDRKCO", property="sdrkco", jdbcType=JdbcType.NCHAR),
        @Result(column="SDRORN", property="sdrorn", jdbcType=JdbcType.NCHAR),
        @Result(column="SDRCTO", property="sdrcto", jdbcType=JdbcType.NCHAR),
        @Result(column="SDRLLN", property="sdrlln", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDDMCT", property="sddmct", jdbcType=JdbcType.NCHAR),
        @Result(column="SDDMCS", property="sddmcs", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDAN8", property="sdan8", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDSHAN", property="sdshan", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDPA8", property="sdpa8", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDDRQJ", property="sddrqj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDTRDJ", property="sdtrdj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDPDDJ", property="sdpddj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDADDJ", property="sdaddj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDIVD", property="sdivd", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDCNDJ", property="sdcndj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDDGL", property="sddgl", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDRSDJ", property="sdrsdj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDPEFJ", property="sdpefj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDPPDJ", property="sdppdj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDVR01", property="sdvr01", jdbcType=JdbcType.NCHAR),
        @Result(column="SDVR02", property="sdvr02", jdbcType=JdbcType.NCHAR),
        @Result(column="SDITM", property="sditm", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDLITM", property="sdlitm", jdbcType=JdbcType.NCHAR),
        @Result(column="SDAITM", property="sdaitm", jdbcType=JdbcType.NCHAR),
        @Result(column="SDLOCN", property="sdlocn", jdbcType=JdbcType.NCHAR),
        @Result(column="SDLOTN", property="sdlotn", jdbcType=JdbcType.NCHAR),
        @Result(column="SDFRGD", property="sdfrgd", jdbcType=JdbcType.NCHAR),
        @Result(column="SDTHGD", property="sdthgd", jdbcType=JdbcType.NCHAR),
        @Result(column="SDFRMP", property="sdfrmp", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDTHRP", property="sdthrp", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDEXDP", property="sdexdp", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDDSC1", property="sddsc1", jdbcType=JdbcType.NCHAR),
        @Result(column="SDDSC2", property="sddsc2", jdbcType=JdbcType.NCHAR),
        @Result(column="SDLNTY", property="sdlnty", jdbcType=JdbcType.NCHAR),
        @Result(column="SDNXTR", property="sdnxtr", jdbcType=JdbcType.NCHAR),
        @Result(column="SDLTTR", property="sdlttr", jdbcType=JdbcType.NCHAR),
        @Result(column="SDEMCU", property="sdemcu", jdbcType=JdbcType.NCHAR),
        @Result(column="SDRLIT", property="sdrlit", jdbcType=JdbcType.NCHAR),
        @Result(column="SDKTLN", property="sdktln", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDCPNT", property="sdcpnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDRKIT", property="sdrkit", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDKTP", property="sdktp", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDSRP1", property="sdsrp1", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSRP2", property="sdsrp2", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSRP3", property="sdsrp3", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSRP4", property="sdsrp4", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSRP5", property="sdsrp5", jdbcType=JdbcType.NCHAR),
        @Result(column="SDPRP1", property="sdprp1", jdbcType=JdbcType.NCHAR),
        @Result(column="SDPRP2", property="sdprp2", jdbcType=JdbcType.NCHAR),
        @Result(column="SDPRP3", property="sdprp3", jdbcType=JdbcType.NCHAR),
        @Result(column="SDPRP4", property="sdprp4", jdbcType=JdbcType.NCHAR),
        @Result(column="SDPRP5", property="sdprp5", jdbcType=JdbcType.NCHAR),
        @Result(column="SDUOM", property="sduom", jdbcType=JdbcType.NCHAR),
        @Result(column="SDUORG", property="sduorg", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDSOQS", property="sdsoqs", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDSOBK", property="sdsobk", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDSOCN", property="sdsocn", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDSONE", property="sdsone", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDUOPN", property="sduopn", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDQTYT", property="sdqtyt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDQRLV", property="sdqrlv", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDCOMM", property="sdcomm", jdbcType=JdbcType.NCHAR),
        @Result(column="SDOTQY", property="sdotqy", jdbcType=JdbcType.NCHAR),
        @Result(column="SDUPRC", property="sduprc", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDAEXP", property="sdaexp", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDAOPN", property="sdaopn", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDPROV", property="sdprov", jdbcType=JdbcType.NCHAR),
        @Result(column="SDTPC", property="sdtpc", jdbcType=JdbcType.NCHAR),
        @Result(column="SDAPUM", property="sdapum", jdbcType=JdbcType.NCHAR),
        @Result(column="SDLPRC", property="sdlprc", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDUNCS", property="sduncs", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDECST", property="sdecst", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDCSTO", property="sdcsto", jdbcType=JdbcType.NCHAR),
        @Result(column="SDTCST", property="sdtcst", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDINMG", property="sdinmg", jdbcType=JdbcType.NCHAR),
        @Result(column="SDPTC", property="sdptc", jdbcType=JdbcType.NCHAR),
        @Result(column="SDRYIN", property="sdryin", jdbcType=JdbcType.NCHAR),
        @Result(column="SDDTBS", property="sddtbs", jdbcType=JdbcType.NCHAR),
        @Result(column="SDTRDC", property="sdtrdc", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDFUN2", property="sdfun2", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDASN", property="sdasn", jdbcType=JdbcType.NCHAR),
        @Result(column="SDPRGR", property="sdprgr", jdbcType=JdbcType.NCHAR),
        @Result(column="SDCLVL", property="sdclvl", jdbcType=JdbcType.NCHAR),
        @Result(column="SDCADC", property="sdcadc", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDKCO", property="sdkco", jdbcType=JdbcType.NCHAR),
        @Result(column="SDDOC", property="sddoc", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDDCT", property="sddct", jdbcType=JdbcType.NCHAR),
        @Result(column="SDODOC", property="sdodoc", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDODCT", property="sdodct", jdbcType=JdbcType.NCHAR),
        @Result(column="SDOKC", property="sdokc", jdbcType=JdbcType.NCHAR),
        @Result(column="SDPSN", property="sdpsn", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDDELN", property="sddeln", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDTAX1", property="sdtax1", jdbcType=JdbcType.NCHAR),
        @Result(column="SDTXA1", property="sdtxa1", jdbcType=JdbcType.NCHAR),
        @Result(column="SDEXR1", property="sdexr1", jdbcType=JdbcType.NCHAR),
        @Result(column="SDATXT", property="sdatxt", jdbcType=JdbcType.NCHAR),
        @Result(column="SDPRIO", property="sdprio", jdbcType=JdbcType.NCHAR),
        @Result(column="SDRESL", property="sdresl", jdbcType=JdbcType.NCHAR),
        @Result(column="SDBACK", property="sdback", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSBAL", property="sdsbal", jdbcType=JdbcType.NCHAR),
        @Result(column="SDAPTS", property="sdapts", jdbcType=JdbcType.NCHAR),
        @Result(column="SDLOB", property="sdlob", jdbcType=JdbcType.NCHAR),
        @Result(column="SDEUSE", property="sdeuse", jdbcType=JdbcType.NCHAR),
        @Result(column="SDDTYS", property="sddtys", jdbcType=JdbcType.NCHAR),
        @Result(column="SDNTR", property="sdntr", jdbcType=JdbcType.NCHAR),
        @Result(column="SDVEND", property="sdvend", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDCARS", property="sdcars", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDMOT", property="sdmot", jdbcType=JdbcType.NCHAR),
        @Result(column="SDROUT", property="sdrout", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSTOP", property="sdstop", jdbcType=JdbcType.NCHAR),
        @Result(column="SDZON", property="sdzon", jdbcType=JdbcType.NCHAR),
        @Result(column="SDCNID", property="sdcnid", jdbcType=JdbcType.NCHAR),
        @Result(column="SDFRTH", property="sdfrth", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSHCM", property="sdshcm", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSHCN", property="sdshcn", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSERN", property="sdsern", jdbcType=JdbcType.NCHAR),
        @Result(column="SDUOM1", property="sduom1", jdbcType=JdbcType.NCHAR),
        @Result(column="SDPQOR", property="sdpqor", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDUOM2", property="sduom2", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSQOR", property="sdsqor", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDUOM4", property="sduom4", jdbcType=JdbcType.NCHAR),
        @Result(column="SDITWT", property="sditwt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDWTUM", property="sdwtum", jdbcType=JdbcType.NCHAR),
        @Result(column="SDITVL", property="sditvl", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDVLUM", property="sdvlum", jdbcType=JdbcType.NCHAR),
        @Result(column="SDRPRC", property="sdrprc", jdbcType=JdbcType.NCHAR),
        @Result(column="SDORPR", property="sdorpr", jdbcType=JdbcType.NCHAR),
        @Result(column="SDORP", property="sdorp", jdbcType=JdbcType.NCHAR),
        @Result(column="SDCMGP", property="sdcmgp", jdbcType=JdbcType.NCHAR),
        @Result(column="SDGLC", property="sdglc", jdbcType=JdbcType.NCHAR),
        @Result(column="SDCTRY", property="sdctry", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDFY", property="sdfy", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDSO01", property="sdso01", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSO02", property="sdso02", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSO03", property="sdso03", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSO04", property="sdso04", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSO05", property="sdso05", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSO06", property="sdso06", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSO07", property="sdso07", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSO08", property="sdso08", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSO09", property="sdso09", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSO10", property="sdso10", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSO11", property="sdso11", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSO12", property="sdso12", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSO13", property="sdso13", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSO14", property="sdso14", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSO15", property="sdso15", jdbcType=JdbcType.NCHAR),
        @Result(column="SDACOM", property="sdacom", jdbcType=JdbcType.NCHAR),
        @Result(column="SDCMCG", property="sdcmcg", jdbcType=JdbcType.NCHAR),
        @Result(column="SDRCD", property="sdrcd", jdbcType=JdbcType.NCHAR),
        @Result(column="SDGRWT", property="sdgrwt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDGWUM", property="sdgwum", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSBL", property="sdsbl", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSBLT", property="sdsblt", jdbcType=JdbcType.NCHAR),
        @Result(column="SDLCOD", property="sdlcod", jdbcType=JdbcType.NCHAR),
        @Result(column="SDUPC1", property="sdupc1", jdbcType=JdbcType.NCHAR),
        @Result(column="SDUPC2", property="sdupc2", jdbcType=JdbcType.NCHAR),
        @Result(column="SDUPC3", property="sdupc3", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSWMS", property="sdswms", jdbcType=JdbcType.NCHAR),
        @Result(column="SDUNCD", property="sduncd", jdbcType=JdbcType.NCHAR),
        @Result(column="SDCRMD", property="sdcrmd", jdbcType=JdbcType.NCHAR),
        @Result(column="SDCRCD", property="sdcrcd", jdbcType=JdbcType.NCHAR),
        @Result(column="SDCRR", property="sdcrr", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDFPRC", property="sdfprc", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDFUP", property="sdfup", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDFEA", property="sdfea", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDFUC", property="sdfuc", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDFEC", property="sdfec", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDURCD", property="sdurcd", jdbcType=JdbcType.NCHAR),
        @Result(column="SDURDT", property="sdurdt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDURAT", property="sdurat", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDURAB", property="sdurab", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDURRF", property="sdurrf", jdbcType=JdbcType.NCHAR),
        @Result(column="SDTORG", property="sdtorg", jdbcType=JdbcType.NCHAR),
        @Result(column="SDUSER", property="sduser", jdbcType=JdbcType.NCHAR),
        @Result(column="SDPID", property="sdpid", jdbcType=JdbcType.NCHAR),
        @Result(column="SDJOBN", property="sdjobn", jdbcType=JdbcType.NCHAR),
        @Result(column="SDUPMJ", property="sdupmj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDTDAY", property="sdtday", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDSO16", property="sdso16", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSO17", property="sdso17", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSO18", property="sdso18", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSO19", property="sdso19", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSO20", property="sdso20", jdbcType=JdbcType.NCHAR),
        @Result(column="SDIR01", property="sdir01", jdbcType=JdbcType.NCHAR),
        @Result(column="SDIR02", property="sdir02", jdbcType=JdbcType.NCHAR),
        @Result(column="SDIR03", property="sdir03", jdbcType=JdbcType.NCHAR),
        @Result(column="SDIR04", property="sdir04", jdbcType=JdbcType.NCHAR),
        @Result(column="SDIR05", property="sdir05", jdbcType=JdbcType.NCHAR),
        @Result(column="SDSOOR", property="sdsoor", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDVR03", property="sdvr03", jdbcType=JdbcType.NCHAR),
        @Result(column="SDDEID", property="sddeid", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDPSIG", property="sdpsig", jdbcType=JdbcType.NCHAR),
        @Result(column="SDRLNU", property="sdrlnu", jdbcType=JdbcType.NCHAR),
        @Result(column="SDPMDT", property="sdpmdt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDRLTM", property="sdrltm", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDRLDJ", property="sdrldj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDDRQT", property="sddrqt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDADTM", property="sdadtm", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDOPTT", property="sdoptt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDPDTT", property="sdpdtt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDPSTM", property="sdpstm", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDXDCK", property="sdxdck", jdbcType=JdbcType.NCHAR),
        @Result(column="SDXPTY", property="sdxpty", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDDUAL", property="sddual", jdbcType=JdbcType.NCHAR),
        @Result(column="SDBSC", property="sdbsc", jdbcType=JdbcType.NCHAR),
        @Result(column="SDCBSC", property="sdcbsc", jdbcType=JdbcType.NCHAR),
        @Result(column="SDCORD", property="sdcord", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDDVAN", property="sddvan", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDPEND", property="sdpend", jdbcType=JdbcType.NCHAR),
        @Result(column="SDRFRV", property="sdrfrv", jdbcType=JdbcType.NCHAR),
        @Result(column="SDMCLN", property="sdmcln", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDSHPN", property="sdshpn", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDRSDT", property="sdrsdt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDPRJM", property="sdprjm", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDOSEQ", property="sdoseq", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDMERL", property="sdmerl", jdbcType=JdbcType.NCHAR),
        @Result(column="SDHOLD", property="sdhold", jdbcType=JdbcType.NCHAR),
        @Result(column="SDHDBU", property="sdhdbu", jdbcType=JdbcType.NCHAR),
        @Result(column="SDDMBU", property="sddmbu", jdbcType=JdbcType.NCHAR),
        @Result(column="SDBCRC", property="sdbcrc", jdbcType=JdbcType.NCHAR),
        @Result(column="SDODLN", property="sdodln", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDOPDJ", property="sdopdj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDXKCO", property="sdxkco", jdbcType=JdbcType.NCHAR),
        @Result(column="SDXORN", property="sdxorn", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDXCTO", property="sdxcto", jdbcType=JdbcType.NCHAR),
        @Result(column="SDXLLN", property="sdxlln", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDXSFX", property="sdxsfx", jdbcType=JdbcType.NCHAR),
        @Result(column="SDPOE", property="sdpoe", jdbcType=JdbcType.NCHAR),
        @Result(column="SDPMTO", property="sdpmto", jdbcType=JdbcType.NCHAR),
        @Result(column="SDANBY", property="sdanby", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDPMTN", property="sdpmtn", jdbcType=JdbcType.NCHAR),
        @Result(column="SDNUMB", property="sdnumb", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDAAID", property="sdaaid", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDSPATTN", property="sdspattn", jdbcType=JdbcType.NCHAR),
        @Result(column="SDPRAN8", property="sdpran8", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDPRCIDLN", property="sdprcidln", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDCCIDLN", property="sdccidln", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDSHCCIDLN", property="sdshccidln", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDOPPID", property="sdoppid", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDOSTP", property="sdostp", jdbcType=JdbcType.NCHAR),
        @Result(column="SDUKID", property="sdukid", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDCATNM", property="sdcatnm", jdbcType=JdbcType.NCHAR),
        @Result(column="SDALLOC", property="sdalloc", jdbcType=JdbcType.NCHAR),
        @Result(column="SDFULPID", property="sdfulpid", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDALLSTS", property="sdallsts", jdbcType=JdbcType.NCHAR),
        @Result(column="SDOSCORE", property="sdoscore", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDOSCOREO", property="sdoscoreo", jdbcType=JdbcType.NCHAR),
        @Result(column="SDCMCO", property="sdcmco", jdbcType=JdbcType.NCHAR),
        @Result(column="SDKITID", property="sdkitid", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDKITAMTDOM", property="sdkitamtdom", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDKITAMTFOR", property="sdkitamtfor", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDKITDIRTY", property="sdkitdirty", jdbcType=JdbcType.NCHAR),
        @Result(column="SDOCITT", property="sdocitt", jdbcType=JdbcType.NCHAR),
        @Result(column="SDOCCARDNO", property="sdoccardno", jdbcType=JdbcType.DECIMAL),
        @Result(column="SDPMPN", property="sdpmpn", jdbcType=JdbcType.NCHAR),
        @Result(column="SDPNS", property="sdpns", jdbcType=JdbcType.DECIMAL)
    })
    List<F4211> selectAll();
}