package com.el.cfg.mapper;

import com.el.cfg.domain.F0006;
import java.util.List;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

public interface F0006Mapper {
    @Select({
        "select",
        "MCMCU, MCSTYL, MCDC, MCLDM, MCCO, MCAN8, MCAN8O, MCCNTY, MCADDS, MCFMOD, MCDL01, ",
        "MCDL02, MCDL03, MCDL04, MCRP01, MCRP02, MCRP03, MCRP04, MCRP05, MCRP06, MCRP07, ",
        "MCRP08, MCRP09, MCRP10, MCRP11, MCRP12, MCRP13, MCRP14, MCRP15, MCRP16, MCRP17, ",
        "MCRP18, MCRP19, MCRP20, MCRP21, MCRP22, MCRP23, MCRP24, MCRP25, MCRP26, MCRP27, ",
        "MCRP28, MCRP29, MCRP30, MCTA, MCTXJS, MCTXA1, MCEXR1, MCTC01, MCTC02, MCTC03, ",
        "MCTC04, MCTC05, MCTC06, MCTC07, MCTC08, MCTC09, MCTC10, MCND01, MCND02, MCND03, ",
        "MCND04, MCND05, MCND06, MCND07, MCND08, MCND09, MCND10, MCCC01, MCCC02, MCCC03, ",
        "MCCC04, MCCC05, MCCC06, MCCC07, MCCC08, MCCC09, MCCC10, MCPECC, MCALS, MCISS, ",
        "MCGLBA, MCALCL, MCLMTH, MCLF, MCOBJ1, MCOBJ2, MCOBJ3, MCSUB1, MCTOU, MCSBLI, ",
        "MCANPA, MCCT, MCCERT, MCMCUS, MCBTYP, MCPC, MCPCA, MCPCC, MCINTA, MCINTL, MCD1J, ",
        "MCD2J, MCD3J, MCD4J, MCD5J, MCD6J, MCFPDJ, MCCAC, MCPAC, MCEEO, MCERC, MCUSER, ",
        "MCPID, MCUPMJ, MCJOBN, MCUPMT, MCBPTP, MCAPSB, MCTSBU, MCRP31, MCRP32, MCRP33, ",
        "MCRP34, MCRP35, MCRP36, MCRP37, MCRP38, MCRP39, MCRP40, MCRP41, MCRP42, MCRP43, ",
        "MCRP44, MCRP45, MCRP46, MCRP47, MCRP48, MCRP49, MCRP50, MCAN8GCA1, MCAN8GCA2, ",
        "MCAN8GCA3, MCAN8GCA4, MCAN8GCA5, MCRMCU1, MCDOCO, MCPCTN, MCCLNU, MCBUCA, MCADJENT, ",
        "MCUAFL",
        "from F0006",
        "where MCMCU = #{mcmcu,jdbcType=NCHAR}"
    })
    @Results({
        @Result(column="MCMCU", property="mcmcu", jdbcType=JdbcType.NCHAR, id=true),
        @Result(column="MCSTYL", property="mcstyl", jdbcType=JdbcType.NCHAR),
        @Result(column="MCDC", property="mcdc", jdbcType=JdbcType.NCHAR),
        @Result(column="MCLDM", property="mcldm", jdbcType=JdbcType.NCHAR),
        @Result(column="MCCO", property="mcco", jdbcType=JdbcType.NCHAR),
        @Result(column="MCAN8", property="mcan8", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCAN8O", property="mcan8o", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCCNTY", property="mccnty", jdbcType=JdbcType.NCHAR),
        @Result(column="MCADDS", property="mcadds", jdbcType=JdbcType.NCHAR),
        @Result(column="MCFMOD", property="mcfmod", jdbcType=JdbcType.NCHAR),
        @Result(column="MCDL01", property="mcdl01", jdbcType=JdbcType.NCHAR),
        @Result(column="MCDL02", property="mcdl02", jdbcType=JdbcType.NCHAR),
        @Result(column="MCDL03", property="mcdl03", jdbcType=JdbcType.NCHAR),
        @Result(column="MCDL04", property="mcdl04", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP01", property="mcrp01", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP02", property="mcrp02", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP03", property="mcrp03", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP04", property="mcrp04", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP05", property="mcrp05", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP06", property="mcrp06", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP07", property="mcrp07", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP08", property="mcrp08", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP09", property="mcrp09", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP10", property="mcrp10", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP11", property="mcrp11", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP12", property="mcrp12", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP13", property="mcrp13", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP14", property="mcrp14", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP15", property="mcrp15", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP16", property="mcrp16", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP17", property="mcrp17", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP18", property="mcrp18", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP19", property="mcrp19", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP20", property="mcrp20", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP21", property="mcrp21", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP22", property="mcrp22", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP23", property="mcrp23", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP24", property="mcrp24", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP25", property="mcrp25", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP26", property="mcrp26", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP27", property="mcrp27", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP28", property="mcrp28", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP29", property="mcrp29", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP30", property="mcrp30", jdbcType=JdbcType.NCHAR),
        @Result(column="MCTA", property="mcta", jdbcType=JdbcType.NCHAR),
        @Result(column="MCTXJS", property="mctxjs", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCTXA1", property="mctxa1", jdbcType=JdbcType.NCHAR),
        @Result(column="MCEXR1", property="mcexr1", jdbcType=JdbcType.NCHAR),
        @Result(column="MCTC01", property="mctc01", jdbcType=JdbcType.NCHAR),
        @Result(column="MCTC02", property="mctc02", jdbcType=JdbcType.NCHAR),
        @Result(column="MCTC03", property="mctc03", jdbcType=JdbcType.NCHAR),
        @Result(column="MCTC04", property="mctc04", jdbcType=JdbcType.NCHAR),
        @Result(column="MCTC05", property="mctc05", jdbcType=JdbcType.NCHAR),
        @Result(column="MCTC06", property="mctc06", jdbcType=JdbcType.NCHAR),
        @Result(column="MCTC07", property="mctc07", jdbcType=JdbcType.NCHAR),
        @Result(column="MCTC08", property="mctc08", jdbcType=JdbcType.NCHAR),
        @Result(column="MCTC09", property="mctc09", jdbcType=JdbcType.NCHAR),
        @Result(column="MCTC10", property="mctc10", jdbcType=JdbcType.NCHAR),
        @Result(column="MCND01", property="mcnd01", jdbcType=JdbcType.NCHAR),
        @Result(column="MCND02", property="mcnd02", jdbcType=JdbcType.NCHAR),
        @Result(column="MCND03", property="mcnd03", jdbcType=JdbcType.NCHAR),
        @Result(column="MCND04", property="mcnd04", jdbcType=JdbcType.NCHAR),
        @Result(column="MCND05", property="mcnd05", jdbcType=JdbcType.NCHAR),
        @Result(column="MCND06", property="mcnd06", jdbcType=JdbcType.NCHAR),
        @Result(column="MCND07", property="mcnd07", jdbcType=JdbcType.NCHAR),
        @Result(column="MCND08", property="mcnd08", jdbcType=JdbcType.NCHAR),
        @Result(column="MCND09", property="mcnd09", jdbcType=JdbcType.NCHAR),
        @Result(column="MCND10", property="mcnd10", jdbcType=JdbcType.NCHAR),
        @Result(column="MCCC01", property="mccc01", jdbcType=JdbcType.NCHAR),
        @Result(column="MCCC02", property="mccc02", jdbcType=JdbcType.NCHAR),
        @Result(column="MCCC03", property="mccc03", jdbcType=JdbcType.NCHAR),
        @Result(column="MCCC04", property="mccc04", jdbcType=JdbcType.NCHAR),
        @Result(column="MCCC05", property="mccc05", jdbcType=JdbcType.NCHAR),
        @Result(column="MCCC06", property="mccc06", jdbcType=JdbcType.NCHAR),
        @Result(column="MCCC07", property="mccc07", jdbcType=JdbcType.NCHAR),
        @Result(column="MCCC08", property="mccc08", jdbcType=JdbcType.NCHAR),
        @Result(column="MCCC09", property="mccc09", jdbcType=JdbcType.NCHAR),
        @Result(column="MCCC10", property="mccc10", jdbcType=JdbcType.NCHAR),
        @Result(column="MCPECC", property="mcpecc", jdbcType=JdbcType.NCHAR),
        @Result(column="MCALS", property="mcals", jdbcType=JdbcType.NCHAR),
        @Result(column="MCISS", property="mciss", jdbcType=JdbcType.NCHAR),
        @Result(column="MCGLBA", property="mcglba", jdbcType=JdbcType.NCHAR),
        @Result(column="MCALCL", property="mcalcl", jdbcType=JdbcType.NCHAR),
        @Result(column="MCLMTH", property="mclmth", jdbcType=JdbcType.NCHAR),
        @Result(column="MCLF", property="mclf", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCOBJ1", property="mcobj1", jdbcType=JdbcType.NCHAR),
        @Result(column="MCOBJ2", property="mcobj2", jdbcType=JdbcType.NCHAR),
        @Result(column="MCOBJ3", property="mcobj3", jdbcType=JdbcType.NCHAR),
        @Result(column="MCSUB1", property="mcsub1", jdbcType=JdbcType.NCHAR),
        @Result(column="MCTOU", property="mctou", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCSBLI", property="mcsbli", jdbcType=JdbcType.NCHAR),
        @Result(column="MCANPA", property="mcanpa", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCCT", property="mcct", jdbcType=JdbcType.NCHAR),
        @Result(column="MCCERT", property="mccert", jdbcType=JdbcType.NCHAR),
        @Result(column="MCMCUS", property="mcmcus", jdbcType=JdbcType.NCHAR),
        @Result(column="MCBTYP", property="mcbtyp", jdbcType=JdbcType.NCHAR),
        @Result(column="MCPC", property="mcpc", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCPCA", property="mcpca", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCPCC", property="mcpcc", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCINTA", property="mcinta", jdbcType=JdbcType.NCHAR),
        @Result(column="MCINTL", property="mcintl", jdbcType=JdbcType.NCHAR),
        @Result(column="MCD1J", property="mcd1j", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCD2J", property="mcd2j", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCD3J", property="mcd3j", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCD4J", property="mcd4j", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCD5J", property="mcd5j", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCD6J", property="mcd6j", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCFPDJ", property="mcfpdj", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCCAC", property="mccac", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCPAC", property="mcpac", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCEEO", property="mceeo", jdbcType=JdbcType.NCHAR),
        @Result(column="MCERC", property="mcerc", jdbcType=JdbcType.NCHAR),
        @Result(column="MCUSER", property="mcuser", jdbcType=JdbcType.NCHAR),
        @Result(column="MCPID", property="mcpid", jdbcType=JdbcType.NCHAR),
        @Result(column="MCUPMJ", property="mcupmj", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCJOBN", property="mcjobn", jdbcType=JdbcType.NCHAR),
        @Result(column="MCUPMT", property="mcupmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCBPTP", property="mcbptp", jdbcType=JdbcType.NCHAR),
        @Result(column="MCAPSB", property="mcapsb", jdbcType=JdbcType.NCHAR),
        @Result(column="MCTSBU", property="mctsbu", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP31", property="mcrp31", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP32", property="mcrp32", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP33", property="mcrp33", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP34", property="mcrp34", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP35", property="mcrp35", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP36", property="mcrp36", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP37", property="mcrp37", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP38", property="mcrp38", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP39", property="mcrp39", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP40", property="mcrp40", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP41", property="mcrp41", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP42", property="mcrp42", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP43", property="mcrp43", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP44", property="mcrp44", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP45", property="mcrp45", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP46", property="mcrp46", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP47", property="mcrp47", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP48", property="mcrp48", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP49", property="mcrp49", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP50", property="mcrp50", jdbcType=JdbcType.NCHAR),
        @Result(column="MCAN8GCA1", property="mcan8gca1", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCAN8GCA2", property="mcan8gca2", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCAN8GCA3", property="mcan8gca3", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCAN8GCA4", property="mcan8gca4", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCAN8GCA5", property="mcan8gca5", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCRMCU1", property="mcrmcu1", jdbcType=JdbcType.NCHAR),
        @Result(column="MCDOCO", property="mcdoco", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCPCTN", property="mcpctn", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCCLNU", property="mcclnu", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCBUCA", property="mcbuca", jdbcType=JdbcType.NCHAR),
        @Result(column="MCADJENT", property="mcadjent", jdbcType=JdbcType.NCHAR),
        @Result(column="MCUAFL", property="mcuafl", jdbcType=JdbcType.NCHAR)
    })
    F0006 selectByPrimaryKey(String mcmcu);

    @Select({
        "select",
        "MCMCU, MCSTYL, MCDC, MCLDM, MCCO, MCAN8, MCAN8O, MCCNTY, MCADDS, MCFMOD, MCDL01, ",
        "MCDL02, MCDL03, MCDL04, MCRP01, MCRP02, MCRP03, MCRP04, MCRP05, MCRP06, MCRP07, ",
        "MCRP08, MCRP09, MCRP10, MCRP11, MCRP12, MCRP13, MCRP14, MCRP15, MCRP16, MCRP17, ",
        "MCRP18, MCRP19, MCRP20, MCRP21, MCRP22, MCRP23, MCRP24, MCRP25, MCRP26, MCRP27, ",
        "MCRP28, MCRP29, MCRP30, MCTA, MCTXJS, MCTXA1, MCEXR1, MCTC01, MCTC02, MCTC03, ",
        "MCTC04, MCTC05, MCTC06, MCTC07, MCTC08, MCTC09, MCTC10, MCND01, MCND02, MCND03, ",
        "MCND04, MCND05, MCND06, MCND07, MCND08, MCND09, MCND10, MCCC01, MCCC02, MCCC03, ",
        "MCCC04, MCCC05, MCCC06, MCCC07, MCCC08, MCCC09, MCCC10, MCPECC, MCALS, MCISS, ",
        "MCGLBA, MCALCL, MCLMTH, MCLF, MCOBJ1, MCOBJ2, MCOBJ3, MCSUB1, MCTOU, MCSBLI, ",
        "MCANPA, MCCT, MCCERT, MCMCUS, MCBTYP, MCPC, MCPCA, MCPCC, MCINTA, MCINTL, MCD1J, ",
        "MCD2J, MCD3J, MCD4J, MCD5J, MCD6J, MCFPDJ, MCCAC, MCPAC, MCEEO, MCERC, MCUSER, ",
        "MCPID, MCUPMJ, MCJOBN, MCUPMT, MCBPTP, MCAPSB, MCTSBU, MCRP31, MCRP32, MCRP33, ",
        "MCRP34, MCRP35, MCRP36, MCRP37, MCRP38, MCRP39, MCRP40, MCRP41, MCRP42, MCRP43, ",
        "MCRP44, MCRP45, MCRP46, MCRP47, MCRP48, MCRP49, MCRP50, MCAN8GCA1, MCAN8GCA2, ",
        "MCAN8GCA3, MCAN8GCA4, MCAN8GCA5, MCRMCU1, MCDOCO, MCPCTN, MCCLNU, MCBUCA, MCADJENT, ",
        "MCUAFL",
        "from F0006"
    })
    @Results({
        @Result(column="MCMCU", property="mcmcu", jdbcType=JdbcType.NCHAR, id=true),
        @Result(column="MCSTYL", property="mcstyl", jdbcType=JdbcType.NCHAR),
        @Result(column="MCDC", property="mcdc", jdbcType=JdbcType.NCHAR),
        @Result(column="MCLDM", property="mcldm", jdbcType=JdbcType.NCHAR),
        @Result(column="MCCO", property="mcco", jdbcType=JdbcType.NCHAR),
        @Result(column="MCAN8", property="mcan8", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCAN8O", property="mcan8o", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCCNTY", property="mccnty", jdbcType=JdbcType.NCHAR),
        @Result(column="MCADDS", property="mcadds", jdbcType=JdbcType.NCHAR),
        @Result(column="MCFMOD", property="mcfmod", jdbcType=JdbcType.NCHAR),
        @Result(column="MCDL01", property="mcdl01", jdbcType=JdbcType.NCHAR),
        @Result(column="MCDL02", property="mcdl02", jdbcType=JdbcType.NCHAR),
        @Result(column="MCDL03", property="mcdl03", jdbcType=JdbcType.NCHAR),
        @Result(column="MCDL04", property="mcdl04", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP01", property="mcrp01", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP02", property="mcrp02", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP03", property="mcrp03", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP04", property="mcrp04", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP05", property="mcrp05", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP06", property="mcrp06", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP07", property="mcrp07", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP08", property="mcrp08", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP09", property="mcrp09", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP10", property="mcrp10", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP11", property="mcrp11", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP12", property="mcrp12", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP13", property="mcrp13", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP14", property="mcrp14", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP15", property="mcrp15", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP16", property="mcrp16", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP17", property="mcrp17", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP18", property="mcrp18", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP19", property="mcrp19", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP20", property="mcrp20", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP21", property="mcrp21", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP22", property="mcrp22", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP23", property="mcrp23", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP24", property="mcrp24", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP25", property="mcrp25", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP26", property="mcrp26", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP27", property="mcrp27", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP28", property="mcrp28", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP29", property="mcrp29", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP30", property="mcrp30", jdbcType=JdbcType.NCHAR),
        @Result(column="MCTA", property="mcta", jdbcType=JdbcType.NCHAR),
        @Result(column="MCTXJS", property="mctxjs", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCTXA1", property="mctxa1", jdbcType=JdbcType.NCHAR),
        @Result(column="MCEXR1", property="mcexr1", jdbcType=JdbcType.NCHAR),
        @Result(column="MCTC01", property="mctc01", jdbcType=JdbcType.NCHAR),
        @Result(column="MCTC02", property="mctc02", jdbcType=JdbcType.NCHAR),
        @Result(column="MCTC03", property="mctc03", jdbcType=JdbcType.NCHAR),
        @Result(column="MCTC04", property="mctc04", jdbcType=JdbcType.NCHAR),
        @Result(column="MCTC05", property="mctc05", jdbcType=JdbcType.NCHAR),
        @Result(column="MCTC06", property="mctc06", jdbcType=JdbcType.NCHAR),
        @Result(column="MCTC07", property="mctc07", jdbcType=JdbcType.NCHAR),
        @Result(column="MCTC08", property="mctc08", jdbcType=JdbcType.NCHAR),
        @Result(column="MCTC09", property="mctc09", jdbcType=JdbcType.NCHAR),
        @Result(column="MCTC10", property="mctc10", jdbcType=JdbcType.NCHAR),
        @Result(column="MCND01", property="mcnd01", jdbcType=JdbcType.NCHAR),
        @Result(column="MCND02", property="mcnd02", jdbcType=JdbcType.NCHAR),
        @Result(column="MCND03", property="mcnd03", jdbcType=JdbcType.NCHAR),
        @Result(column="MCND04", property="mcnd04", jdbcType=JdbcType.NCHAR),
        @Result(column="MCND05", property="mcnd05", jdbcType=JdbcType.NCHAR),
        @Result(column="MCND06", property="mcnd06", jdbcType=JdbcType.NCHAR),
        @Result(column="MCND07", property="mcnd07", jdbcType=JdbcType.NCHAR),
        @Result(column="MCND08", property="mcnd08", jdbcType=JdbcType.NCHAR),
        @Result(column="MCND09", property="mcnd09", jdbcType=JdbcType.NCHAR),
        @Result(column="MCND10", property="mcnd10", jdbcType=JdbcType.NCHAR),
        @Result(column="MCCC01", property="mccc01", jdbcType=JdbcType.NCHAR),
        @Result(column="MCCC02", property="mccc02", jdbcType=JdbcType.NCHAR),
        @Result(column="MCCC03", property="mccc03", jdbcType=JdbcType.NCHAR),
        @Result(column="MCCC04", property="mccc04", jdbcType=JdbcType.NCHAR),
        @Result(column="MCCC05", property="mccc05", jdbcType=JdbcType.NCHAR),
        @Result(column="MCCC06", property="mccc06", jdbcType=JdbcType.NCHAR),
        @Result(column="MCCC07", property="mccc07", jdbcType=JdbcType.NCHAR),
        @Result(column="MCCC08", property="mccc08", jdbcType=JdbcType.NCHAR),
        @Result(column="MCCC09", property="mccc09", jdbcType=JdbcType.NCHAR),
        @Result(column="MCCC10", property="mccc10", jdbcType=JdbcType.NCHAR),
        @Result(column="MCPECC", property="mcpecc", jdbcType=JdbcType.NCHAR),
        @Result(column="MCALS", property="mcals", jdbcType=JdbcType.NCHAR),
        @Result(column="MCISS", property="mciss", jdbcType=JdbcType.NCHAR),
        @Result(column="MCGLBA", property="mcglba", jdbcType=JdbcType.NCHAR),
        @Result(column="MCALCL", property="mcalcl", jdbcType=JdbcType.NCHAR),
        @Result(column="MCLMTH", property="mclmth", jdbcType=JdbcType.NCHAR),
        @Result(column="MCLF", property="mclf", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCOBJ1", property="mcobj1", jdbcType=JdbcType.NCHAR),
        @Result(column="MCOBJ2", property="mcobj2", jdbcType=JdbcType.NCHAR),
        @Result(column="MCOBJ3", property="mcobj3", jdbcType=JdbcType.NCHAR),
        @Result(column="MCSUB1", property="mcsub1", jdbcType=JdbcType.NCHAR),
        @Result(column="MCTOU", property="mctou", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCSBLI", property="mcsbli", jdbcType=JdbcType.NCHAR),
        @Result(column="MCANPA", property="mcanpa", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCCT", property="mcct", jdbcType=JdbcType.NCHAR),
        @Result(column="MCCERT", property="mccert", jdbcType=JdbcType.NCHAR),
        @Result(column="MCMCUS", property="mcmcus", jdbcType=JdbcType.NCHAR),
        @Result(column="MCBTYP", property="mcbtyp", jdbcType=JdbcType.NCHAR),
        @Result(column="MCPC", property="mcpc", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCPCA", property="mcpca", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCPCC", property="mcpcc", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCINTA", property="mcinta", jdbcType=JdbcType.NCHAR),
        @Result(column="MCINTL", property="mcintl", jdbcType=JdbcType.NCHAR),
        @Result(column="MCD1J", property="mcd1j", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCD2J", property="mcd2j", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCD3J", property="mcd3j", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCD4J", property="mcd4j", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCD5J", property="mcd5j", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCD6J", property="mcd6j", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCFPDJ", property="mcfpdj", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCCAC", property="mccac", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCPAC", property="mcpac", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCEEO", property="mceeo", jdbcType=JdbcType.NCHAR),
        @Result(column="MCERC", property="mcerc", jdbcType=JdbcType.NCHAR),
        @Result(column="MCUSER", property="mcuser", jdbcType=JdbcType.NCHAR),
        @Result(column="MCPID", property="mcpid", jdbcType=JdbcType.NCHAR),
        @Result(column="MCUPMJ", property="mcupmj", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCJOBN", property="mcjobn", jdbcType=JdbcType.NCHAR),
        @Result(column="MCUPMT", property="mcupmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCBPTP", property="mcbptp", jdbcType=JdbcType.NCHAR),
        @Result(column="MCAPSB", property="mcapsb", jdbcType=JdbcType.NCHAR),
        @Result(column="MCTSBU", property="mctsbu", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP31", property="mcrp31", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP32", property="mcrp32", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP33", property="mcrp33", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP34", property="mcrp34", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP35", property="mcrp35", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP36", property="mcrp36", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP37", property="mcrp37", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP38", property="mcrp38", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP39", property="mcrp39", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP40", property="mcrp40", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP41", property="mcrp41", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP42", property="mcrp42", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP43", property="mcrp43", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP44", property="mcrp44", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP45", property="mcrp45", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP46", property="mcrp46", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP47", property="mcrp47", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP48", property="mcrp48", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP49", property="mcrp49", jdbcType=JdbcType.NCHAR),
        @Result(column="MCRP50", property="mcrp50", jdbcType=JdbcType.NCHAR),
        @Result(column="MCAN8GCA1", property="mcan8gca1", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCAN8GCA2", property="mcan8gca2", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCAN8GCA3", property="mcan8gca3", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCAN8GCA4", property="mcan8gca4", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCAN8GCA5", property="mcan8gca5", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCRMCU1", property="mcrmcu1", jdbcType=JdbcType.NCHAR),
        @Result(column="MCDOCO", property="mcdoco", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCPCTN", property="mcpctn", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCCLNU", property="mcclnu", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCBUCA", property="mcbuca", jdbcType=JdbcType.NCHAR),
        @Result(column="MCADJENT", property="mcadjent", jdbcType=JdbcType.NCHAR),
        @Result(column="MCUAFL", property="mcuafl", jdbcType=JdbcType.NCHAR)
    })
    List<F0006> selectAll();
}