package com.el.cfg.mapper;

import com.el.cfg.domain.F47072;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

public interface F47072Mapper {
    @Select({
        "select",
        "SZEDOC, SZEDCT, SZEKCO, SZEDLN, SZEDTY, SZEDSQ, SZEDST, SZEDFT, SZEDDT, SZEDER, ",
        "SZEDDL, SZEDSP, SZEDBT, SZPNID, SZLSTS, SZKCOO, SZDOCO, SZDCTO, SZSFXO, SZLNID, ",
        "SZMCU, SZCO, SZOKCO, SZOORN, SZOCTO, SZOGNO, SZRKCO, SZRORN, SZRCTO, SZRLLN, ",
        "SZDMCT, SZDMCS, SZAN8, SZSHAN, SZDRQJ, SZTRDJ, SZPDDJ, SZOPDJ, SZADDJ, SZCNDJ, ",
        "SZPEFJ, SZPPDJ, SZPSDJ, SZDSVJ, SZDGL, SZPN, SZVR01, SZVR02, SZITM, SZLITM, ",
        "SZAITM, SZCITM, SZLOCN, SZLOTN, SZFRGD, SZTHGD, SZFRMP, SZTHRP, SZDSC1, SZDSC2, ",
        "SZLNTY, SZNXTR, SZLTTR, SZRLIT, SZPDS1, SZPDS2, SZPDS3, SZPDS4, SZPDS5, SZPDP1, ",
        "SZPDP2, SZPDP3, SZPDP4, SZPDP5, SZUOM, SZUORG, SZUCHG, SZUOPN, SZUREC, SZCREC, ",
        "SZURLV, SZOTQY, SZPRRC, SZAEXP, SZACHG, SZAOPN, SZAREC, SZARLV, SZFTN1, SZTRLV, ",
        "SZPROV, SZAMC3, SZECST, SZCSTO, SZCSMP, SZINMG, SZASN, SZPRGR, SZCLVL, SZCATN, ",
        "SZDSPR, SZPTC, SZTX, SZEXR1, SZTXA1, SZATXT, SZCNID, SZCDCD, SZNTR, SZFRTH, ",
        "SZFRTC, SZZON, SZFRAT, SZRATT, SZANBY, SZANCR, SZMOT, SZCOT, SZSHCM, SZSHCN, ",
        "SZUOM1, SZPQOR, SZUOM2, SZSQOR, SZUOM3, SZITWT, SZWTUM, SZITVL, SZVLUM, SZGLC, ",
        "SZCTRY, SZFY, SZSTTS, SZRCD, SZFUF1, SZFUF2, SZGRWT, SZGWUM, SZLT, SZANI, SZAID, ",
        "SZOMCU, SZOBJ, SZSUB, SZSBLT, SZSBL, SZASID, SZCCMP, SZTAG, SZWR01, SZPL, SZELEV, ",
        "SZR001, SZRTNR, SZLCOD, SZPURG, SZPROM, SZFNLP, SZAVCH, SZPRPY, SZUNCD, SZMATY, ",
        "SZRTGC, SZRCPF, SZARTG, SZCORD, SZCHDT, SZDOCC, SZCHLN, SZCRCD, SZCRR, SZFRRC, ",
        "SZFEA, SZFUC, SZFEC, SZFCHG, SZFAP, SZFREC, SZURET, SZUDMG, SZDGCD, SZUREJ, ",
        "SZRJCD, SZUIQ1, SZU1CD, SZUIQ2, SZU2CD, SZUIQ3, SZU3CD, SZURCD, SZURDT, SZURAT, ",
        "SZURAB, SZURRF, SZTORG, SZUSER, SZPID, SZJOBN, SZUPMJ, SZTDAY, SZBALU, SZMERL, ",
        "SZKTLN, SZCPNT, SZBCRC, SZSHPN, SZPS01, SZPS02, SZPS03, SZPS04, SZPS05, SZPS06, ",
        "SZPS07, SZPS08, SZPS09, SZPS10, SZCRMD, SZCHID, SZCHMJ, SZCHT, SZCTAM, SZFTRL, ",
        "SZMACT, SZDCD, SZDCP, SZNDTP, SZPXDD, SZPXDM, SZDRQT, SZRSHT, SZPLT, SZPAK, ",
        "SZSCCN, SZSCCQ, SZSCUM, SZUPCN, SZUPQT, SZUPUM, SZVRMK, SZLOT1, SZLOT2, SZRLOT, ",
        "SZLOTS, SZMMEJ, SZLDSC, SZDUAL, SZXDCK, SZLOTC, SZVR03, SZLDNM, SZMKFR, SZBTAN, ",
        "SZCTSN, SZGAN8, SZGSHAN, SZGCARS, SZGMKFR, SZGBTAN, SZORIG",
        "from F47072",
        "where SZEDOC = #{szedoc,jdbcType=DECIMAL}",
          "and SZEDCT = #{szedct,jdbcType=NCHAR}",
          "and SZEKCO = #{szekco,jdbcType=NCHAR}",
          "and SZEDLN = #{szedln,jdbcType=DECIMAL}"
    })
    @Results({
        @Result(column="SZEDOC", property="szedoc", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="SZEDCT", property="szedct", jdbcType=JdbcType.NCHAR, id=true),
        @Result(column="SZEKCO", property="szekco", jdbcType=JdbcType.NCHAR, id=true),
        @Result(column="SZEDLN", property="szedln", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="SZEDTY", property="szedty", jdbcType=JdbcType.NCHAR),
        @Result(column="SZEDSQ", property="szedsq", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZEDST", property="szedst", jdbcType=JdbcType.NCHAR),
        @Result(column="SZEDFT", property="szedft", jdbcType=JdbcType.NCHAR),
        @Result(column="SZEDDT", property="szeddt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZEDER", property="szeder", jdbcType=JdbcType.NCHAR),
        @Result(column="SZEDDL", property="szeddl", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZEDSP", property="szedsp", jdbcType=JdbcType.NCHAR),
        @Result(column="SZEDBT", property="szedbt", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPNID", property="szpnid", jdbcType=JdbcType.NCHAR),
        @Result(column="SZLSTS", property="szlsts", jdbcType=JdbcType.NCHAR),
        @Result(column="SZKCOO", property="szkcoo", jdbcType=JdbcType.NCHAR),
        @Result(column="SZDOCO", property="szdoco", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZDCTO", property="szdcto", jdbcType=JdbcType.NCHAR),
        @Result(column="SZSFXO", property="szsfxo", jdbcType=JdbcType.NCHAR),
        @Result(column="SZLNID", property="szlnid", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZMCU", property="szmcu", jdbcType=JdbcType.NCHAR),
        @Result(column="SZCO", property="szco", jdbcType=JdbcType.NCHAR),
        @Result(column="SZOKCO", property="szokco", jdbcType=JdbcType.NCHAR),
        @Result(column="SZOORN", property="szoorn", jdbcType=JdbcType.NCHAR),
        @Result(column="SZOCTO", property="szocto", jdbcType=JdbcType.NCHAR),
        @Result(column="SZOGNO", property="szogno", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZRKCO", property="szrkco", jdbcType=JdbcType.NCHAR),
        @Result(column="SZRORN", property="szrorn", jdbcType=JdbcType.NCHAR),
        @Result(column="SZRCTO", property="szrcto", jdbcType=JdbcType.NCHAR),
        @Result(column="SZRLLN", property="szrlln", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZDMCT", property="szdmct", jdbcType=JdbcType.NCHAR),
        @Result(column="SZDMCS", property="szdmcs", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZAN8", property="szan8", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZSHAN", property="szshan", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZDRQJ", property="szdrqj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZTRDJ", property="sztrdj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZPDDJ", property="szpddj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZOPDJ", property="szopdj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZADDJ", property="szaddj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZCNDJ", property="szcndj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZPEFJ", property="szpefj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZPPDJ", property="szppdj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZPSDJ", property="szpsdj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZDSVJ", property="szdsvj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZDGL", property="szdgl", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZPN", property="szpn", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZVR01", property="szvr01", jdbcType=JdbcType.NCHAR),
        @Result(column="SZVR02", property="szvr02", jdbcType=JdbcType.NCHAR),
        @Result(column="SZITM", property="szitm", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZLITM", property="szlitm", jdbcType=JdbcType.NCHAR),
        @Result(column="SZAITM", property="szaitm", jdbcType=JdbcType.NCHAR),
        @Result(column="SZCITM", property="szcitm", jdbcType=JdbcType.NCHAR),
        @Result(column="SZLOCN", property="szlocn", jdbcType=JdbcType.NCHAR),
        @Result(column="SZLOTN", property="szlotn", jdbcType=JdbcType.NCHAR),
        @Result(column="SZFRGD", property="szfrgd", jdbcType=JdbcType.NCHAR),
        @Result(column="SZTHGD", property="szthgd", jdbcType=JdbcType.NCHAR),
        @Result(column="SZFRMP", property="szfrmp", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZTHRP", property="szthrp", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZDSC1", property="szdsc1", jdbcType=JdbcType.NCHAR),
        @Result(column="SZDSC2", property="szdsc2", jdbcType=JdbcType.NCHAR),
        @Result(column="SZLNTY", property="szlnty", jdbcType=JdbcType.NCHAR),
        @Result(column="SZNXTR", property="sznxtr", jdbcType=JdbcType.NCHAR),
        @Result(column="SZLTTR", property="szlttr", jdbcType=JdbcType.NCHAR),
        @Result(column="SZRLIT", property="szrlit", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPDS1", property="szpds1", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPDS2", property="szpds2", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPDS3", property="szpds3", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPDS4", property="szpds4", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPDS5", property="szpds5", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPDP1", property="szpdp1", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPDP2", property="szpdp2", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPDP3", property="szpdp3", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPDP4", property="szpdp4", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPDP5", property="szpdp5", jdbcType=JdbcType.NCHAR),
        @Result(column="SZUOM", property="szuom", jdbcType=JdbcType.NCHAR),
        @Result(column="SZUORG", property="szuorg", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZUCHG", property="szuchg", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZUOPN", property="szuopn", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZUREC", property="szurec", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZCREC", property="szcrec", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZURLV", property="szurlv", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZOTQY", property="szotqy", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPRRC", property="szprrc", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZAEXP", property="szaexp", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZACHG", property="szachg", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZAOPN", property="szaopn", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZAREC", property="szarec", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZARLV", property="szarlv", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZFTN1", property="szftn1", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZTRLV", property="sztrlv", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZPROV", property="szprov", jdbcType=JdbcType.NCHAR),
        @Result(column="SZAMC3", property="szamc3", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZECST", property="szecst", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZCSTO", property="szcsto", jdbcType=JdbcType.NCHAR),
        @Result(column="SZCSMP", property="szcsmp", jdbcType=JdbcType.NCHAR),
        @Result(column="SZINMG", property="szinmg", jdbcType=JdbcType.NCHAR),
        @Result(column="SZASN", property="szasn", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPRGR", property="szprgr", jdbcType=JdbcType.NCHAR),
        @Result(column="SZCLVL", property="szclvl", jdbcType=JdbcType.NCHAR),
        @Result(column="SZCATN", property="szcatn", jdbcType=JdbcType.NCHAR),
        @Result(column="SZDSPR", property="szdspr", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZPTC", property="szptc", jdbcType=JdbcType.NCHAR),
        @Result(column="SZTX", property="sztx", jdbcType=JdbcType.NCHAR),
        @Result(column="SZEXR1", property="szexr1", jdbcType=JdbcType.NCHAR),
        @Result(column="SZTXA1", property="sztxa1", jdbcType=JdbcType.NCHAR),
        @Result(column="SZATXT", property="szatxt", jdbcType=JdbcType.NCHAR),
        @Result(column="SZCNID", property="szcnid", jdbcType=JdbcType.NCHAR),
        @Result(column="SZCDCD", property="szcdcd", jdbcType=JdbcType.NCHAR),
        @Result(column="SZNTR", property="szntr", jdbcType=JdbcType.NCHAR),
        @Result(column="SZFRTH", property="szfrth", jdbcType=JdbcType.NCHAR),
        @Result(column="SZFRTC", property="szfrtc", jdbcType=JdbcType.NCHAR),
        @Result(column="SZZON", property="szzon", jdbcType=JdbcType.NCHAR),
        @Result(column="SZFRAT", property="szfrat", jdbcType=JdbcType.NCHAR),
        @Result(column="SZRATT", property="szratt", jdbcType=JdbcType.NCHAR),
        @Result(column="SZANBY", property="szanby", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZANCR", property="szancr", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZMOT", property="szmot", jdbcType=JdbcType.NCHAR),
        @Result(column="SZCOT", property="szcot", jdbcType=JdbcType.NCHAR),
        @Result(column="SZSHCM", property="szshcm", jdbcType=JdbcType.NCHAR),
        @Result(column="SZSHCN", property="szshcn", jdbcType=JdbcType.NCHAR),
        @Result(column="SZUOM1", property="szuom1", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPQOR", property="szpqor", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZUOM2", property="szuom2", jdbcType=JdbcType.NCHAR),
        @Result(column="SZSQOR", property="szsqor", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZUOM3", property="szuom3", jdbcType=JdbcType.NCHAR),
        @Result(column="SZITWT", property="szitwt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZWTUM", property="szwtum", jdbcType=JdbcType.NCHAR),
        @Result(column="SZITVL", property="szitvl", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZVLUM", property="szvlum", jdbcType=JdbcType.NCHAR),
        @Result(column="SZGLC", property="szglc", jdbcType=JdbcType.NCHAR),
        @Result(column="SZCTRY", property="szctry", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZFY", property="szfy", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZSTTS", property="szstts", jdbcType=JdbcType.NCHAR),
        @Result(column="SZRCD", property="szrcd", jdbcType=JdbcType.NCHAR),
        @Result(column="SZFUF1", property="szfuf1", jdbcType=JdbcType.NCHAR),
        @Result(column="SZFUF2", property="szfuf2", jdbcType=JdbcType.NCHAR),
        @Result(column="SZGRWT", property="szgrwt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZGWUM", property="szgwum", jdbcType=JdbcType.NCHAR),
        @Result(column="SZLT", property="szlt", jdbcType=JdbcType.NCHAR),
        @Result(column="SZANI", property="szani", jdbcType=JdbcType.NCHAR),
        @Result(column="SZAID", property="szaid", jdbcType=JdbcType.NCHAR),
        @Result(column="SZOMCU", property="szomcu", jdbcType=JdbcType.NCHAR),
        @Result(column="SZOBJ", property="szobj", jdbcType=JdbcType.NCHAR),
        @Result(column="SZSUB", property="szsub", jdbcType=JdbcType.NCHAR),
        @Result(column="SZSBLT", property="szsblt", jdbcType=JdbcType.NCHAR),
        @Result(column="SZSBL", property="szsbl", jdbcType=JdbcType.NCHAR),
        @Result(column="SZASID", property="szasid", jdbcType=JdbcType.NCHAR),
        @Result(column="SZCCMP", property="szccmp", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZTAG", property="sztag", jdbcType=JdbcType.NCHAR),
        @Result(column="SZWR01", property="szwr01", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPL", property="szpl", jdbcType=JdbcType.NCHAR),
        @Result(column="SZELEV", property="szelev", jdbcType=JdbcType.NCHAR),
        @Result(column="SZR001", property="szr001", jdbcType=JdbcType.NCHAR),
        @Result(column="SZRTNR", property="szrtnr", jdbcType=JdbcType.NCHAR),
        @Result(column="SZLCOD", property="szlcod", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPURG", property="szpurg", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPROM", property="szprom", jdbcType=JdbcType.NCHAR),
        @Result(column="SZFNLP", property="szfnlp", jdbcType=JdbcType.NCHAR),
        @Result(column="SZAVCH", property="szavch", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPRPY", property="szprpy", jdbcType=JdbcType.NCHAR),
        @Result(column="SZUNCD", property="szuncd", jdbcType=JdbcType.NCHAR),
        @Result(column="SZMATY", property="szmaty", jdbcType=JdbcType.NCHAR),
        @Result(column="SZRTGC", property="szrtgc", jdbcType=JdbcType.NCHAR),
        @Result(column="SZRCPF", property="szrcpf", jdbcType=JdbcType.NCHAR),
        @Result(column="SZARTG", property="szartg", jdbcType=JdbcType.NCHAR),
        @Result(column="SZCORD", property="szcord", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZCHDT", property="szchdt", jdbcType=JdbcType.NCHAR),
        @Result(column="SZDOCC", property="szdocc", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZCHLN", property="szchln", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZCRCD", property="szcrcd", jdbcType=JdbcType.NCHAR),
        @Result(column="SZCRR", property="szcrr", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZFRRC", property="szfrrc", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZFEA", property="szfea", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZFUC", property="szfuc", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZFEC", property="szfec", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZFCHG", property="szfchg", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZFAP", property="szfap", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZFREC", property="szfrec", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZURET", property="szuret", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZUDMG", property="szudmg", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZDGCD", property="szdgcd", jdbcType=JdbcType.NCHAR),
        @Result(column="SZUREJ", property="szurej", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZRJCD", property="szrjcd", jdbcType=JdbcType.NCHAR),
        @Result(column="SZUIQ1", property="szuiq1", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZU1CD", property="szu1cd", jdbcType=JdbcType.NCHAR),
        @Result(column="SZUIQ2", property="szuiq2", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZU2CD", property="szu2cd", jdbcType=JdbcType.NCHAR),
        @Result(column="SZUIQ3", property="szuiq3", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZU3CD", property="szu3cd", jdbcType=JdbcType.NCHAR),
        @Result(column="SZURCD", property="szurcd", jdbcType=JdbcType.NCHAR),
        @Result(column="SZURDT", property="szurdt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZURAT", property="szurat", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZURAB", property="szurab", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZURRF", property="szurrf", jdbcType=JdbcType.NCHAR),
        @Result(column="SZTORG", property="sztorg", jdbcType=JdbcType.NCHAR),
        @Result(column="SZUSER", property="szuser", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPID", property="szpid", jdbcType=JdbcType.NCHAR),
        @Result(column="SZJOBN", property="szjobn", jdbcType=JdbcType.NCHAR),
        @Result(column="SZUPMJ", property="szupmj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZTDAY", property="sztday", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZBALU", property="szbalu", jdbcType=JdbcType.NCHAR),
        @Result(column="SZMERL", property="szmerl", jdbcType=JdbcType.NCHAR),
        @Result(column="SZKTLN", property="szktln", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZCPNT", property="szcpnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZBCRC", property="szbcrc", jdbcType=JdbcType.NCHAR),
        @Result(column="SZSHPN", property="szshpn", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZPS01", property="szps01", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPS02", property="szps02", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPS03", property="szps03", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPS04", property="szps04", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPS05", property="szps05", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPS06", property="szps06", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPS07", property="szps07", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPS08", property="szps08", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPS09", property="szps09", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPS10", property="szps10", jdbcType=JdbcType.NCHAR),
        @Result(column="SZCRMD", property="szcrmd", jdbcType=JdbcType.NCHAR),
        @Result(column="SZCHID", property="szchid", jdbcType=JdbcType.NCHAR),
        @Result(column="SZCHMJ", property="szchmj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZCHT", property="szcht", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZCTAM", property="szctam", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZFTRL", property="szftrl", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZMACT", property="szmact", jdbcType=JdbcType.NCHAR),
        @Result(column="SZDCD", property="szdcd", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZDCP", property="szdcp", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZNDTP", property="szndtp", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZPXDD", property="szpxdd", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZPXDM", property="szpxdm", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZDRQT", property="szdrqt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZRSHT", property="szrsht", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZPLT", property="szplt", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPAK", property="szpak", jdbcType=JdbcType.NCHAR),
        @Result(column="SZSCCN", property="szsccn", jdbcType=JdbcType.NCHAR),
        @Result(column="SZSCCQ", property="szsccq", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZSCUM", property="szscum", jdbcType=JdbcType.NCHAR),
        @Result(column="SZUPCN", property="szupcn", jdbcType=JdbcType.NCHAR),
        @Result(column="SZUPQT", property="szupqt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZUPUM", property="szupum", jdbcType=JdbcType.NCHAR),
        @Result(column="SZVRMK", property="szvrmk", jdbcType=JdbcType.NCHAR),
        @Result(column="SZLOT1", property="szlot1", jdbcType=JdbcType.NCHAR),
        @Result(column="SZLOT2", property="szlot2", jdbcType=JdbcType.NCHAR),
        @Result(column="SZRLOT", property="szrlot", jdbcType=JdbcType.NCHAR),
        @Result(column="SZLOTS", property="szlots", jdbcType=JdbcType.NCHAR),
        @Result(column="SZMMEJ", property="szmmej", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZLDSC", property="szldsc", jdbcType=JdbcType.NCHAR),
        @Result(column="SZDUAL", property="szdual", jdbcType=JdbcType.NCHAR),
        @Result(column="SZXDCK", property="szxdck", jdbcType=JdbcType.NCHAR),
        @Result(column="SZLOTC", property="szlotc", jdbcType=JdbcType.NCHAR),
        @Result(column="SZVR03", property="szvr03", jdbcType=JdbcType.NCHAR),
        @Result(column="SZLDNM", property="szldnm", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZMKFR", property="szmkfr", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZBTAN", property="szbtan", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZCTSN", property="szctsn", jdbcType=JdbcType.NCHAR),
        @Result(column="SZGAN8", property="szgan8", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZGSHAN", property="szgshan", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZGCARS", property="szgcars", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZGMKFR", property="szgmkfr", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZGBTAN", property="szgbtan", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZORIG", property="szorig", jdbcType=JdbcType.NCHAR)
    })
    F47072 selectByPrimaryKey(@Param("szedoc") BigDecimal szedoc, @Param("szedct") String szedct, @Param("szekco") String szekco, @Param("szedln") BigDecimal szedln);

    @Select({
        "select",
        "SZEDOC, SZEDCT, SZEKCO, SZEDLN, SZEDTY, SZEDSQ, SZEDST, SZEDFT, SZEDDT, SZEDER, ",
        "SZEDDL, SZEDSP, SZEDBT, SZPNID, SZLSTS, SZKCOO, SZDOCO, SZDCTO, SZSFXO, SZLNID, ",
        "SZMCU, SZCO, SZOKCO, SZOORN, SZOCTO, SZOGNO, SZRKCO, SZRORN, SZRCTO, SZRLLN, ",
        "SZDMCT, SZDMCS, SZAN8, SZSHAN, SZDRQJ, SZTRDJ, SZPDDJ, SZOPDJ, SZADDJ, SZCNDJ, ",
        "SZPEFJ, SZPPDJ, SZPSDJ, SZDSVJ, SZDGL, SZPN, SZVR01, SZVR02, SZITM, SZLITM, ",
        "SZAITM, SZCITM, SZLOCN, SZLOTN, SZFRGD, SZTHGD, SZFRMP, SZTHRP, SZDSC1, SZDSC2, ",
        "SZLNTY, SZNXTR, SZLTTR, SZRLIT, SZPDS1, SZPDS2, SZPDS3, SZPDS4, SZPDS5, SZPDP1, ",
        "SZPDP2, SZPDP3, SZPDP4, SZPDP5, SZUOM, SZUORG, SZUCHG, SZUOPN, SZUREC, SZCREC, ",
        "SZURLV, SZOTQY, SZPRRC, SZAEXP, SZACHG, SZAOPN, SZAREC, SZARLV, SZFTN1, SZTRLV, ",
        "SZPROV, SZAMC3, SZECST, SZCSTO, SZCSMP, SZINMG, SZASN, SZPRGR, SZCLVL, SZCATN, ",
        "SZDSPR, SZPTC, SZTX, SZEXR1, SZTXA1, SZATXT, SZCNID, SZCDCD, SZNTR, SZFRTH, ",
        "SZFRTC, SZZON, SZFRAT, SZRATT, SZANBY, SZANCR, SZMOT, SZCOT, SZSHCM, SZSHCN, ",
        "SZUOM1, SZPQOR, SZUOM2, SZSQOR, SZUOM3, SZITWT, SZWTUM, SZITVL, SZVLUM, SZGLC, ",
        "SZCTRY, SZFY, SZSTTS, SZRCD, SZFUF1, SZFUF2, SZGRWT, SZGWUM, SZLT, SZANI, SZAID, ",
        "SZOMCU, SZOBJ, SZSUB, SZSBLT, SZSBL, SZASID, SZCCMP, SZTAG, SZWR01, SZPL, SZELEV, ",
        "SZR001, SZRTNR, SZLCOD, SZPURG, SZPROM, SZFNLP, SZAVCH, SZPRPY, SZUNCD, SZMATY, ",
        "SZRTGC, SZRCPF, SZARTG, SZCORD, SZCHDT, SZDOCC, SZCHLN, SZCRCD, SZCRR, SZFRRC, ",
        "SZFEA, SZFUC, SZFEC, SZFCHG, SZFAP, SZFREC, SZURET, SZUDMG, SZDGCD, SZUREJ, ",
        "SZRJCD, SZUIQ1, SZU1CD, SZUIQ2, SZU2CD, SZUIQ3, SZU3CD, SZURCD, SZURDT, SZURAT, ",
        "SZURAB, SZURRF, SZTORG, SZUSER, SZPID, SZJOBN, SZUPMJ, SZTDAY, SZBALU, SZMERL, ",
        "SZKTLN, SZCPNT, SZBCRC, SZSHPN, SZPS01, SZPS02, SZPS03, SZPS04, SZPS05, SZPS06, ",
        "SZPS07, SZPS08, SZPS09, SZPS10, SZCRMD, SZCHID, SZCHMJ, SZCHT, SZCTAM, SZFTRL, ",
        "SZMACT, SZDCD, SZDCP, SZNDTP, SZPXDD, SZPXDM, SZDRQT, SZRSHT, SZPLT, SZPAK, ",
        "SZSCCN, SZSCCQ, SZSCUM, SZUPCN, SZUPQT, SZUPUM, SZVRMK, SZLOT1, SZLOT2, SZRLOT, ",
        "SZLOTS, SZMMEJ, SZLDSC, SZDUAL, SZXDCK, SZLOTC, SZVR03, SZLDNM, SZMKFR, SZBTAN, ",
        "SZCTSN, SZGAN8, SZGSHAN, SZGCARS, SZGMKFR, SZGBTAN, SZORIG",
        "from F47072"
    })
    @Results({
        @Result(column="SZEDOC", property="szedoc", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="SZEDCT", property="szedct", jdbcType=JdbcType.NCHAR, id=true),
        @Result(column="SZEKCO", property="szekco", jdbcType=JdbcType.NCHAR, id=true),
        @Result(column="SZEDLN", property="szedln", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="SZEDTY", property="szedty", jdbcType=JdbcType.NCHAR),
        @Result(column="SZEDSQ", property="szedsq", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZEDST", property="szedst", jdbcType=JdbcType.NCHAR),
        @Result(column="SZEDFT", property="szedft", jdbcType=JdbcType.NCHAR),
        @Result(column="SZEDDT", property="szeddt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZEDER", property="szeder", jdbcType=JdbcType.NCHAR),
        @Result(column="SZEDDL", property="szeddl", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZEDSP", property="szedsp", jdbcType=JdbcType.NCHAR),
        @Result(column="SZEDBT", property="szedbt", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPNID", property="szpnid", jdbcType=JdbcType.NCHAR),
        @Result(column="SZLSTS", property="szlsts", jdbcType=JdbcType.NCHAR),
        @Result(column="SZKCOO", property="szkcoo", jdbcType=JdbcType.NCHAR),
        @Result(column="SZDOCO", property="szdoco", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZDCTO", property="szdcto", jdbcType=JdbcType.NCHAR),
        @Result(column="SZSFXO", property="szsfxo", jdbcType=JdbcType.NCHAR),
        @Result(column="SZLNID", property="szlnid", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZMCU", property="szmcu", jdbcType=JdbcType.NCHAR),
        @Result(column="SZCO", property="szco", jdbcType=JdbcType.NCHAR),
        @Result(column="SZOKCO", property="szokco", jdbcType=JdbcType.NCHAR),
        @Result(column="SZOORN", property="szoorn", jdbcType=JdbcType.NCHAR),
        @Result(column="SZOCTO", property="szocto", jdbcType=JdbcType.NCHAR),
        @Result(column="SZOGNO", property="szogno", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZRKCO", property="szrkco", jdbcType=JdbcType.NCHAR),
        @Result(column="SZRORN", property="szrorn", jdbcType=JdbcType.NCHAR),
        @Result(column="SZRCTO", property="szrcto", jdbcType=JdbcType.NCHAR),
        @Result(column="SZRLLN", property="szrlln", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZDMCT", property="szdmct", jdbcType=JdbcType.NCHAR),
        @Result(column="SZDMCS", property="szdmcs", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZAN8", property="szan8", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZSHAN", property="szshan", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZDRQJ", property="szdrqj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZTRDJ", property="sztrdj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZPDDJ", property="szpddj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZOPDJ", property="szopdj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZADDJ", property="szaddj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZCNDJ", property="szcndj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZPEFJ", property="szpefj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZPPDJ", property="szppdj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZPSDJ", property="szpsdj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZDSVJ", property="szdsvj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZDGL", property="szdgl", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZPN", property="szpn", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZVR01", property="szvr01", jdbcType=JdbcType.NCHAR),
        @Result(column="SZVR02", property="szvr02", jdbcType=JdbcType.NCHAR),
        @Result(column="SZITM", property="szitm", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZLITM", property="szlitm", jdbcType=JdbcType.NCHAR),
        @Result(column="SZAITM", property="szaitm", jdbcType=JdbcType.NCHAR),
        @Result(column="SZCITM", property="szcitm", jdbcType=JdbcType.NCHAR),
        @Result(column="SZLOCN", property="szlocn", jdbcType=JdbcType.NCHAR),
        @Result(column="SZLOTN", property="szlotn", jdbcType=JdbcType.NCHAR),
        @Result(column="SZFRGD", property="szfrgd", jdbcType=JdbcType.NCHAR),
        @Result(column="SZTHGD", property="szthgd", jdbcType=JdbcType.NCHAR),
        @Result(column="SZFRMP", property="szfrmp", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZTHRP", property="szthrp", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZDSC1", property="szdsc1", jdbcType=JdbcType.NCHAR),
        @Result(column="SZDSC2", property="szdsc2", jdbcType=JdbcType.NCHAR),
        @Result(column="SZLNTY", property="szlnty", jdbcType=JdbcType.NCHAR),
        @Result(column="SZNXTR", property="sznxtr", jdbcType=JdbcType.NCHAR),
        @Result(column="SZLTTR", property="szlttr", jdbcType=JdbcType.NCHAR),
        @Result(column="SZRLIT", property="szrlit", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPDS1", property="szpds1", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPDS2", property="szpds2", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPDS3", property="szpds3", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPDS4", property="szpds4", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPDS5", property="szpds5", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPDP1", property="szpdp1", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPDP2", property="szpdp2", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPDP3", property="szpdp3", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPDP4", property="szpdp4", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPDP5", property="szpdp5", jdbcType=JdbcType.NCHAR),
        @Result(column="SZUOM", property="szuom", jdbcType=JdbcType.NCHAR),
        @Result(column="SZUORG", property="szuorg", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZUCHG", property="szuchg", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZUOPN", property="szuopn", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZUREC", property="szurec", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZCREC", property="szcrec", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZURLV", property="szurlv", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZOTQY", property="szotqy", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPRRC", property="szprrc", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZAEXP", property="szaexp", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZACHG", property="szachg", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZAOPN", property="szaopn", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZAREC", property="szarec", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZARLV", property="szarlv", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZFTN1", property="szftn1", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZTRLV", property="sztrlv", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZPROV", property="szprov", jdbcType=JdbcType.NCHAR),
        @Result(column="SZAMC3", property="szamc3", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZECST", property="szecst", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZCSTO", property="szcsto", jdbcType=JdbcType.NCHAR),
        @Result(column="SZCSMP", property="szcsmp", jdbcType=JdbcType.NCHAR),
        @Result(column="SZINMG", property="szinmg", jdbcType=JdbcType.NCHAR),
        @Result(column="SZASN", property="szasn", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPRGR", property="szprgr", jdbcType=JdbcType.NCHAR),
        @Result(column="SZCLVL", property="szclvl", jdbcType=JdbcType.NCHAR),
        @Result(column="SZCATN", property="szcatn", jdbcType=JdbcType.NCHAR),
        @Result(column="SZDSPR", property="szdspr", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZPTC", property="szptc", jdbcType=JdbcType.NCHAR),
        @Result(column="SZTX", property="sztx", jdbcType=JdbcType.NCHAR),
        @Result(column="SZEXR1", property="szexr1", jdbcType=JdbcType.NCHAR),
        @Result(column="SZTXA1", property="sztxa1", jdbcType=JdbcType.NCHAR),
        @Result(column="SZATXT", property="szatxt", jdbcType=JdbcType.NCHAR),
        @Result(column="SZCNID", property="szcnid", jdbcType=JdbcType.NCHAR),
        @Result(column="SZCDCD", property="szcdcd", jdbcType=JdbcType.NCHAR),
        @Result(column="SZNTR", property="szntr", jdbcType=JdbcType.NCHAR),
        @Result(column="SZFRTH", property="szfrth", jdbcType=JdbcType.NCHAR),
        @Result(column="SZFRTC", property="szfrtc", jdbcType=JdbcType.NCHAR),
        @Result(column="SZZON", property="szzon", jdbcType=JdbcType.NCHAR),
        @Result(column="SZFRAT", property="szfrat", jdbcType=JdbcType.NCHAR),
        @Result(column="SZRATT", property="szratt", jdbcType=JdbcType.NCHAR),
        @Result(column="SZANBY", property="szanby", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZANCR", property="szancr", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZMOT", property="szmot", jdbcType=JdbcType.NCHAR),
        @Result(column="SZCOT", property="szcot", jdbcType=JdbcType.NCHAR),
        @Result(column="SZSHCM", property="szshcm", jdbcType=JdbcType.NCHAR),
        @Result(column="SZSHCN", property="szshcn", jdbcType=JdbcType.NCHAR),
        @Result(column="SZUOM1", property="szuom1", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPQOR", property="szpqor", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZUOM2", property="szuom2", jdbcType=JdbcType.NCHAR),
        @Result(column="SZSQOR", property="szsqor", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZUOM3", property="szuom3", jdbcType=JdbcType.NCHAR),
        @Result(column="SZITWT", property="szitwt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZWTUM", property="szwtum", jdbcType=JdbcType.NCHAR),
        @Result(column="SZITVL", property="szitvl", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZVLUM", property="szvlum", jdbcType=JdbcType.NCHAR),
        @Result(column="SZGLC", property="szglc", jdbcType=JdbcType.NCHAR),
        @Result(column="SZCTRY", property="szctry", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZFY", property="szfy", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZSTTS", property="szstts", jdbcType=JdbcType.NCHAR),
        @Result(column="SZRCD", property="szrcd", jdbcType=JdbcType.NCHAR),
        @Result(column="SZFUF1", property="szfuf1", jdbcType=JdbcType.NCHAR),
        @Result(column="SZFUF2", property="szfuf2", jdbcType=JdbcType.NCHAR),
        @Result(column="SZGRWT", property="szgrwt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZGWUM", property="szgwum", jdbcType=JdbcType.NCHAR),
        @Result(column="SZLT", property="szlt", jdbcType=JdbcType.NCHAR),
        @Result(column="SZANI", property="szani", jdbcType=JdbcType.NCHAR),
        @Result(column="SZAID", property="szaid", jdbcType=JdbcType.NCHAR),
        @Result(column="SZOMCU", property="szomcu", jdbcType=JdbcType.NCHAR),
        @Result(column="SZOBJ", property="szobj", jdbcType=JdbcType.NCHAR),
        @Result(column="SZSUB", property="szsub", jdbcType=JdbcType.NCHAR),
        @Result(column="SZSBLT", property="szsblt", jdbcType=JdbcType.NCHAR),
        @Result(column="SZSBL", property="szsbl", jdbcType=JdbcType.NCHAR),
        @Result(column="SZASID", property="szasid", jdbcType=JdbcType.NCHAR),
        @Result(column="SZCCMP", property="szccmp", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZTAG", property="sztag", jdbcType=JdbcType.NCHAR),
        @Result(column="SZWR01", property="szwr01", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPL", property="szpl", jdbcType=JdbcType.NCHAR),
        @Result(column="SZELEV", property="szelev", jdbcType=JdbcType.NCHAR),
        @Result(column="SZR001", property="szr001", jdbcType=JdbcType.NCHAR),
        @Result(column="SZRTNR", property="szrtnr", jdbcType=JdbcType.NCHAR),
        @Result(column="SZLCOD", property="szlcod", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPURG", property="szpurg", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPROM", property="szprom", jdbcType=JdbcType.NCHAR),
        @Result(column="SZFNLP", property="szfnlp", jdbcType=JdbcType.NCHAR),
        @Result(column="SZAVCH", property="szavch", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPRPY", property="szprpy", jdbcType=JdbcType.NCHAR),
        @Result(column="SZUNCD", property="szuncd", jdbcType=JdbcType.NCHAR),
        @Result(column="SZMATY", property="szmaty", jdbcType=JdbcType.NCHAR),
        @Result(column="SZRTGC", property="szrtgc", jdbcType=JdbcType.NCHAR),
        @Result(column="SZRCPF", property="szrcpf", jdbcType=JdbcType.NCHAR),
        @Result(column="SZARTG", property="szartg", jdbcType=JdbcType.NCHAR),
        @Result(column="SZCORD", property="szcord", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZCHDT", property="szchdt", jdbcType=JdbcType.NCHAR),
        @Result(column="SZDOCC", property="szdocc", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZCHLN", property="szchln", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZCRCD", property="szcrcd", jdbcType=JdbcType.NCHAR),
        @Result(column="SZCRR", property="szcrr", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZFRRC", property="szfrrc", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZFEA", property="szfea", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZFUC", property="szfuc", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZFEC", property="szfec", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZFCHG", property="szfchg", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZFAP", property="szfap", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZFREC", property="szfrec", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZURET", property="szuret", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZUDMG", property="szudmg", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZDGCD", property="szdgcd", jdbcType=JdbcType.NCHAR),
        @Result(column="SZUREJ", property="szurej", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZRJCD", property="szrjcd", jdbcType=JdbcType.NCHAR),
        @Result(column="SZUIQ1", property="szuiq1", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZU1CD", property="szu1cd", jdbcType=JdbcType.NCHAR),
        @Result(column="SZUIQ2", property="szuiq2", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZU2CD", property="szu2cd", jdbcType=JdbcType.NCHAR),
        @Result(column="SZUIQ3", property="szuiq3", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZU3CD", property="szu3cd", jdbcType=JdbcType.NCHAR),
        @Result(column="SZURCD", property="szurcd", jdbcType=JdbcType.NCHAR),
        @Result(column="SZURDT", property="szurdt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZURAT", property="szurat", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZURAB", property="szurab", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZURRF", property="szurrf", jdbcType=JdbcType.NCHAR),
        @Result(column="SZTORG", property="sztorg", jdbcType=JdbcType.NCHAR),
        @Result(column="SZUSER", property="szuser", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPID", property="szpid", jdbcType=JdbcType.NCHAR),
        @Result(column="SZJOBN", property="szjobn", jdbcType=JdbcType.NCHAR),
        @Result(column="SZUPMJ", property="szupmj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZTDAY", property="sztday", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZBALU", property="szbalu", jdbcType=JdbcType.NCHAR),
        @Result(column="SZMERL", property="szmerl", jdbcType=JdbcType.NCHAR),
        @Result(column="SZKTLN", property="szktln", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZCPNT", property="szcpnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZBCRC", property="szbcrc", jdbcType=JdbcType.NCHAR),
        @Result(column="SZSHPN", property="szshpn", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZPS01", property="szps01", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPS02", property="szps02", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPS03", property="szps03", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPS04", property="szps04", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPS05", property="szps05", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPS06", property="szps06", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPS07", property="szps07", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPS08", property="szps08", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPS09", property="szps09", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPS10", property="szps10", jdbcType=JdbcType.NCHAR),
        @Result(column="SZCRMD", property="szcrmd", jdbcType=JdbcType.NCHAR),
        @Result(column="SZCHID", property="szchid", jdbcType=JdbcType.NCHAR),
        @Result(column="SZCHMJ", property="szchmj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZCHT", property="szcht", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZCTAM", property="szctam", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZFTRL", property="szftrl", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZMACT", property="szmact", jdbcType=JdbcType.NCHAR),
        @Result(column="SZDCD", property="szdcd", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZDCP", property="szdcp", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZNDTP", property="szndtp", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZPXDD", property="szpxdd", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZPXDM", property="szpxdm", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZDRQT", property="szdrqt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZRSHT", property="szrsht", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZPLT", property="szplt", jdbcType=JdbcType.NCHAR),
        @Result(column="SZPAK", property="szpak", jdbcType=JdbcType.NCHAR),
        @Result(column="SZSCCN", property="szsccn", jdbcType=JdbcType.NCHAR),
        @Result(column="SZSCCQ", property="szsccq", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZSCUM", property="szscum", jdbcType=JdbcType.NCHAR),
        @Result(column="SZUPCN", property="szupcn", jdbcType=JdbcType.NCHAR),
        @Result(column="SZUPQT", property="szupqt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZUPUM", property="szupum", jdbcType=JdbcType.NCHAR),
        @Result(column="SZVRMK", property="szvrmk", jdbcType=JdbcType.NCHAR),
        @Result(column="SZLOT1", property="szlot1", jdbcType=JdbcType.NCHAR),
        @Result(column="SZLOT2", property="szlot2", jdbcType=JdbcType.NCHAR),
        @Result(column="SZRLOT", property="szrlot", jdbcType=JdbcType.NCHAR),
        @Result(column="SZLOTS", property="szlots", jdbcType=JdbcType.NCHAR),
        @Result(column="SZMMEJ", property="szmmej", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZLDSC", property="szldsc", jdbcType=JdbcType.NCHAR),
        @Result(column="SZDUAL", property="szdual", jdbcType=JdbcType.NCHAR),
        @Result(column="SZXDCK", property="szxdck", jdbcType=JdbcType.NCHAR),
        @Result(column="SZLOTC", property="szlotc", jdbcType=JdbcType.NCHAR),
        @Result(column="SZVR03", property="szvr03", jdbcType=JdbcType.NCHAR),
        @Result(column="SZLDNM", property="szldnm", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZMKFR", property="szmkfr", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZBTAN", property="szbtan", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZCTSN", property="szctsn", jdbcType=JdbcType.NCHAR),
        @Result(column="SZGAN8", property="szgan8", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZGSHAN", property="szgshan", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZGCARS", property="szgcars", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZGMKFR", property="szgmkfr", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZGBTAN", property="szgbtan", jdbcType=JdbcType.DECIMAL),
        @Result(column="SZORIG", property="szorig", jdbcType=JdbcType.NCHAR)
    })
    List<F47072> selectAll();
}