package com.el.cfg.mapper;

import com.el.cfg.domain.F47071;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

public interface F47071Mapper {
    @Select({
        "select",
        "SYEDOC, SYEDCT, SYEKCO, SYEDTY, SYEDSQ, SYEDLN, SYEDST, SYEDFT, SYEDDT, SYEDER, ",
        "SYEDDL, SYEDSP, SYEDBT, SYPNID, SYTPUR, SYRATY, SYKCOO, SYDOCO, SYDCTO, SYSFXO, ",
        "SYMCU, SYOKCO, SYOORN, SYOCTO, SYRKCO, SYRORN, SYRCTO, SYAN8, SYSHAN, SYDRQJ, ",
        "SYTRDJ, SYPDDJ, SYOPDJ, SYADDJ, SYCNDJ, SYPEFJ, SYPPDJ, SYPSDJ, SYVR01, SYVR02, ",
        "SYDEL1, SYDEL2, SYRMK, SYDESC, SYINMG, SYASN, SYPRGP, SYPTC, SYEXR1, SYTXA1, ",
        "SYTXCT, SYATXT, SYHOLD, SYINVC, SYNTR, SYCNID, SYFRTH, SYZON, SYANBY, SYANCR, ",
        "SYMOT, SYCOT, SYRCD, SYFRTC, SYFUF1, SYFUF2, SYOTOT, SYPCRT, SYRTNR, SYWUMD, ",
        "SYVUMD, SYPURG, SYLGCT, SYPROM, SYMATY, SYOSTS, SYAVCH, SYPRPY, SYCRMD, SYPRP5, ",
        "SYARTG, SYCORD, SYCRRM, SYCRCD, SYCRR, SYLNGP, SYFAP, SYORBY, SYTKBY, SYURCD, ",
        "SYURDT, SYURAT, SYURAB, SYURRF, SYTORG, SYUSER, SYPID, SYJOBN, SYUPMJ, SYTDAY, ",
        "SYBCRC, SYDCD, SYDCP, SYNDTP, SYPXDD, SYPXDM, SYDRQT, SYRSHT, SYDVAN, SYVR03, ",
        "SYMKFR, SYGAN8, SYGSHAN, SYGCARS, SYGDVAN, SYGMKFR",
        "from F47071",
        "where SYEDOC = #{syedoc,jdbcType=DECIMAL}",
          "and SYEDCT = #{syedct,jdbcType=NCHAR}",
          "and SYEKCO = #{syekco,jdbcType=NCHAR}"
    })
    @Results({
        @Result(column="SYEDOC", property="syedoc", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="SYEDCT", property="syedct", jdbcType=JdbcType.NCHAR, id=true),
        @Result(column="SYEKCO", property="syekco", jdbcType=JdbcType.NCHAR, id=true),
        @Result(column="SYEDTY", property="syedty", jdbcType=JdbcType.NCHAR),
        @Result(column="SYEDSQ", property="syedsq", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYEDLN", property="syedln", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYEDST", property="syedst", jdbcType=JdbcType.NCHAR),
        @Result(column="SYEDFT", property="syedft", jdbcType=JdbcType.NCHAR),
        @Result(column="SYEDDT", property="syeddt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYEDER", property="syeder", jdbcType=JdbcType.NCHAR),
        @Result(column="SYEDDL", property="syeddl", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYEDSP", property="syedsp", jdbcType=JdbcType.NCHAR),
        @Result(column="SYEDBT", property="syedbt", jdbcType=JdbcType.NCHAR),
        @Result(column="SYPNID", property="sypnid", jdbcType=JdbcType.NCHAR),
        @Result(column="SYTPUR", property="sytpur", jdbcType=JdbcType.NCHAR),
        @Result(column="SYRATY", property="syraty", jdbcType=JdbcType.NCHAR),
        @Result(column="SYKCOO", property="sykcoo", jdbcType=JdbcType.NCHAR),
        @Result(column="SYDOCO", property="sydoco", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYDCTO", property="sydcto", jdbcType=JdbcType.NCHAR),
        @Result(column="SYSFXO", property="sysfxo", jdbcType=JdbcType.NCHAR),
        @Result(column="SYMCU", property="symcu", jdbcType=JdbcType.NCHAR),
        @Result(column="SYOKCO", property="syokco", jdbcType=JdbcType.NCHAR),
        @Result(column="SYOORN", property="syoorn", jdbcType=JdbcType.NCHAR),
        @Result(column="SYOCTO", property="syocto", jdbcType=JdbcType.NCHAR),
        @Result(column="SYRKCO", property="syrkco", jdbcType=JdbcType.NCHAR),
        @Result(column="SYRORN", property="syrorn", jdbcType=JdbcType.NCHAR),
        @Result(column="SYRCTO", property="syrcto", jdbcType=JdbcType.NCHAR),
        @Result(column="SYAN8", property="syan8", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYSHAN", property="syshan", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYDRQJ", property="sydrqj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYTRDJ", property="sytrdj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYPDDJ", property="sypddj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYOPDJ", property="syopdj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYADDJ", property="syaddj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYCNDJ", property="sycndj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYPEFJ", property="sypefj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYPPDJ", property="syppdj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYPSDJ", property="sypsdj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYVR01", property="syvr01", jdbcType=JdbcType.NCHAR),
        @Result(column="SYVR02", property="syvr02", jdbcType=JdbcType.NCHAR),
        @Result(column="SYDEL1", property="sydel1", jdbcType=JdbcType.NCHAR),
        @Result(column="SYDEL2", property="sydel2", jdbcType=JdbcType.NCHAR),
        @Result(column="SYRMK", property="syrmk", jdbcType=JdbcType.NCHAR),
        @Result(column="SYDESC", property="sydesc", jdbcType=JdbcType.NCHAR),
        @Result(column="SYINMG", property="syinmg", jdbcType=JdbcType.NCHAR),
        @Result(column="SYASN", property="syasn", jdbcType=JdbcType.NCHAR),
        @Result(column="SYPRGP", property="syprgp", jdbcType=JdbcType.NCHAR),
        @Result(column="SYPTC", property="syptc", jdbcType=JdbcType.NCHAR),
        @Result(column="SYEXR1", property="syexr1", jdbcType=JdbcType.NCHAR),
        @Result(column="SYTXA1", property="sytxa1", jdbcType=JdbcType.NCHAR),
        @Result(column="SYTXCT", property="sytxct", jdbcType=JdbcType.NCHAR),
        @Result(column="SYATXT", property="syatxt", jdbcType=JdbcType.NCHAR),
        @Result(column="SYHOLD", property="syhold", jdbcType=JdbcType.NCHAR),
        @Result(column="SYINVC", property="syinvc", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYNTR", property="syntr", jdbcType=JdbcType.NCHAR),
        @Result(column="SYCNID", property="sycnid", jdbcType=JdbcType.NCHAR),
        @Result(column="SYFRTH", property="syfrth", jdbcType=JdbcType.NCHAR),
        @Result(column="SYZON", property="syzon", jdbcType=JdbcType.NCHAR),
        @Result(column="SYANBY", property="syanby", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYANCR", property="syancr", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYMOT", property="symot", jdbcType=JdbcType.NCHAR),
        @Result(column="SYCOT", property="sycot", jdbcType=JdbcType.NCHAR),
        @Result(column="SYRCD", property="syrcd", jdbcType=JdbcType.NCHAR),
        @Result(column="SYFRTC", property="syfrtc", jdbcType=JdbcType.NCHAR),
        @Result(column="SYFUF1", property="syfuf1", jdbcType=JdbcType.NCHAR),
        @Result(column="SYFUF2", property="syfuf2", jdbcType=JdbcType.NCHAR),
        @Result(column="SYOTOT", property="syotot", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYPCRT", property="sypcrt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYRTNR", property="syrtnr", jdbcType=JdbcType.NCHAR),
        @Result(column="SYWUMD", property="sywumd", jdbcType=JdbcType.NCHAR),
        @Result(column="SYVUMD", property="syvumd", jdbcType=JdbcType.NCHAR),
        @Result(column="SYPURG", property="sypurg", jdbcType=JdbcType.NCHAR),
        @Result(column="SYLGCT", property="sylgct", jdbcType=JdbcType.NCHAR),
        @Result(column="SYPROM", property="syprom", jdbcType=JdbcType.NCHAR),
        @Result(column="SYMATY", property="symaty", jdbcType=JdbcType.NCHAR),
        @Result(column="SYOSTS", property="syosts", jdbcType=JdbcType.NCHAR),
        @Result(column="SYAVCH", property="syavch", jdbcType=JdbcType.NCHAR),
        @Result(column="SYPRPY", property="syprpy", jdbcType=JdbcType.NCHAR),
        @Result(column="SYCRMD", property="sycrmd", jdbcType=JdbcType.NCHAR),
        @Result(column="SYPRP5", property="syprp5", jdbcType=JdbcType.NCHAR),
        @Result(column="SYARTG", property="syartg", jdbcType=JdbcType.NCHAR),
        @Result(column="SYCORD", property="sycord", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYCRRM", property="sycrrm", jdbcType=JdbcType.NCHAR),
        @Result(column="SYCRCD", property="sycrcd", jdbcType=JdbcType.NCHAR),
        @Result(column="SYCRR", property="sycrr", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYLNGP", property="sylngp", jdbcType=JdbcType.NCHAR),
        @Result(column="SYFAP", property="syfap", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYORBY", property="syorby", jdbcType=JdbcType.NCHAR),
        @Result(column="SYTKBY", property="sytkby", jdbcType=JdbcType.NCHAR),
        @Result(column="SYURCD", property="syurcd", jdbcType=JdbcType.NCHAR),
        @Result(column="SYURDT", property="syurdt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYURAT", property="syurat", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYURAB", property="syurab", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYURRF", property="syurrf", jdbcType=JdbcType.NCHAR),
        @Result(column="SYTORG", property="sytorg", jdbcType=JdbcType.NCHAR),
        @Result(column="SYUSER", property="syuser", jdbcType=JdbcType.NCHAR),
        @Result(column="SYPID", property="sypid", jdbcType=JdbcType.NCHAR),
        @Result(column="SYJOBN", property="syjobn", jdbcType=JdbcType.NCHAR),
        @Result(column="SYUPMJ", property="syupmj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYTDAY", property="sytday", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYBCRC", property="sybcrc", jdbcType=JdbcType.NCHAR),
        @Result(column="SYDCD", property="sydcd", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYDCP", property="sydcp", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYNDTP", property="syndtp", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYPXDD", property="sypxdd", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYPXDM", property="sypxdm", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYDRQT", property="sydrqt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYRSHT", property="syrsht", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYDVAN", property="sydvan", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYVR03", property="syvr03", jdbcType=JdbcType.NCHAR),
        @Result(column="SYMKFR", property="symkfr", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYGAN8", property="sygan8", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYGSHAN", property="sygshan", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYGCARS", property="sygcars", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYGDVAN", property="sygdvan", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYGMKFR", property="sygmkfr", jdbcType=JdbcType.DECIMAL)
    })
    F47071 selectByPrimaryKey(@Param("syedoc") BigDecimal syedoc, @Param("syedct") String syedct, @Param("syekco") String syekco);

    @Select({
        "select",
        "SYEDOC, SYEDCT, SYEKCO, SYEDTY, SYEDSQ, SYEDLN, SYEDST, SYEDFT, SYEDDT, SYEDER, ",
        "SYEDDL, SYEDSP, SYEDBT, SYPNID, SYTPUR, SYRATY, SYKCOO, SYDOCO, SYDCTO, SYSFXO, ",
        "SYMCU, SYOKCO, SYOORN, SYOCTO, SYRKCO, SYRORN, SYRCTO, SYAN8, SYSHAN, SYDRQJ, ",
        "SYTRDJ, SYPDDJ, SYOPDJ, SYADDJ, SYCNDJ, SYPEFJ, SYPPDJ, SYPSDJ, SYVR01, SYVR02, ",
        "SYDEL1, SYDEL2, SYRMK, SYDESC, SYINMG, SYASN, SYPRGP, SYPTC, SYEXR1, SYTXA1, ",
        "SYTXCT, SYATXT, SYHOLD, SYINVC, SYNTR, SYCNID, SYFRTH, SYZON, SYANBY, SYANCR, ",
        "SYMOT, SYCOT, SYRCD, SYFRTC, SYFUF1, SYFUF2, SYOTOT, SYPCRT, SYRTNR, SYWUMD, ",
        "SYVUMD, SYPURG, SYLGCT, SYPROM, SYMATY, SYOSTS, SYAVCH, SYPRPY, SYCRMD, SYPRP5, ",
        "SYARTG, SYCORD, SYCRRM, SYCRCD, SYCRR, SYLNGP, SYFAP, SYORBY, SYTKBY, SYURCD, ",
        "SYURDT, SYURAT, SYURAB, SYURRF, SYTORG, SYUSER, SYPID, SYJOBN, SYUPMJ, SYTDAY, ",
        "SYBCRC, SYDCD, SYDCP, SYNDTP, SYPXDD, SYPXDM, SYDRQT, SYRSHT, SYDVAN, SYVR03, ",
        "SYMKFR, SYGAN8, SYGSHAN, SYGCARS, SYGDVAN, SYGMKFR",
        "from F47071"
    })
    @Results({
        @Result(column="SYEDOC", property="syedoc", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="SYEDCT", property="syedct", jdbcType=JdbcType.NCHAR, id=true),
        @Result(column="SYEKCO", property="syekco", jdbcType=JdbcType.NCHAR, id=true),
        @Result(column="SYEDTY", property="syedty", jdbcType=JdbcType.NCHAR),
        @Result(column="SYEDSQ", property="syedsq", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYEDLN", property="syedln", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYEDST", property="syedst", jdbcType=JdbcType.NCHAR),
        @Result(column="SYEDFT", property="syedft", jdbcType=JdbcType.NCHAR),
        @Result(column="SYEDDT", property="syeddt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYEDER", property="syeder", jdbcType=JdbcType.NCHAR),
        @Result(column="SYEDDL", property="syeddl", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYEDSP", property="syedsp", jdbcType=JdbcType.NCHAR),
        @Result(column="SYEDBT", property="syedbt", jdbcType=JdbcType.NCHAR),
        @Result(column="SYPNID", property="sypnid", jdbcType=JdbcType.NCHAR),
        @Result(column="SYTPUR", property="sytpur", jdbcType=JdbcType.NCHAR),
        @Result(column="SYRATY", property="syraty", jdbcType=JdbcType.NCHAR),
        @Result(column="SYKCOO", property="sykcoo", jdbcType=JdbcType.NCHAR),
        @Result(column="SYDOCO", property="sydoco", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYDCTO", property="sydcto", jdbcType=JdbcType.NCHAR),
        @Result(column="SYSFXO", property="sysfxo", jdbcType=JdbcType.NCHAR),
        @Result(column="SYMCU", property="symcu", jdbcType=JdbcType.NCHAR),
        @Result(column="SYOKCO", property="syokco", jdbcType=JdbcType.NCHAR),
        @Result(column="SYOORN", property="syoorn", jdbcType=JdbcType.NCHAR),
        @Result(column="SYOCTO", property="syocto", jdbcType=JdbcType.NCHAR),
        @Result(column="SYRKCO", property="syrkco", jdbcType=JdbcType.NCHAR),
        @Result(column="SYRORN", property="syrorn", jdbcType=JdbcType.NCHAR),
        @Result(column="SYRCTO", property="syrcto", jdbcType=JdbcType.NCHAR),
        @Result(column="SYAN8", property="syan8", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYSHAN", property="syshan", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYDRQJ", property="sydrqj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYTRDJ", property="sytrdj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYPDDJ", property="sypddj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYOPDJ", property="syopdj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYADDJ", property="syaddj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYCNDJ", property="sycndj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYPEFJ", property="sypefj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYPPDJ", property="syppdj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYPSDJ", property="sypsdj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYVR01", property="syvr01", jdbcType=JdbcType.NCHAR),
        @Result(column="SYVR02", property="syvr02", jdbcType=JdbcType.NCHAR),
        @Result(column="SYDEL1", property="sydel1", jdbcType=JdbcType.NCHAR),
        @Result(column="SYDEL2", property="sydel2", jdbcType=JdbcType.NCHAR),
        @Result(column="SYRMK", property="syrmk", jdbcType=JdbcType.NCHAR),
        @Result(column="SYDESC", property="sydesc", jdbcType=JdbcType.NCHAR),
        @Result(column="SYINMG", property="syinmg", jdbcType=JdbcType.NCHAR),
        @Result(column="SYASN", property="syasn", jdbcType=JdbcType.NCHAR),
        @Result(column="SYPRGP", property="syprgp", jdbcType=JdbcType.NCHAR),
        @Result(column="SYPTC", property="syptc", jdbcType=JdbcType.NCHAR),
        @Result(column="SYEXR1", property="syexr1", jdbcType=JdbcType.NCHAR),
        @Result(column="SYTXA1", property="sytxa1", jdbcType=JdbcType.NCHAR),
        @Result(column="SYTXCT", property="sytxct", jdbcType=JdbcType.NCHAR),
        @Result(column="SYATXT", property="syatxt", jdbcType=JdbcType.NCHAR),
        @Result(column="SYHOLD", property="syhold", jdbcType=JdbcType.NCHAR),
        @Result(column="SYINVC", property="syinvc", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYNTR", property="syntr", jdbcType=JdbcType.NCHAR),
        @Result(column="SYCNID", property="sycnid", jdbcType=JdbcType.NCHAR),
        @Result(column="SYFRTH", property="syfrth", jdbcType=JdbcType.NCHAR),
        @Result(column="SYZON", property="syzon", jdbcType=JdbcType.NCHAR),
        @Result(column="SYANBY", property="syanby", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYANCR", property="syancr", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYMOT", property="symot", jdbcType=JdbcType.NCHAR),
        @Result(column="SYCOT", property="sycot", jdbcType=JdbcType.NCHAR),
        @Result(column="SYRCD", property="syrcd", jdbcType=JdbcType.NCHAR),
        @Result(column="SYFRTC", property="syfrtc", jdbcType=JdbcType.NCHAR),
        @Result(column="SYFUF1", property="syfuf1", jdbcType=JdbcType.NCHAR),
        @Result(column="SYFUF2", property="syfuf2", jdbcType=JdbcType.NCHAR),
        @Result(column="SYOTOT", property="syotot", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYPCRT", property="sypcrt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYRTNR", property="syrtnr", jdbcType=JdbcType.NCHAR),
        @Result(column="SYWUMD", property="sywumd", jdbcType=JdbcType.NCHAR),
        @Result(column="SYVUMD", property="syvumd", jdbcType=JdbcType.NCHAR),
        @Result(column="SYPURG", property="sypurg", jdbcType=JdbcType.NCHAR),
        @Result(column="SYLGCT", property="sylgct", jdbcType=JdbcType.NCHAR),
        @Result(column="SYPROM", property="syprom", jdbcType=JdbcType.NCHAR),
        @Result(column="SYMATY", property="symaty", jdbcType=JdbcType.NCHAR),
        @Result(column="SYOSTS", property="syosts", jdbcType=JdbcType.NCHAR),
        @Result(column="SYAVCH", property="syavch", jdbcType=JdbcType.NCHAR),
        @Result(column="SYPRPY", property="syprpy", jdbcType=JdbcType.NCHAR),
        @Result(column="SYCRMD", property="sycrmd", jdbcType=JdbcType.NCHAR),
        @Result(column="SYPRP5", property="syprp5", jdbcType=JdbcType.NCHAR),
        @Result(column="SYARTG", property="syartg", jdbcType=JdbcType.NCHAR),
        @Result(column="SYCORD", property="sycord", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYCRRM", property="sycrrm", jdbcType=JdbcType.NCHAR),
        @Result(column="SYCRCD", property="sycrcd", jdbcType=JdbcType.NCHAR),
        @Result(column="SYCRR", property="sycrr", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYLNGP", property="sylngp", jdbcType=JdbcType.NCHAR),
        @Result(column="SYFAP", property="syfap", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYORBY", property="syorby", jdbcType=JdbcType.NCHAR),
        @Result(column="SYTKBY", property="sytkby", jdbcType=JdbcType.NCHAR),
        @Result(column="SYURCD", property="syurcd", jdbcType=JdbcType.NCHAR),
        @Result(column="SYURDT", property="syurdt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYURAT", property="syurat", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYURAB", property="syurab", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYURRF", property="syurrf", jdbcType=JdbcType.NCHAR),
        @Result(column="SYTORG", property="sytorg", jdbcType=JdbcType.NCHAR),
        @Result(column="SYUSER", property="syuser", jdbcType=JdbcType.NCHAR),
        @Result(column="SYPID", property="sypid", jdbcType=JdbcType.NCHAR),
        @Result(column="SYJOBN", property="syjobn", jdbcType=JdbcType.NCHAR),
        @Result(column="SYUPMJ", property="syupmj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYTDAY", property="sytday", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYBCRC", property="sybcrc", jdbcType=JdbcType.NCHAR),
        @Result(column="SYDCD", property="sydcd", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYDCP", property="sydcp", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYNDTP", property="syndtp", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYPXDD", property="sypxdd", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYPXDM", property="sypxdm", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYDRQT", property="sydrqt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYRSHT", property="syrsht", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYDVAN", property="sydvan", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYVR03", property="syvr03", jdbcType=JdbcType.NCHAR),
        @Result(column="SYMKFR", property="symkfr", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYGAN8", property="sygan8", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYGSHAN", property="sygshan", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYGCARS", property="sygcars", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYGDVAN", property="sygdvan", jdbcType=JdbcType.DECIMAL),
        @Result(column="SYGMKFR", property="sygmkfr", jdbcType=JdbcType.DECIMAL)
    })
    List<F47071> selectAll();
}