package nc.itf.mdm.ws.mfr;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-10-17T10:45:30.281+08:00
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "QxmdmMfrService", 
                  wsdlLocation = "http://10.17.9.94/uapws/service/QxmdmMfrService?wsdl",
                  targetNamespace = "http://ws.mdm.itf.nc/QxmdmMfrService") 
public class QxmdmMfrService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.mdm.itf.nc/QxmdmMfrService", "QxmdmMfrService");
    public final static QName QxmdmMfrServiceSOAP11PortHttp = new QName("http://ws.mdm.itf.nc/QxmdmMfrService", "QxmdmMfrServiceSOAP11port_http");
    static {
        URL url = null;
        try {
            url = new URL("http://10.17.9.94/uapws/service/QxmdmMfrService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(QxmdmMfrService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.17.9.94/uapws/service/QxmdmMfrService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public QxmdmMfrService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public QxmdmMfrService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QxmdmMfrService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public QxmdmMfrService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public QxmdmMfrService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public QxmdmMfrService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns QxmdmMfrServicePortType
     */
    @WebEndpoint(name = "QxmdmMfrServiceSOAP11port_http")
    public QxmdmMfrServicePortType getQxmdmMfrServiceSOAP11PortHttp() {
        return super.getPort(QxmdmMfrServiceSOAP11PortHttp, QxmdmMfrServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QxmdmMfrServicePortType
     */
    @WebEndpoint(name = "QxmdmMfrServiceSOAP11port_http")
    public QxmdmMfrServicePortType getQxmdmMfrServiceSOAP11PortHttp(WebServiceFeature... features) {
        return super.getPort(QxmdmMfrServiceSOAP11PortHttp, QxmdmMfrServicePortType.class, features);
    }

}
