package nc.itf.mdm.ws.eq;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-10-20T13:44:55.186+08:00
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "QxmdmEquService", 
                  wsdlLocation = "http://10.17.28.103/uapws/service/QxmdmEquService?wsdl",
                  targetNamespace = "http://ws.mdm.itf.nc/QxmdmEquService") 
public class QxmdmEquService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.mdm.itf.nc/QxmdmEquService", "QxmdmEquService");
    public final static QName QxmdmEquServiceSOAP11PortHttp = new QName("http://ws.mdm.itf.nc/QxmdmEquService", "QxmdmEquServiceSOAP11port_http");
    static {
        URL url = null;
        try {
            url = new URL("http://10.17.28.103/uapws/service/QxmdmEquService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(QxmdmEquService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.17.28.103/uapws/service/QxmdmEquService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public QxmdmEquService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public QxmdmEquService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QxmdmEquService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public QxmdmEquService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public QxmdmEquService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public QxmdmEquService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns QxmdmEquServicePortType
     */
    @WebEndpoint(name = "QxmdmEquServiceSOAP11port_http")
    public QxmdmEquServicePortType getQxmdmEquServiceSOAP11PortHttp() {
        return super.getPort(QxmdmEquServiceSOAP11PortHttp, QxmdmEquServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QxmdmEquServicePortType
     */
    @WebEndpoint(name = "QxmdmEquServiceSOAP11port_http")
    public QxmdmEquServicePortType getQxmdmEquServiceSOAP11PortHttp(WebServiceFeature... features) {
        return super.getPort(QxmdmEquServiceSOAP11PortHttp, QxmdmEquServicePortType.class, features);
    }

}
