package com.el.cfg.mapper;

import com.el.cfg.domain.F4311;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

public interface F4311Mapper {
    @Select({
        "select",
        "PDDOCO, PDDCTO, PDKCOO, PDSFXO, PDLNID, PDMCU, PDCO, PDOKCO, PDOORN, PDOCTO, ",
        "PDOGNO, PDRKCO, PDRORN, PDRCTO, PDRLLN, PDDMCT, PDDMCS, PDBALU, PDAN8, PDSHAN, ",
        "PDDRQJ, PDTRDJ, PDPDDJ, PDOPDJ, PDADDJ, PDCNDJ, PDPEFJ, PDPPDJ, PDPSDJ, PDDSVJ, ",
        "PDDGL, PDPN, PDVR01, PDVR02, PDITM, PDLITM, PDAITM, PDLOCN, PDLOTN, PDFRGD, ",
        "PDTHGD, PDFRMP, PDTHRP, PDDSC1, PDDSC2, PDLNTY, PDNXTR, PDLTTR, PDRLIT, PDPDS1, ",
        "PDPDS2, PDPDS3, PDPDS4, PDPDS5, PDPDP1, PDPDP2, PDPDP3, PDPDP4, PDPDP5, PDUOM, ",
        "PDUORG, PDUCHG, PDUOPN, PDUREC, PDCREC, PDURLV, PDOTQY, PDPRRC, PDAEXP, PDACHG, ",
        "PDAOPN, PDAREC, PDARLV, PDFTN1, PDTRLV, PDPROV, PDAMC3, PDECST, PDCSTO, PDCSMP, ",
        "PDINMG, PDASN, PDPRGR, PDCLVL, PDCATN, PDDSPR, PDPTC, PDTX, PDEXR1, PDTXA1, ",
        "PDATXT, PDCNID, PDCDCD, PDNTR, PDFRTH, PDFRTC, PDZON, PDFRAT, PDRATT, PDANBY, ",
        "PDANCR, PDMOT, PDCOT, PDSHCM, PDSHCN, PDUOM1, PDPQOR, PDUOM2, PDSQOR, PDUOM3, ",
        "PDITWT, PDWTUM, PDITVL, PDVLUM, PDGLC, PDCTRY, PDFY, PDSTTS, PDRCD, PDFUF1, ",
        "PDFUF2, PDGRWT, PDGWUM, PDLT, PDANI, PDAID, PDOMCU, PDOBJ, PDSUB, PDSBLT, PDSBL, ",
        "PDASID, PDCCMP, PDTAG, PDWR01, PDPL, PDELEV, PDR001, PDRTNR, PDLCOD, PDPURG, ",
        "PDPROM, PDFNLP, PDAVCH, PDPRPY, PDUNCD, PDMATY, PDRTGC, PDRCPF, PDPS01, PDPS02, ",
        "PDPS03, PDPS04, PDPS05, PDPS06, PDPS07, PDPS08, PDPS09, PDPS10, PDCRMD, PDARTG, ",
        "PDCORD, PDCHDT, PDDOCC, PDCHLN, PDCRCD, PDCRR, PDFRRC, PDFEA, PDFUC, PDFEC, ",
        "PDFCHG, PDFAP, PDFREC, PDURCD, PDURDT, PDURAT, PDURAB, PDURRF, PDTORG, PDUSER, ",
        "PDPID, PDJOBN, PDUPMJ, PDTDAY, PDVR05, PDVR04, PDSHPN, PDRSHT, PDPRJM, PDOSFX, ",
        "PDMERL, PDMCLN, PDMACT, PDKTLN, PDFTRL, PDDUAL, PDDRQT, PDDLEJ, PDCTAM, PDCPNT, ",
        "PDCHT, PDCHRT, PDCHRS, PDCHMJ, PDBCRC, PDVR03, PDLDNM, PDMKFR, PDPMTN, PDUKID, ",
        "PDUNSPSC, PDCMDCDE, PDRSFX, PDWVID, PDCNTRTID, PDCNTRTDID, PDMOADJ, PDPODC01, ",
        "PDPODC02, PDPODC03, PDPODC04, PDJBCD, PDSRQTY, PDSRUOM, PDCFGFL, PDPMPN, PDPNS",
        "from F4311",
        "where PDDOCO = #{pddoco,jdbcType=DECIMAL}",
          "and PDDCTO = #{pddcto,jdbcType=NCHAR}",
          "and PDKCOO = #{pdkcoo,jdbcType=NCHAR}",
          "and PDSFXO = #{pdsfxo,jdbcType=NCHAR}",
          "and PDLNID = #{pdlnid,jdbcType=DECIMAL}"
    })
    @Results({
        @Result(column="PDDOCO", property="pddoco", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="PDDCTO", property="pddcto", jdbcType=JdbcType.NCHAR, id=true),
        @Result(column="PDKCOO", property="pdkcoo", jdbcType=JdbcType.NCHAR, id=true),
        @Result(column="PDSFXO", property="pdsfxo", jdbcType=JdbcType.NCHAR, id=true),
        @Result(column="PDLNID", property="pdlnid", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="PDMCU", property="pdmcu", jdbcType=JdbcType.NCHAR),
        @Result(column="PDCO", property="pdco", jdbcType=JdbcType.NCHAR),
        @Result(column="PDOKCO", property="pdokco", jdbcType=JdbcType.NCHAR),
        @Result(column="PDOORN", property="pdoorn", jdbcType=JdbcType.NCHAR),
        @Result(column="PDOCTO", property="pdocto", jdbcType=JdbcType.NCHAR),
        @Result(column="PDOGNO", property="pdogno", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDRKCO", property="pdrkco", jdbcType=JdbcType.NCHAR),
        @Result(column="PDRORN", property="pdrorn", jdbcType=JdbcType.NCHAR),
        @Result(column="PDRCTO", property="pdrcto", jdbcType=JdbcType.NCHAR),
        @Result(column="PDRLLN", property="pdrlln", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDDMCT", property="pddmct", jdbcType=JdbcType.NCHAR),
        @Result(column="PDDMCS", property="pddmcs", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDBALU", property="pdbalu", jdbcType=JdbcType.NCHAR),
        @Result(column="PDAN8", property="pdan8", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDSHAN", property="pdshan", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDDRQJ", property="pddrqj", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDTRDJ", property="pdtrdj", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDPDDJ", property="pdpddj", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDOPDJ", property="pdopdj", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDADDJ", property="pdaddj", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDCNDJ", property="pdcndj", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDPEFJ", property="pdpefj", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDPPDJ", property="pdppdj", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDPSDJ", property="pdpsdj", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDDSVJ", property="pddsvj", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDDGL", property="pddgl", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDPN", property="pdpn", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDVR01", property="pdvr01", jdbcType=JdbcType.NCHAR),
        @Result(column="PDVR02", property="pdvr02", jdbcType=JdbcType.NCHAR),
        @Result(column="PDITM", property="pditm", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDLITM", property="pdlitm", jdbcType=JdbcType.NCHAR),
        @Result(column="PDAITM", property="pdaitm", jdbcType=JdbcType.NCHAR),
        @Result(column="PDLOCN", property="pdlocn", jdbcType=JdbcType.NCHAR),
        @Result(column="PDLOTN", property="pdlotn", jdbcType=JdbcType.NCHAR),
        @Result(column="PDFRGD", property="pdfrgd", jdbcType=JdbcType.NCHAR),
        @Result(column="PDTHGD", property="pdthgd", jdbcType=JdbcType.NCHAR),
        @Result(column="PDFRMP", property="pdfrmp", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDTHRP", property="pdthrp", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDDSC1", property="pddsc1", jdbcType=JdbcType.NCHAR),
        @Result(column="PDDSC2", property="pddsc2", jdbcType=JdbcType.NCHAR),
        @Result(column="PDLNTY", property="pdlnty", jdbcType=JdbcType.NCHAR),
        @Result(column="PDNXTR", property="pdnxtr", jdbcType=JdbcType.NCHAR),
        @Result(column="PDLTTR", property="pdlttr", jdbcType=JdbcType.NCHAR),
        @Result(column="PDRLIT", property="pdrlit", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPDS1", property="pdpds1", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPDS2", property="pdpds2", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPDS3", property="pdpds3", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPDS4", property="pdpds4", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPDS5", property="pdpds5", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPDP1", property="pdpdp1", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPDP2", property="pdpdp2", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPDP3", property="pdpdp3", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPDP4", property="pdpdp4", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPDP5", property="pdpdp5", jdbcType=JdbcType.NCHAR),
        @Result(column="PDUOM", property="pduom", jdbcType=JdbcType.NCHAR),
        @Result(column="PDUORG", property="pduorg", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDUCHG", property="pduchg", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDUOPN", property="pduopn", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDUREC", property="pdurec", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDCREC", property="pdcrec", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDURLV", property="pdurlv", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDOTQY", property="pdotqy", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPRRC", property="pdprrc", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDAEXP", property="pdaexp", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDACHG", property="pdachg", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDAOPN", property="pdaopn", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDAREC", property="pdarec", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDARLV", property="pdarlv", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDFTN1", property="pdftn1", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDTRLV", property="pdtrlv", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDPROV", property="pdprov", jdbcType=JdbcType.NCHAR),
        @Result(column="PDAMC3", property="pdamc3", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDECST", property="pdecst", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDCSTO", property="pdcsto", jdbcType=JdbcType.NCHAR),
        @Result(column="PDCSMP", property="pdcsmp", jdbcType=JdbcType.NCHAR),
        @Result(column="PDINMG", property="pdinmg", jdbcType=JdbcType.NCHAR),
        @Result(column="PDASN", property="pdasn", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPRGR", property="pdprgr", jdbcType=JdbcType.NCHAR),
        @Result(column="PDCLVL", property="pdclvl", jdbcType=JdbcType.NCHAR),
        @Result(column="PDCATN", property="pdcatn", jdbcType=JdbcType.NCHAR),
        @Result(column="PDDSPR", property="pddspr", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDPTC", property="pdptc", jdbcType=JdbcType.NCHAR),
        @Result(column="PDTX", property="pdtx", jdbcType=JdbcType.NCHAR),
        @Result(column="PDEXR1", property="pdexr1", jdbcType=JdbcType.NCHAR),
        @Result(column="PDTXA1", property="pdtxa1", jdbcType=JdbcType.NCHAR),
        @Result(column="PDATXT", property="pdatxt", jdbcType=JdbcType.NCHAR),
        @Result(column="PDCNID", property="pdcnid", jdbcType=JdbcType.NCHAR),
        @Result(column="PDCDCD", property="pdcdcd", jdbcType=JdbcType.NCHAR),
        @Result(column="PDNTR", property="pdntr", jdbcType=JdbcType.NCHAR),
        @Result(column="PDFRTH", property="pdfrth", jdbcType=JdbcType.NCHAR),
        @Result(column="PDFRTC", property="pdfrtc", jdbcType=JdbcType.NCHAR),
        @Result(column="PDZON", property="pdzon", jdbcType=JdbcType.NCHAR),
        @Result(column="PDFRAT", property="pdfrat", jdbcType=JdbcType.NCHAR),
        @Result(column="PDRATT", property="pdratt", jdbcType=JdbcType.NCHAR),
        @Result(column="PDANBY", property="pdanby", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDANCR", property="pdancr", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDMOT", property="pdmot", jdbcType=JdbcType.NCHAR),
        @Result(column="PDCOT", property="pdcot", jdbcType=JdbcType.NCHAR),
        @Result(column="PDSHCM", property="pdshcm", jdbcType=JdbcType.NCHAR),
        @Result(column="PDSHCN", property="pdshcn", jdbcType=JdbcType.NCHAR),
        @Result(column="PDUOM1", property="pduom1", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPQOR", property="pdpqor", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDUOM2", property="pduom2", jdbcType=JdbcType.NCHAR),
        @Result(column="PDSQOR", property="pdsqor", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDUOM3", property="pduom3", jdbcType=JdbcType.NCHAR),
        @Result(column="PDITWT", property="pditwt", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDWTUM", property="pdwtum", jdbcType=JdbcType.NCHAR),
        @Result(column="PDITVL", property="pditvl", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDVLUM", property="pdvlum", jdbcType=JdbcType.NCHAR),
        @Result(column="PDGLC", property="pdglc", jdbcType=JdbcType.NCHAR),
        @Result(column="PDCTRY", property="pdctry", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDFY", property="pdfy", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDSTTS", property="pdstts", jdbcType=JdbcType.NCHAR),
        @Result(column="PDRCD", property="pdrcd", jdbcType=JdbcType.NCHAR),
        @Result(column="PDFUF1", property="pdfuf1", jdbcType=JdbcType.NCHAR),
        @Result(column="PDFUF2", property="pdfuf2", jdbcType=JdbcType.NCHAR),
        @Result(column="PDGRWT", property="pdgrwt", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDGWUM", property="pdgwum", jdbcType=JdbcType.NCHAR),
        @Result(column="PDLT", property="pdlt", jdbcType=JdbcType.NCHAR),
        @Result(column="PDANI", property="pdani", jdbcType=JdbcType.NCHAR),
        @Result(column="PDAID", property="pdaid", jdbcType=JdbcType.NCHAR),
        @Result(column="PDOMCU", property="pdomcu", jdbcType=JdbcType.NCHAR),
        @Result(column="PDOBJ", property="pdobj", jdbcType=JdbcType.NCHAR),
        @Result(column="PDSUB", property="pdsub", jdbcType=JdbcType.NCHAR),
        @Result(column="PDSBLT", property="pdsblt", jdbcType=JdbcType.NCHAR),
        @Result(column="PDSBL", property="pdsbl", jdbcType=JdbcType.NCHAR),
        @Result(column="PDASID", property="pdasid", jdbcType=JdbcType.NCHAR),
        @Result(column="PDCCMP", property="pdccmp", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDTAG", property="pdtag", jdbcType=JdbcType.NCHAR),
        @Result(column="PDWR01", property="pdwr01", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPL", property="pdpl", jdbcType=JdbcType.NCHAR),
        @Result(column="PDELEV", property="pdelev", jdbcType=JdbcType.NCHAR),
        @Result(column="PDR001", property="pdr001", jdbcType=JdbcType.NCHAR),
        @Result(column="PDRTNR", property="pdrtnr", jdbcType=JdbcType.NCHAR),
        @Result(column="PDLCOD", property="pdlcod", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPURG", property="pdpurg", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPROM", property="pdprom", jdbcType=JdbcType.NCHAR),
        @Result(column="PDFNLP", property="pdfnlp", jdbcType=JdbcType.NCHAR),
        @Result(column="PDAVCH", property="pdavch", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPRPY", property="pdprpy", jdbcType=JdbcType.NCHAR),
        @Result(column="PDUNCD", property="pduncd", jdbcType=JdbcType.NCHAR),
        @Result(column="PDMATY", property="pdmaty", jdbcType=JdbcType.NCHAR),
        @Result(column="PDRTGC", property="pdrtgc", jdbcType=JdbcType.NCHAR),
        @Result(column="PDRCPF", property="pdrcpf", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPS01", property="pdps01", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPS02", property="pdps02", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPS03", property="pdps03", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPS04", property="pdps04", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPS05", property="pdps05", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPS06", property="pdps06", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPS07", property="pdps07", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPS08", property="pdps08", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPS09", property="pdps09", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPS10", property="pdps10", jdbcType=JdbcType.NCHAR),
        @Result(column="PDCRMD", property="pdcrmd", jdbcType=JdbcType.NCHAR),
        @Result(column="PDARTG", property="pdartg", jdbcType=JdbcType.NCHAR),
        @Result(column="PDCORD", property="pdcord", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDCHDT", property="pdchdt", jdbcType=JdbcType.NCHAR),
        @Result(column="PDDOCC", property="pddocc", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDCHLN", property="pdchln", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDCRCD", property="pdcrcd", jdbcType=JdbcType.NCHAR),
        @Result(column="PDCRR", property="pdcrr", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDFRRC", property="pdfrrc", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDFEA", property="pdfea", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDFUC", property="pdfuc", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDFEC", property="pdfec", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDFCHG", property="pdfchg", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDFAP", property="pdfap", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDFREC", property="pdfrec", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDURCD", property="pdurcd", jdbcType=JdbcType.NCHAR),
        @Result(column="PDURDT", property="pdurdt", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDURAT", property="pdurat", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDURAB", property="pdurab", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDURRF", property="pdurrf", jdbcType=JdbcType.NCHAR),
        @Result(column="PDTORG", property="pdtorg", jdbcType=JdbcType.NCHAR),
        @Result(column="PDUSER", property="pduser", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPID", property="pdpid", jdbcType=JdbcType.NCHAR),
        @Result(column="PDJOBN", property="pdjobn", jdbcType=JdbcType.NCHAR),
        @Result(column="PDUPMJ", property="pdupmj", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDTDAY", property="pdtday", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDVR05", property="pdvr05", jdbcType=JdbcType.NCHAR),
        @Result(column="PDVR04", property="pdvr04", jdbcType=JdbcType.NCHAR),
        @Result(column="PDSHPN", property="pdshpn", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDRSHT", property="pdrsht", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDPRJM", property="pdprjm", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDOSFX", property="pdosfx", jdbcType=JdbcType.NCHAR),
        @Result(column="PDMERL", property="pdmerl", jdbcType=JdbcType.NCHAR),
        @Result(column="PDMCLN", property="pdmcln", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDMACT", property="pdmact", jdbcType=JdbcType.NCHAR),
        @Result(column="PDKTLN", property="pdktln", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDFTRL", property="pdftrl", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDDUAL", property="pddual", jdbcType=JdbcType.NCHAR),
        @Result(column="PDDRQT", property="pddrqt", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDDLEJ", property="pddlej", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDCTAM", property="pdctam", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDCPNT", property="pdcpnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDCHT", property="pdcht", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDCHRT", property="pdchrt", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDCHRS", property="pdchrs", jdbcType=JdbcType.NCHAR),
        @Result(column="PDCHMJ", property="pdchmj", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDBCRC", property="pdbcrc", jdbcType=JdbcType.NCHAR),
        @Result(column="PDVR03", property="pdvr03", jdbcType=JdbcType.NCHAR),
        @Result(column="PDLDNM", property="pdldnm", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDMKFR", property="pdmkfr", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDPMTN", property="pdpmtn", jdbcType=JdbcType.NCHAR),
        @Result(column="PDUKID", property="pdukid", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDUNSPSC", property="pdunspsc", jdbcType=JdbcType.NCHAR),
        @Result(column="PDCMDCDE", property="pdcmdcde", jdbcType=JdbcType.NCHAR),
        @Result(column="PDRSFX", property="pdrsfx", jdbcType=JdbcType.NCHAR),
        @Result(column="PDWVID", property="pdwvid", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDCNTRTID", property="pdcntrtid", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDCNTRTDID", property="pdcntrtdid", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDMOADJ", property="pdmoadj", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPODC01", property="pdpodc01", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPODC02", property="pdpodc02", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPODC03", property="pdpodc03", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPODC04", property="pdpodc04", jdbcType=JdbcType.NCHAR),
        @Result(column="PDJBCD", property="pdjbcd", jdbcType=JdbcType.NCHAR),
        @Result(column="PDSRQTY", property="pdsrqty", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDSRUOM", property="pdsruom", jdbcType=JdbcType.NCHAR),
        @Result(column="PDCFGFL", property="pdcfgfl", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPMPN", property="pdpmpn", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPNS", property="pdpns", jdbcType=JdbcType.DECIMAL)
    })
    F4311 selectByPrimaryKey(@Param("pddoco") BigDecimal pddoco, @Param("pddcto") String pddcto, @Param("pdkcoo") String pdkcoo, @Param("pdsfxo") String pdsfxo, @Param("pdlnid") BigDecimal pdlnid);

    @Select({
        "select",
        "PDDOCO, PDDCTO, PDKCOO, PDSFXO, PDLNID, PDMCU, PDCO, PDOKCO, PDOORN, PDOCTO, ",
        "PDOGNO, PDRKCO, PDRORN, PDRCTO, PDRLLN, PDDMCT, PDDMCS, PDBALU, PDAN8, PDSHAN, ",
        "PDDRQJ, PDTRDJ, PDPDDJ, PDOPDJ, PDADDJ, PDCNDJ, PDPEFJ, PDPPDJ, PDPSDJ, PDDSVJ, ",
        "PDDGL, PDPN, PDVR01, PDVR02, PDITM, PDLITM, PDAITM, PDLOCN, PDLOTN, PDFRGD, ",
        "PDTHGD, PDFRMP, PDTHRP, PDDSC1, PDDSC2, PDLNTY, PDNXTR, PDLTTR, PDRLIT, PDPDS1, ",
        "PDPDS2, PDPDS3, PDPDS4, PDPDS5, PDPDP1, PDPDP2, PDPDP3, PDPDP4, PDPDP5, PDUOM, ",
        "PDUORG, PDUCHG, PDUOPN, PDUREC, PDCREC, PDURLV, PDOTQY, PDPRRC, PDAEXP, PDACHG, ",
        "PDAOPN, PDAREC, PDARLV, PDFTN1, PDTRLV, PDPROV, PDAMC3, PDECST, PDCSTO, PDCSMP, ",
        "PDINMG, PDASN, PDPRGR, PDCLVL, PDCATN, PDDSPR, PDPTC, PDTX, PDEXR1, PDTXA1, ",
        "PDATXT, PDCNID, PDCDCD, PDNTR, PDFRTH, PDFRTC, PDZON, PDFRAT, PDRATT, PDANBY, ",
        "PDANCR, PDMOT, PDCOT, PDSHCM, PDSHCN, PDUOM1, PDPQOR, PDUOM2, PDSQOR, PDUOM3, ",
        "PDITWT, PDWTUM, PDITVL, PDVLUM, PDGLC, PDCTRY, PDFY, PDSTTS, PDRCD, PDFUF1, ",
        "PDFUF2, PDGRWT, PDGWUM, PDLT, PDANI, PDAID, PDOMCU, PDOBJ, PDSUB, PDSBLT, PDSBL, ",
        "PDASID, PDCCMP, PDTAG, PDWR01, PDPL, PDELEV, PDR001, PDRTNR, PDLCOD, PDPURG, ",
        "PDPROM, PDFNLP, PDAVCH, PDPRPY, PDUNCD, PDMATY, PDRTGC, PDRCPF, PDPS01, PDPS02, ",
        "PDPS03, PDPS04, PDPS05, PDPS06, PDPS07, PDPS08, PDPS09, PDPS10, PDCRMD, PDARTG, ",
        "PDCORD, PDCHDT, PDDOCC, PDCHLN, PDCRCD, PDCRR, PDFRRC, PDFEA, PDFUC, PDFEC, ",
        "PDFCHG, PDFAP, PDFREC, PDURCD, PDURDT, PDURAT, PDURAB, PDURRF, PDTORG, PDUSER, ",
        "PDPID, PDJOBN, PDUPMJ, PDTDAY, PDVR05, PDVR04, PDSHPN, PDRSHT, PDPRJM, PDOSFX, ",
        "PDMERL, PDMCLN, PDMACT, PDKTLN, PDFTRL, PDDUAL, PDDRQT, PDDLEJ, PDCTAM, PDCPNT, ",
        "PDCHT, PDCHRT, PDCHRS, PDCHMJ, PDBCRC, PDVR03, PDLDNM, PDMKFR, PDPMTN, PDUKID, ",
        "PDUNSPSC, PDCMDCDE, PDRSFX, PDWVID, PDCNTRTID, PDCNTRTDID, PDMOADJ, PDPODC01, ",
        "PDPODC02, PDPODC03, PDPODC04, PDJBCD, PDSRQTY, PDSRUOM, PDCFGFL, PDPMPN, PDPNS",
        "from F4311"
    })
    @Results({
        @Result(column="PDDOCO", property="pddoco", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="PDDCTO", property="pddcto", jdbcType=JdbcType.NCHAR, id=true),
        @Result(column="PDKCOO", property="pdkcoo", jdbcType=JdbcType.NCHAR, id=true),
        @Result(column="PDSFXO", property="pdsfxo", jdbcType=JdbcType.NCHAR, id=true),
        @Result(column="PDLNID", property="pdlnid", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="PDMCU", property="pdmcu", jdbcType=JdbcType.NCHAR),
        @Result(column="PDCO", property="pdco", jdbcType=JdbcType.NCHAR),
        @Result(column="PDOKCO", property="pdokco", jdbcType=JdbcType.NCHAR),
        @Result(column="PDOORN", property="pdoorn", jdbcType=JdbcType.NCHAR),
        @Result(column="PDOCTO", property="pdocto", jdbcType=JdbcType.NCHAR),
        @Result(column="PDOGNO", property="pdogno", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDRKCO", property="pdrkco", jdbcType=JdbcType.NCHAR),
        @Result(column="PDRORN", property="pdrorn", jdbcType=JdbcType.NCHAR),
        @Result(column="PDRCTO", property="pdrcto", jdbcType=JdbcType.NCHAR),
        @Result(column="PDRLLN", property="pdrlln", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDDMCT", property="pddmct", jdbcType=JdbcType.NCHAR),
        @Result(column="PDDMCS", property="pddmcs", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDBALU", property="pdbalu", jdbcType=JdbcType.NCHAR),
        @Result(column="PDAN8", property="pdan8", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDSHAN", property="pdshan", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDDRQJ", property="pddrqj", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDTRDJ", property="pdtrdj", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDPDDJ", property="pdpddj", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDOPDJ", property="pdopdj", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDADDJ", property="pdaddj", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDCNDJ", property="pdcndj", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDPEFJ", property="pdpefj", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDPPDJ", property="pdppdj", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDPSDJ", property="pdpsdj", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDDSVJ", property="pddsvj", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDDGL", property="pddgl", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDPN", property="pdpn", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDVR01", property="pdvr01", jdbcType=JdbcType.NCHAR),
        @Result(column="PDVR02", property="pdvr02", jdbcType=JdbcType.NCHAR),
        @Result(column="PDITM", property="pditm", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDLITM", property="pdlitm", jdbcType=JdbcType.NCHAR),
        @Result(column="PDAITM", property="pdaitm", jdbcType=JdbcType.NCHAR),
        @Result(column="PDLOCN", property="pdlocn", jdbcType=JdbcType.NCHAR),
        @Result(column="PDLOTN", property="pdlotn", jdbcType=JdbcType.NCHAR),
        @Result(column="PDFRGD", property="pdfrgd", jdbcType=JdbcType.NCHAR),
        @Result(column="PDTHGD", property="pdthgd", jdbcType=JdbcType.NCHAR),
        @Result(column="PDFRMP", property="pdfrmp", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDTHRP", property="pdthrp", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDDSC1", property="pddsc1", jdbcType=JdbcType.NCHAR),
        @Result(column="PDDSC2", property="pddsc2", jdbcType=JdbcType.NCHAR),
        @Result(column="PDLNTY", property="pdlnty", jdbcType=JdbcType.NCHAR),
        @Result(column="PDNXTR", property="pdnxtr", jdbcType=JdbcType.NCHAR),
        @Result(column="PDLTTR", property="pdlttr", jdbcType=JdbcType.NCHAR),
        @Result(column="PDRLIT", property="pdrlit", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPDS1", property="pdpds1", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPDS2", property="pdpds2", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPDS3", property="pdpds3", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPDS4", property="pdpds4", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPDS5", property="pdpds5", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPDP1", property="pdpdp1", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPDP2", property="pdpdp2", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPDP3", property="pdpdp3", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPDP4", property="pdpdp4", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPDP5", property="pdpdp5", jdbcType=JdbcType.NCHAR),
        @Result(column="PDUOM", property="pduom", jdbcType=JdbcType.NCHAR),
        @Result(column="PDUORG", property="pduorg", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDUCHG", property="pduchg", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDUOPN", property="pduopn", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDUREC", property="pdurec", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDCREC", property="pdcrec", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDURLV", property="pdurlv", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDOTQY", property="pdotqy", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPRRC", property="pdprrc", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDAEXP", property="pdaexp", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDACHG", property="pdachg", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDAOPN", property="pdaopn", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDAREC", property="pdarec", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDARLV", property="pdarlv", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDFTN1", property="pdftn1", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDTRLV", property="pdtrlv", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDPROV", property="pdprov", jdbcType=JdbcType.NCHAR),
        @Result(column="PDAMC3", property="pdamc3", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDECST", property="pdecst", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDCSTO", property="pdcsto", jdbcType=JdbcType.NCHAR),
        @Result(column="PDCSMP", property="pdcsmp", jdbcType=JdbcType.NCHAR),
        @Result(column="PDINMG", property="pdinmg", jdbcType=JdbcType.NCHAR),
        @Result(column="PDASN", property="pdasn", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPRGR", property="pdprgr", jdbcType=JdbcType.NCHAR),
        @Result(column="PDCLVL", property="pdclvl", jdbcType=JdbcType.NCHAR),
        @Result(column="PDCATN", property="pdcatn", jdbcType=JdbcType.NCHAR),
        @Result(column="PDDSPR", property="pddspr", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDPTC", property="pdptc", jdbcType=JdbcType.NCHAR),
        @Result(column="PDTX", property="pdtx", jdbcType=JdbcType.NCHAR),
        @Result(column="PDEXR1", property="pdexr1", jdbcType=JdbcType.NCHAR),
        @Result(column="PDTXA1", property="pdtxa1", jdbcType=JdbcType.NCHAR),
        @Result(column="PDATXT", property="pdatxt", jdbcType=JdbcType.NCHAR),
        @Result(column="PDCNID", property="pdcnid", jdbcType=JdbcType.NCHAR),
        @Result(column="PDCDCD", property="pdcdcd", jdbcType=JdbcType.NCHAR),
        @Result(column="PDNTR", property="pdntr", jdbcType=JdbcType.NCHAR),
        @Result(column="PDFRTH", property="pdfrth", jdbcType=JdbcType.NCHAR),
        @Result(column="PDFRTC", property="pdfrtc", jdbcType=JdbcType.NCHAR),
        @Result(column="PDZON", property="pdzon", jdbcType=JdbcType.NCHAR),
        @Result(column="PDFRAT", property="pdfrat", jdbcType=JdbcType.NCHAR),
        @Result(column="PDRATT", property="pdratt", jdbcType=JdbcType.NCHAR),
        @Result(column="PDANBY", property="pdanby", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDANCR", property="pdancr", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDMOT", property="pdmot", jdbcType=JdbcType.NCHAR),
        @Result(column="PDCOT", property="pdcot", jdbcType=JdbcType.NCHAR),
        @Result(column="PDSHCM", property="pdshcm", jdbcType=JdbcType.NCHAR),
        @Result(column="PDSHCN", property="pdshcn", jdbcType=JdbcType.NCHAR),
        @Result(column="PDUOM1", property="pduom1", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPQOR", property="pdpqor", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDUOM2", property="pduom2", jdbcType=JdbcType.NCHAR),
        @Result(column="PDSQOR", property="pdsqor", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDUOM3", property="pduom3", jdbcType=JdbcType.NCHAR),
        @Result(column="PDITWT", property="pditwt", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDWTUM", property="pdwtum", jdbcType=JdbcType.NCHAR),
        @Result(column="PDITVL", property="pditvl", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDVLUM", property="pdvlum", jdbcType=JdbcType.NCHAR),
        @Result(column="PDGLC", property="pdglc", jdbcType=JdbcType.NCHAR),
        @Result(column="PDCTRY", property="pdctry", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDFY", property="pdfy", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDSTTS", property="pdstts", jdbcType=JdbcType.NCHAR),
        @Result(column="PDRCD", property="pdrcd", jdbcType=JdbcType.NCHAR),
        @Result(column="PDFUF1", property="pdfuf1", jdbcType=JdbcType.NCHAR),
        @Result(column="PDFUF2", property="pdfuf2", jdbcType=JdbcType.NCHAR),
        @Result(column="PDGRWT", property="pdgrwt", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDGWUM", property="pdgwum", jdbcType=JdbcType.NCHAR),
        @Result(column="PDLT", property="pdlt", jdbcType=JdbcType.NCHAR),
        @Result(column="PDANI", property="pdani", jdbcType=JdbcType.NCHAR),
        @Result(column="PDAID", property="pdaid", jdbcType=JdbcType.NCHAR),
        @Result(column="PDOMCU", property="pdomcu", jdbcType=JdbcType.NCHAR),
        @Result(column="PDOBJ", property="pdobj", jdbcType=JdbcType.NCHAR),
        @Result(column="PDSUB", property="pdsub", jdbcType=JdbcType.NCHAR),
        @Result(column="PDSBLT", property="pdsblt", jdbcType=JdbcType.NCHAR),
        @Result(column="PDSBL", property="pdsbl", jdbcType=JdbcType.NCHAR),
        @Result(column="PDASID", property="pdasid", jdbcType=JdbcType.NCHAR),
        @Result(column="PDCCMP", property="pdccmp", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDTAG", property="pdtag", jdbcType=JdbcType.NCHAR),
        @Result(column="PDWR01", property="pdwr01", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPL", property="pdpl", jdbcType=JdbcType.NCHAR),
        @Result(column="PDELEV", property="pdelev", jdbcType=JdbcType.NCHAR),
        @Result(column="PDR001", property="pdr001", jdbcType=JdbcType.NCHAR),
        @Result(column="PDRTNR", property="pdrtnr", jdbcType=JdbcType.NCHAR),
        @Result(column="PDLCOD", property="pdlcod", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPURG", property="pdpurg", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPROM", property="pdprom", jdbcType=JdbcType.NCHAR),
        @Result(column="PDFNLP", property="pdfnlp", jdbcType=JdbcType.NCHAR),
        @Result(column="PDAVCH", property="pdavch", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPRPY", property="pdprpy", jdbcType=JdbcType.NCHAR),
        @Result(column="PDUNCD", property="pduncd", jdbcType=JdbcType.NCHAR),
        @Result(column="PDMATY", property="pdmaty", jdbcType=JdbcType.NCHAR),
        @Result(column="PDRTGC", property="pdrtgc", jdbcType=JdbcType.NCHAR),
        @Result(column="PDRCPF", property="pdrcpf", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPS01", property="pdps01", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPS02", property="pdps02", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPS03", property="pdps03", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPS04", property="pdps04", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPS05", property="pdps05", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPS06", property="pdps06", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPS07", property="pdps07", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPS08", property="pdps08", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPS09", property="pdps09", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPS10", property="pdps10", jdbcType=JdbcType.NCHAR),
        @Result(column="PDCRMD", property="pdcrmd", jdbcType=JdbcType.NCHAR),
        @Result(column="PDARTG", property="pdartg", jdbcType=JdbcType.NCHAR),
        @Result(column="PDCORD", property="pdcord", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDCHDT", property="pdchdt", jdbcType=JdbcType.NCHAR),
        @Result(column="PDDOCC", property="pddocc", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDCHLN", property="pdchln", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDCRCD", property="pdcrcd", jdbcType=JdbcType.NCHAR),
        @Result(column="PDCRR", property="pdcrr", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDFRRC", property="pdfrrc", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDFEA", property="pdfea", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDFUC", property="pdfuc", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDFEC", property="pdfec", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDFCHG", property="pdfchg", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDFAP", property="pdfap", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDFREC", property="pdfrec", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDURCD", property="pdurcd", jdbcType=JdbcType.NCHAR),
        @Result(column="PDURDT", property="pdurdt", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDURAT", property="pdurat", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDURAB", property="pdurab", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDURRF", property="pdurrf", jdbcType=JdbcType.NCHAR),
        @Result(column="PDTORG", property="pdtorg", jdbcType=JdbcType.NCHAR),
        @Result(column="PDUSER", property="pduser", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPID", property="pdpid", jdbcType=JdbcType.NCHAR),
        @Result(column="PDJOBN", property="pdjobn", jdbcType=JdbcType.NCHAR),
        @Result(column="PDUPMJ", property="pdupmj", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDTDAY", property="pdtday", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDVR05", property="pdvr05", jdbcType=JdbcType.NCHAR),
        @Result(column="PDVR04", property="pdvr04", jdbcType=JdbcType.NCHAR),
        @Result(column="PDSHPN", property="pdshpn", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDRSHT", property="pdrsht", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDPRJM", property="pdprjm", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDOSFX", property="pdosfx", jdbcType=JdbcType.NCHAR),
        @Result(column="PDMERL", property="pdmerl", jdbcType=JdbcType.NCHAR),
        @Result(column="PDMCLN", property="pdmcln", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDMACT", property="pdmact", jdbcType=JdbcType.NCHAR),
        @Result(column="PDKTLN", property="pdktln", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDFTRL", property="pdftrl", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDDUAL", property="pddual", jdbcType=JdbcType.NCHAR),
        @Result(column="PDDRQT", property="pddrqt", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDDLEJ", property="pddlej", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDCTAM", property="pdctam", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDCPNT", property="pdcpnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDCHT", property="pdcht", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDCHRT", property="pdchrt", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDCHRS", property="pdchrs", jdbcType=JdbcType.NCHAR),
        @Result(column="PDCHMJ", property="pdchmj", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDBCRC", property="pdbcrc", jdbcType=JdbcType.NCHAR),
        @Result(column="PDVR03", property="pdvr03", jdbcType=JdbcType.NCHAR),
        @Result(column="PDLDNM", property="pdldnm", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDMKFR", property="pdmkfr", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDPMTN", property="pdpmtn", jdbcType=JdbcType.NCHAR),
        @Result(column="PDUKID", property="pdukid", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDUNSPSC", property="pdunspsc", jdbcType=JdbcType.NCHAR),
        @Result(column="PDCMDCDE", property="pdcmdcde", jdbcType=JdbcType.NCHAR),
        @Result(column="PDRSFX", property="pdrsfx", jdbcType=JdbcType.NCHAR),
        @Result(column="PDWVID", property="pdwvid", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDCNTRTID", property="pdcntrtid", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDCNTRTDID", property="pdcntrtdid", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDMOADJ", property="pdmoadj", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPODC01", property="pdpodc01", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPODC02", property="pdpodc02", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPODC03", property="pdpodc03", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPODC04", property="pdpodc04", jdbcType=JdbcType.NCHAR),
        @Result(column="PDJBCD", property="pdjbcd", jdbcType=JdbcType.NCHAR),
        @Result(column="PDSRQTY", property="pdsrqty", jdbcType=JdbcType.DECIMAL),
        @Result(column="PDSRUOM", property="pdsruom", jdbcType=JdbcType.NCHAR),
        @Result(column="PDCFGFL", property="pdcfgfl", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPMPN", property="pdpmpn", jdbcType=JdbcType.NCHAR),
        @Result(column="PDPNS", property="pdpns", jdbcType=JdbcType.DECIMAL)
    })
    List<F4311> selectAll();
}