package com.el.client;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-09-02T11:02:42.400+08:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://ws.cmic.el.com/", name = "EmpWsService")
@XmlSeeAlso({ObjectFactory.class})
public interface EmpWsService {

    @WebMethod
    @RequestWrapper(localName = "reqEmps", targetNamespace = "http://ws.cmic.el.com/", className = "com.el.client.ReqEmps")
    @ResponseWrapper(localName = "reqEmpsResponse", targetNamespace = "http://ws.cmic.el.com/", className = "com.el.client.ReqEmpsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<Emp> reqEmps();
}
