package com.el.cmic.mapper.inbound;

import com.el.cfg.domain.F47071;
import com.el.cfg.domain.F47131;
import com.el.cfg.domain.Fe8wms04;
import com.el.cfg.domain.Fe8wms05;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

import java.math.BigDecimal;

/**
 * Created by Vincent on 2016/11/23.
 */
public interface InboundCommonMapper {
    @Select({
            "select",
            "XLPTUT01, XLAA05, XLCA01, XLUPRC, XLUORG, XLLITM, XLPTUT02, XLUSER, XLPID, XLUPMJ, ",
            "XLTDAY, XLKCOO, XLDCTO, XLDOCO, XLLNID, XLDL01, XLDL02, XLDL03, XLAB01, XLAB02, ",
            "XLAB03, XLEV01, XLEV02, XLDL010, XLLOTN, XLLOT1, XLLOT2",
            "from ${tableSchema}.FE8WMS04",
            "where TRIM(XLPTUT01) = #{xlptut01,jdbcType=NCHAR} AND TRIM(XLLITM)=#{xllitm,jdbcType=NCHAR} and trim(xllot1)=#{xllot1,jdbcType=NCHAR}"
    })
    @Results({
            @Result(column="XLPTUT01", property="xlptut01", jdbcType= JdbcType.NCHAR, id=true),
            @Result(column="XLAA05", property="xlaa05", jdbcType=JdbcType.NCHAR),
            @Result(column="XLCA01", property="xlca01", jdbcType=JdbcType.DECIMAL),
            @Result(column="XLUPRC", property="xluprc", jdbcType=JdbcType.DECIMAL),
            @Result(column="XLUORG", property="xluorg", jdbcType=JdbcType.DECIMAL),
            @Result(column="XLLITM", property="xllitm", jdbcType=JdbcType.NCHAR),
            @Result(column="XLPTUT02", property="xlptut02", jdbcType=JdbcType.NCHAR),
            @Result(column="XLUSER", property="xluser", jdbcType=JdbcType.NCHAR),
            @Result(column="XLPID", property="xlpid", jdbcType=JdbcType.NCHAR),
            @Result(column="XLUPMJ", property="xlupmj", jdbcType=JdbcType.DECIMAL),
            @Result(column="XLTDAY", property="xltday", jdbcType=JdbcType.DECIMAL),
            @Result(column="XLKCOO", property="xlkcoo", jdbcType=JdbcType.NCHAR),
            @Result(column="XLDCTO", property="xldcto", jdbcType=JdbcType.NCHAR),
            @Result(column="XLDOCO", property="xldoco", jdbcType=JdbcType.DECIMAL),
            @Result(column="XLLNID", property="xllnid", jdbcType=JdbcType.DECIMAL),
            @Result(column="XLDL01", property="xldl01", jdbcType=JdbcType.NCHAR),
            @Result(column="XLDL02", property="xldl02", jdbcType=JdbcType.NCHAR),
            @Result(column="XLDL03", property="xldl03", jdbcType=JdbcType.NCHAR),
            @Result(column="XLAB01", property="xlab01", jdbcType=JdbcType.DECIMAL),
            @Result(column="XLAB02", property="xlab02", jdbcType=JdbcType.DECIMAL),
            @Result(column="XLAB03", property="xlab03", jdbcType=JdbcType.DECIMAL),
            @Result(column="XLEV01", property="xlev01", jdbcType=JdbcType.NCHAR),
            @Result(column="XLEV02", property="xlev02", jdbcType=JdbcType.NCHAR),
            @Result(column="XLDL010", property="xldl010", jdbcType=JdbcType.NCHAR),
            @Result(column="XLLOTN", property="xllotn", jdbcType=JdbcType.NCHAR),
            @Result(column="XLLOT1", property="xllot1", jdbcType=JdbcType.NCHAR),
            @Result(column="XLLOT2", property="xllot2", jdbcType=JdbcType.NCHAR)
    })
    Fe8wms04 selectByPrimaryKey(@Param("xlptut01") String xlptut01, @Param("xllitm") String xllitm,@Param("xllot1") String xllot1);

    @Select({
            "select",
            "SYEDOC, SYEDCT, SYEKCO, SYEDTY, SYEDSQ, SYEDLN, SYEDST, SYEDFT, SYEDDT, SYEDER, ",
            "SYEDDL, SYEDSP, SYEDBT, SYPNID, SYTPUR, SYRATY, SYKCOO, SYDOCO, SYDCTO, SYSFXO, ",
            "SYMCU, SYOKCO, SYOORN, SYOCTO, SYRKCO, SYRORN, SYRCTO, SYAN8, SYSHAN, SYDRQJ, ",
            "SYTRDJ, SYPDDJ, SYOPDJ, SYADDJ, SYCNDJ, SYPEFJ, SYPPDJ, SYPSDJ, SYVR01, SYVR02, ",
            "SYDEL1, SYDEL2, SYRMK, SYDESC, SYINMG, SYASN, SYPRGP, SYPTC, SYEXR1, SYTXA1, ",
            "SYTXCT, SYATXT, SYHOLD, SYINVC, SYNTR, SYCNID, SYFRTH, SYZON, SYANBY, SYANCR, ",
            "SYMOT, SYCOT, SYRCD, SYFRTC, SYFUF1, SYFUF2, SYOTOT, SYPCRT, SYRTNR, SYWUMD, ",
            "SYVUMD, SYPURG, SYLGCT, SYPROM, SYMATY, SYOSTS, SYAVCH, SYPRPY, SYCRMD, SYPRP5, ",
            "SYARTG, SYCORD, SYCRRM, SYCRCD, SYCRR, SYLNGP, SYFAP, SYORBY, SYTKBY, SYURCD, ",
            "SYURDT, SYURAT, SYURAB, SYURRF, SYTORG, SYUSER, SYPID, SYJOBN, SYUPMJ, SYTDAY, ",
            "SYBCRC, SYDCD, SYDCP, SYNDTP, SYPXDD, SYPXDM, SYDRQT, SYRSHT, SYDVAN, SYVR03, ",
            "SYMKFR, SYGAN8, SYGSHAN, SYGCARS, SYGDVAN, SYGMKFR",
            "from ${tableSchema}.F47071",
            "where trim(SYVR02) = #{wmsdoco,jdbcType=NCHAR}"
    })
    @Results({
            @Result(column="SYEDOC", property="syedoc", jdbcType=JdbcType.DECIMAL, id=true),
            @Result(column="SYEDCT", property="syedct", jdbcType=JdbcType.NCHAR, id=true),
            @Result(column="SYEKCO", property="syekco", jdbcType=JdbcType.NCHAR, id=true),
            @Result(column="SYEDTY", property="syedty", jdbcType=JdbcType.NCHAR),
            @Result(column="SYEDSQ", property="syedsq", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYEDLN", property="syedln", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYEDST", property="syedst", jdbcType=JdbcType.NCHAR),
            @Result(column="SYEDFT", property="syedft", jdbcType=JdbcType.NCHAR),
            @Result(column="SYEDDT", property="syeddt", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYEDER", property="syeder", jdbcType=JdbcType.NCHAR),
            @Result(column="SYEDDL", property="syeddl", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYEDSP", property="syedsp", jdbcType=JdbcType.NCHAR),
            @Result(column="SYEDBT", property="syedbt", jdbcType=JdbcType.NCHAR),
            @Result(column="SYPNID", property="sypnid", jdbcType=JdbcType.NCHAR),
            @Result(column="SYTPUR", property="sytpur", jdbcType=JdbcType.NCHAR),
            @Result(column="SYRATY", property="syraty", jdbcType=JdbcType.NCHAR),
            @Result(column="SYKCOO", property="sykcoo", jdbcType=JdbcType.NCHAR),
            @Result(column="SYDOCO", property="sydoco", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYDCTO", property="sydcto", jdbcType=JdbcType.NCHAR),
            @Result(column="SYSFXO", property="sysfxo", jdbcType=JdbcType.NCHAR),
            @Result(column="SYMCU", property="symcu", jdbcType=JdbcType.NCHAR),
            @Result(column="SYOKCO", property="syokco", jdbcType=JdbcType.NCHAR),
            @Result(column="SYOORN", property="syoorn", jdbcType=JdbcType.NCHAR),
            @Result(column="SYOCTO", property="syocto", jdbcType=JdbcType.NCHAR),
            @Result(column="SYRKCO", property="syrkco", jdbcType=JdbcType.NCHAR),
            @Result(column="SYRORN", property="syrorn", jdbcType=JdbcType.NCHAR),
            @Result(column="SYRCTO", property="syrcto", jdbcType=JdbcType.NCHAR),
            @Result(column="SYAN8", property="syan8", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYSHAN", property="syshan", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYDRQJ", property="sydrqj", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYTRDJ", property="sytrdj", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYPDDJ", property="sypddj", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYOPDJ", property="syopdj", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYADDJ", property="syaddj", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYCNDJ", property="sycndj", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYPEFJ", property="sypefj", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYPPDJ", property="syppdj", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYPSDJ", property="sypsdj", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYVR01", property="syvr01", jdbcType=JdbcType.NCHAR),
            @Result(column="SYVR02", property="syvr02", jdbcType=JdbcType.NCHAR),
            @Result(column="SYDEL1", property="sydel1", jdbcType=JdbcType.NCHAR),
            @Result(column="SYDEL2", property="sydel2", jdbcType=JdbcType.NCHAR),
            @Result(column="SYRMK", property="syrmk", jdbcType=JdbcType.NCHAR),
            @Result(column="SYDESC", property="sydesc", jdbcType=JdbcType.NCHAR),
            @Result(column="SYINMG", property="syinmg", jdbcType=JdbcType.NCHAR),
            @Result(column="SYASN", property="syasn", jdbcType=JdbcType.NCHAR),
            @Result(column="SYPRGP", property="syprgp", jdbcType=JdbcType.NCHAR),
            @Result(column="SYPTC", property="syptc", jdbcType=JdbcType.NCHAR),
            @Result(column="SYEXR1", property="syexr1", jdbcType=JdbcType.NCHAR),
            @Result(column="SYTXA1", property="sytxa1", jdbcType=JdbcType.NCHAR),
            @Result(column="SYTXCT", property="sytxct", jdbcType=JdbcType.NCHAR),
            @Result(column="SYATXT", property="syatxt", jdbcType=JdbcType.NCHAR),
            @Result(column="SYHOLD", property="syhold", jdbcType=JdbcType.NCHAR),
            @Result(column="SYINVC", property="syinvc", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYNTR", property="syntr", jdbcType=JdbcType.NCHAR),
            @Result(column="SYCNID", property="sycnid", jdbcType=JdbcType.NCHAR),
            @Result(column="SYFRTH", property="syfrth", jdbcType=JdbcType.NCHAR),
            @Result(column="SYZON", property="syzon", jdbcType=JdbcType.NCHAR),
            @Result(column="SYANBY", property="syanby", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYANCR", property="syancr", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYMOT", property="symot", jdbcType=JdbcType.NCHAR),
            @Result(column="SYCOT", property="sycot", jdbcType=JdbcType.NCHAR),
            @Result(column="SYRCD", property="syrcd", jdbcType=JdbcType.NCHAR),
            @Result(column="SYFRTC", property="syfrtc", jdbcType=JdbcType.NCHAR),
            @Result(column="SYFUF1", property="syfuf1", jdbcType=JdbcType.NCHAR),
            @Result(column="SYFUF2", property="syfuf2", jdbcType=JdbcType.NCHAR),
            @Result(column="SYOTOT", property="syotot", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYPCRT", property="sypcrt", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYRTNR", property="syrtnr", jdbcType=JdbcType.NCHAR),
            @Result(column="SYWUMD", property="sywumd", jdbcType=JdbcType.NCHAR),
            @Result(column="SYVUMD", property="syvumd", jdbcType=JdbcType.NCHAR),
            @Result(column="SYPURG", property="sypurg", jdbcType=JdbcType.NCHAR),
            @Result(column="SYLGCT", property="sylgct", jdbcType=JdbcType.NCHAR),
            @Result(column="SYPROM", property="syprom", jdbcType=JdbcType.NCHAR),
            @Result(column="SYMATY", property="symaty", jdbcType=JdbcType.NCHAR),
            @Result(column="SYOSTS", property="syosts", jdbcType=JdbcType.NCHAR),
            @Result(column="SYAVCH", property="syavch", jdbcType=JdbcType.NCHAR),
            @Result(column="SYPRPY", property="syprpy", jdbcType=JdbcType.NCHAR),
            @Result(column="SYCRMD", property="sycrmd", jdbcType=JdbcType.NCHAR),
            @Result(column="SYPRP5", property="syprp5", jdbcType=JdbcType.NCHAR),
            @Result(column="SYARTG", property="syartg", jdbcType=JdbcType.NCHAR),
            @Result(column="SYCORD", property="sycord", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYCRRM", property="sycrrm", jdbcType=JdbcType.NCHAR),
            @Result(column="SYCRCD", property="sycrcd", jdbcType=JdbcType.NCHAR),
            @Result(column="SYCRR", property="sycrr", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYLNGP", property="sylngp", jdbcType=JdbcType.NCHAR),
            @Result(column="SYFAP", property="syfap", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYORBY", property="syorby", jdbcType=JdbcType.NCHAR),
            @Result(column="SYTKBY", property="sytkby", jdbcType=JdbcType.NCHAR),
            @Result(column="SYURCD", property="syurcd", jdbcType=JdbcType.NCHAR),
            @Result(column="SYURDT", property="syurdt", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYURAT", property="syurat", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYURAB", property="syurab", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYURRF", property="syurrf", jdbcType=JdbcType.NCHAR),
            @Result(column="SYTORG", property="sytorg", jdbcType=JdbcType.NCHAR),
            @Result(column="SYUSER", property="syuser", jdbcType=JdbcType.NCHAR),
            @Result(column="SYPID", property="sypid", jdbcType=JdbcType.NCHAR),
            @Result(column="SYJOBN", property="syjobn", jdbcType=JdbcType.NCHAR),
            @Result(column="SYUPMJ", property="syupmj", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYTDAY", property="sytday", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYBCRC", property="sybcrc", jdbcType=JdbcType.NCHAR),
            @Result(column="SYDCD", property="sydcd", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYDCP", property="sydcp", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYNDTP", property="syndtp", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYPXDD", property="sypxdd", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYPXDM", property="sypxdm", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYDRQT", property="sydrqt", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYRSHT", property="syrsht", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYDVAN", property="sydvan", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYVR03", property="syvr03", jdbcType=JdbcType.NCHAR),
            @Result(column="SYMKFR", property="symkfr", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYGAN8", property="sygan8", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYGSHAN", property="sygshan", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYGCARS", property="sygcars", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYGDVAN", property="sygdvan", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYGMKFR", property="sygmkfr", jdbcType=JdbcType.DECIMAL)
    })
    F47071 selectByWmsNo(@Param("wmsdoco") String wmsdoco);


    @Select({
            "select",
            "SYEDOC, SYEDCT, SYEKCO, SYEDTY, SYEDSQ, SYEDLN, SYEDST, SYEDFT, SYEDDT, SYEDER, ",
            "SYEDDL, SYEDSP, SYEDBT, SYPNID, SYTPUR, SYKCOO, SYDOCO, SYDCTO, SYSFXO, SYMCU, ",
            "SYCO, SYOKCO, SYOORN, SYOCTO, SYRKCO, SYRORN, SYRCTO, SYAN8, SYSHAN, SYPA8, ",
            "SYDRQJ, SYTRDJ, SYPDDJ, SYOPDJ, SYADDJ, SYCNDJ, SYPEFJ, SYPPDJ, SYPSDJ, SYVR01, ",
            "SYVR02, SYDEL1, SYDEL2, SYINMG, SYPTC, SYRYIN, SYASN, SYPRGP, SYTRDC, SYPCRT, ",
            "SYTXA1, SYEXR1, SYTXCT, SYATXT, SYPRIO, SYBACK, SYSBAL, SYNTR, SYANBY, SYCARS, ",
            "SYMOT, SYCOT, SYROUT, SYSTOP, SYZON, SYCNID, SYFRTH, SYAFT, SYRCD, SYOTOT, SYTOTC, ",
            "SYWUMD, SYVUMD, SYAUTN, SYCACT, SYCEXP, SYCRMD, SYCRRM, SYCRCD, SYCRR, SYLNGP, ",
            "SYFAP, SYFCST, SYORBY, SYTKBY, SYURCD, SYURDT, SYURAT, SYURAB, SYURRF, SYTORG, ",
            "SYUSER, SYPID, SYJOBN, SYUPMJ, SYTDAY, SYIR01, SYIR02, SYIR03, SYIR04, SYIR05, ",
            "SYVR03, SYSOOR, SYPMDT, SYRSDT, SYRQSJ, SYPSTM, SYPDTT, SYOPTT, SYDRQT, SYADTM, ",
            "SYADLJ, SYPBAN, SYITAN, SYFTAN, SYDVAN, SYDOC1, SYDCT4, SYCORD, SYBSC, SYBCRC, ",
            "SYRSHT, SYHOLD, SYFUF1, SYAUFT, SYAUFI, SYOPBO, SYOPTC, SYOPLD, SYOPBK, SYOPSB, ",
            "SYOPPS, SYOPPL, SYOPMS, SYOPSS, SYOPBA, SYOPLL, SYPRAN8, SYPRCIDLN, SYOPPID, ",
            "SYCCIDLN, SYSDATTN, SYSHCCIDLN, SYSPATTN, SYOTIND, SYEXVAR0, SYEXVAR1, SYEXVAR4, ",
            "SYEXVAR5, SYEXVAR6, SYEXVAR7, SYEXVAR12, SYEXVAR13, SYEXNM0, SYEXNM1, SYEXNM2, ",
            "SYEXNMP0, SYEXNMP1, SYEXNMP2, SYEXDT0, SYEXDT1, SYEXDT2, SYGAN8, SYGSHAN, SYGPA8, ",
            "SYGCARS, SYGPBAN, SYGITAN, SYGAUFT, SYGAUFI, SYGFTAN, SYGDVAN, SYGANS8",
            "from ${tableSchema}.F47131",
            "where SYDOCO = #{sydoco,jdbcType=DECIMAL}",
            "and trim(SYKCOO) = #{sykcoo,jdbcType=NCHAR}",
            "and trim(SYDCTO) = #{sydcto,jdbcType=NCHAR}"
    })
    @Results({
            @Result(column="SYEDOC", property="syedoc", jdbcType=JdbcType.DECIMAL, id=true),
            @Result(column="SYEDCT", property="syedct", jdbcType=JdbcType.NCHAR, id=true),
            @Result(column="SYEKCO", property="syekco", jdbcType=JdbcType.NCHAR, id=true),
            @Result(column="SYEDTY", property="syedty", jdbcType=JdbcType.NCHAR),
            @Result(column="SYEDSQ", property="syedsq", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYEDLN", property="syedln", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYEDST", property="syedst", jdbcType=JdbcType.NCHAR),
            @Result(column="SYEDFT", property="syedft", jdbcType=JdbcType.NCHAR),
            @Result(column="SYEDDT", property="syeddt", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYEDER", property="syeder", jdbcType=JdbcType.NCHAR),
            @Result(column="SYEDDL", property="syeddl", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYEDSP", property="syedsp", jdbcType=JdbcType.NCHAR),
            @Result(column="SYEDBT", property="syedbt", jdbcType=JdbcType.NCHAR),
            @Result(column="SYPNID", property="sypnid", jdbcType=JdbcType.NCHAR),
            @Result(column="SYTPUR", property="sytpur", jdbcType=JdbcType.NCHAR),
            @Result(column="SYKCOO", property="sykcoo", jdbcType=JdbcType.NCHAR),
            @Result(column="SYDOCO", property="sydoco", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYDCTO", property="sydcto", jdbcType=JdbcType.NCHAR),
            @Result(column="SYSFXO", property="sysfxo", jdbcType=JdbcType.NCHAR),
            @Result(column="SYMCU", property="symcu", jdbcType=JdbcType.NCHAR),
            @Result(column="SYCO", property="syco", jdbcType=JdbcType.NCHAR),
            @Result(column="SYOKCO", property="syokco", jdbcType=JdbcType.NCHAR),
            @Result(column="SYOORN", property="syoorn", jdbcType=JdbcType.NCHAR),
            @Result(column="SYOCTO", property="syocto", jdbcType=JdbcType.NCHAR),
            @Result(column="SYRKCO", property="syrkco", jdbcType=JdbcType.NCHAR),
            @Result(column="SYRORN", property="syrorn", jdbcType=JdbcType.NCHAR),
            @Result(column="SYRCTO", property="syrcto", jdbcType=JdbcType.NCHAR),
            @Result(column="SYAN8", property="syan8", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYSHAN", property="syshan", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYPA8", property="sypa8", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYDRQJ", property="sydrqj", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYTRDJ", property="sytrdj", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYPDDJ", property="sypddj", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYOPDJ", property="syopdj", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYADDJ", property="syaddj", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYCNDJ", property="sycndj", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYPEFJ", property="sypefj", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYPPDJ", property="syppdj", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYPSDJ", property="sypsdj", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYVR01", property="syvr01", jdbcType=JdbcType.NCHAR),
            @Result(column="SYVR02", property="syvr02", jdbcType=JdbcType.NCHAR),
            @Result(column="SYDEL1", property="sydel1", jdbcType=JdbcType.NCHAR),
            @Result(column="SYDEL2", property="sydel2", jdbcType=JdbcType.NCHAR),
            @Result(column="SYINMG", property="syinmg", jdbcType=JdbcType.NCHAR),
            @Result(column="SYPTC", property="syptc", jdbcType=JdbcType.NCHAR),
            @Result(column="SYRYIN", property="syryin", jdbcType=JdbcType.NCHAR),
            @Result(column="SYASN", property="syasn", jdbcType=JdbcType.NCHAR),
            @Result(column="SYPRGP", property="syprgp", jdbcType=JdbcType.NCHAR),
            @Result(column="SYTRDC", property="sytrdc", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYPCRT", property="sypcrt", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYTXA1", property="sytxa1", jdbcType=JdbcType.NCHAR),
            @Result(column="SYEXR1", property="syexr1", jdbcType=JdbcType.NCHAR),
            @Result(column="SYTXCT", property="sytxct", jdbcType=JdbcType.NCHAR),
            @Result(column="SYATXT", property="syatxt", jdbcType=JdbcType.NCHAR),
            @Result(column="SYPRIO", property="syprio", jdbcType=JdbcType.NCHAR),
            @Result(column="SYBACK", property="syback", jdbcType=JdbcType.NCHAR),
            @Result(column="SYSBAL", property="sysbal", jdbcType=JdbcType.NCHAR),
            @Result(column="SYNTR", property="syntr", jdbcType=JdbcType.NCHAR),
            @Result(column="SYANBY", property="syanby", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYCARS", property="sycars", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYMOT", property="symot", jdbcType=JdbcType.NCHAR),
            @Result(column="SYCOT", property="sycot", jdbcType=JdbcType.NCHAR),
            @Result(column="SYROUT", property="syrout", jdbcType=JdbcType.NCHAR),
            @Result(column="SYSTOP", property="systop", jdbcType=JdbcType.NCHAR),
            @Result(column="SYZON", property="syzon", jdbcType=JdbcType.NCHAR),
            @Result(column="SYCNID", property="sycnid", jdbcType=JdbcType.NCHAR),
            @Result(column="SYFRTH", property="syfrth", jdbcType=JdbcType.NCHAR),
            @Result(column="SYAFT", property="syaft", jdbcType=JdbcType.NCHAR),
            @Result(column="SYRCD", property="syrcd", jdbcType=JdbcType.NCHAR),
            @Result(column="SYOTOT", property="syotot", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYTOTC", property="sytotc", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYWUMD", property="sywumd", jdbcType=JdbcType.NCHAR),
            @Result(column="SYVUMD", property="syvumd", jdbcType=JdbcType.NCHAR),
            @Result(column="SYAUTN", property="syautn", jdbcType=JdbcType.NCHAR),
            @Result(column="SYCACT", property="sycact", jdbcType=JdbcType.NCHAR),
            @Result(column="SYCEXP", property="sycexp", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYCRMD", property="sycrmd", jdbcType=JdbcType.NCHAR),
            @Result(column="SYCRRM", property="sycrrm", jdbcType=JdbcType.NCHAR),
            @Result(column="SYCRCD", property="sycrcd", jdbcType=JdbcType.NCHAR),
            @Result(column="SYCRR", property="sycrr", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYLNGP", property="sylngp", jdbcType=JdbcType.NCHAR),
            @Result(column="SYFAP", property="syfap", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYFCST", property="syfcst", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYORBY", property="syorby", jdbcType=JdbcType.NCHAR),
            @Result(column="SYTKBY", property="sytkby", jdbcType=JdbcType.NCHAR),
            @Result(column="SYURCD", property="syurcd", jdbcType=JdbcType.NCHAR),
            @Result(column="SYURDT", property="syurdt", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYURAT", property="syurat", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYURAB", property="syurab", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYURRF", property="syurrf", jdbcType=JdbcType.NCHAR),
            @Result(column="SYTORG", property="sytorg", jdbcType=JdbcType.NCHAR),
            @Result(column="SYUSER", property="syuser", jdbcType=JdbcType.NCHAR),
            @Result(column="SYPID", property="sypid", jdbcType=JdbcType.NCHAR),
            @Result(column="SYJOBN", property="syjobn", jdbcType=JdbcType.NCHAR),
            @Result(column="SYUPMJ", property="syupmj", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYTDAY", property="sytday", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYIR01", property="syir01", jdbcType=JdbcType.NCHAR),
            @Result(column="SYIR02", property="syir02", jdbcType=JdbcType.NCHAR),
            @Result(column="SYIR03", property="syir03", jdbcType=JdbcType.NCHAR),
            @Result(column="SYIR04", property="syir04", jdbcType=JdbcType.NCHAR),
            @Result(column="SYIR05", property="syir05", jdbcType=JdbcType.NCHAR),
            @Result(column="SYVR03", property="syvr03", jdbcType=JdbcType.NCHAR),
            @Result(column="SYSOOR", property="sysoor", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYPMDT", property="sypmdt", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYRSDT", property="syrsdt", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYRQSJ", property="syrqsj", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYPSTM", property="sypstm", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYPDTT", property="sypdtt", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYOPTT", property="syoptt", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYDRQT", property="sydrqt", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYADTM", property="syadtm", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYADLJ", property="syadlj", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYPBAN", property="sypban", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYITAN", property="syitan", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYFTAN", property="syftan", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYDVAN", property="sydvan", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYDOC1", property="sydoc1", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYDCT4", property="sydct4", jdbcType=JdbcType.NCHAR),
            @Result(column="SYCORD", property="sycord", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYBSC", property="sybsc", jdbcType=JdbcType.NCHAR),
            @Result(column="SYBCRC", property="sybcrc", jdbcType=JdbcType.NCHAR),
            @Result(column="SYRSHT", property="syrsht", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYHOLD", property="syhold", jdbcType=JdbcType.NCHAR),
            @Result(column="SYFUF1", property="syfuf1", jdbcType=JdbcType.NCHAR),
            @Result(column="SYAUFT", property="syauft", jdbcType=JdbcType.NCHAR),
            @Result(column="SYAUFI", property="syaufi", jdbcType=JdbcType.NCHAR),
            @Result(column="SYOPBO", property="syopbo", jdbcType=JdbcType.NCHAR),
            @Result(column="SYOPTC", property="syoptc", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYOPLD", property="syopld", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYOPBK", property="syopbk", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYOPSB", property="syopsb", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYOPPS", property="syopps", jdbcType=JdbcType.NCHAR),
            @Result(column="SYOPPL", property="syoppl", jdbcType=JdbcType.NCHAR),
            @Result(column="SYOPMS", property="syopms", jdbcType=JdbcType.NCHAR),
            @Result(column="SYOPSS", property="syopss", jdbcType=JdbcType.NCHAR),
            @Result(column="SYOPBA", property="syopba", jdbcType=JdbcType.NCHAR),
            @Result(column="SYOPLL", property="syopll", jdbcType=JdbcType.NCHAR),
            @Result(column="SYPRAN8", property="sypran8", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYPRCIDLN", property="syprcidln", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYOPPID", property="syoppid", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYCCIDLN", property="syccidln", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYSDATTN", property="sysdattn", jdbcType=JdbcType.NCHAR),
            @Result(column="SYSHCCIDLN", property="syshccidln", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYSPATTN", property="syspattn", jdbcType=JdbcType.NCHAR),
            @Result(column="SYOTIND", property="syotind", jdbcType=JdbcType.NCHAR),
            @Result(column="SYEXVAR0", property="syexvar0", jdbcType=JdbcType.NCHAR),
            @Result(column="SYEXVAR1", property="syexvar1", jdbcType=JdbcType.NCHAR),
            @Result(column="SYEXVAR4", property="syexvar4", jdbcType=JdbcType.NCHAR),
            @Result(column="SYEXVAR5", property="syexvar5", jdbcType=JdbcType.NCHAR),
            @Result(column="SYEXVAR6", property="syexvar6", jdbcType=JdbcType.NCHAR),
            @Result(column="SYEXVAR7", property="syexvar7", jdbcType=JdbcType.NCHAR),
            @Result(column="SYEXVAR12", property="syexvar12", jdbcType=JdbcType.NCHAR),
            @Result(column="SYEXVAR13", property="syexvar13", jdbcType=JdbcType.NCHAR),
            @Result(column="SYEXNM0", property="syexnm0", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYEXNM1", property="syexnm1", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYEXNM2", property="syexnm2", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYEXNMP0", property="syexnmp0", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYEXNMP1", property="syexnmp1", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYEXNMP2", property="syexnmp2", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYEXDT0", property="syexdt0", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="SYEXDT1", property="syexdt1", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="SYEXDT2", property="syexdt2", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="SYGAN8", property="sygan8", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYGSHAN", property="sygshan", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYGPA8", property="sygpa8", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYGCARS", property="sygcars", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYGPBAN", property="sygpban", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYGITAN", property="sygitan", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYGAUFT", property="sygauft", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYGAUFI", property="sygaufi", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYGFTAN", property="sygftan", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYGDVAN", property="sygdvan", jdbcType=JdbcType.DECIMAL),
            @Result(column="SYGANS8", property="sygans8", jdbcType=JdbcType.DECIMAL)
    })
    F47131 selectF47131ByDoco(@Param("sydoco") BigDecimal sydoco, @Param("sykcoo") String sykcoo, @Param("sydcto") String sydcto);

    @Select({
            "select",
            "XLKCOO, XLLNID, XLMCU, XLCA01, XLDCTO, XLDOCO, XLCF01, XLLITM, XLPTUT01, XLPTUT02, ",
            "XLCA02, XLUPRC, XLPRRC, XLAMC3, XLTRDJ, XLE8NAME, XLPEFJ, XLPSDJ, XLGRWT, XLDL010, ",
            "XLDL01, XLDL02, XLDL03, XLAB01, XLAB02, XLAB03, XLEV01, XLEV02, XLUSER, XLPID, ",
            "XLUPMJ, XLTDAY, XLAOD, XLDS50",
            "from ${tableSchema}.FE8WMS05",
            "where XLDOCO=#{xldoco,jdbcType=DECIMAL}",
            " and XLKCOO = #{xlkcoo,jdbcType=NCHAR}",
            "and XLDCTO = #{xldcto,jdbcType=NCHAR}"
    })
    @Results({
            @Result(column="XLKCOO", property="xlkcoo", jdbcType=JdbcType.NCHAR, id=true),
            @Result(column="XLLNID", property="xllnid", jdbcType=JdbcType.DECIMAL, id=true),
            @Result(column="XLMCU", property="xlmcu", jdbcType=JdbcType.NCHAR),
            @Result(column="XLCA01", property="xlca01", jdbcType=JdbcType.DECIMAL),
            @Result(column="XLDCTO", property="xldcto", jdbcType=JdbcType.NCHAR),
            @Result(column="XLDOCO", property="xldoco", jdbcType=JdbcType.DECIMAL),
            @Result(column="XLCF01", property="xlcf01", jdbcType=JdbcType.NCHAR),
            @Result(column="XLLITM", property="xllitm", jdbcType=JdbcType.NCHAR),
            @Result(column="XLPTUT01", property="xlptut01", jdbcType=JdbcType.NCHAR),
            @Result(column="XLPTUT02", property="xlptut02", jdbcType=JdbcType.NCHAR),
            @Result(column="XLCA02", property="xlca02", jdbcType=JdbcType.DECIMAL),
            @Result(column="XLUPRC", property="xluprc", jdbcType=JdbcType.DECIMAL),
            @Result(column="XLPRRC", property="xlprrc", jdbcType=JdbcType.DECIMAL),
            @Result(column="XLAMC3", property="xlamc3", jdbcType=JdbcType.DECIMAL),
            @Result(column="XLTRDJ", property="xltrdj", jdbcType=JdbcType.DECIMAL),
            @Result(column="XLE8NAME", property="xle8name", jdbcType=JdbcType.NCHAR),
            @Result(column="XLPEFJ", property="xlpefj", jdbcType=JdbcType.DECIMAL),
            @Result(column="XLPSDJ", property="xlpsdj", jdbcType=JdbcType.DECIMAL),
            @Result(column="XLGRWT", property="xlgrwt", jdbcType=JdbcType.DECIMAL),
            @Result(column="XLDL010", property="xldl010", jdbcType=JdbcType.NCHAR),
            @Result(column="XLDL01", property="xldl01", jdbcType=JdbcType.NCHAR),
            @Result(column="XLDL02", property="xldl02", jdbcType=JdbcType.NCHAR),
            @Result(column="XLDL03", property="xldl03", jdbcType=JdbcType.NCHAR),
            @Result(column="XLAB01", property="xlab01", jdbcType=JdbcType.DECIMAL),
            @Result(column="XLAB02", property="xlab02", jdbcType=JdbcType.DECIMAL),
            @Result(column="XLAB03", property="xlab03", jdbcType=JdbcType.DECIMAL),
            @Result(column="XLEV01", property="xlev01", jdbcType=JdbcType.NCHAR),
            @Result(column="XLEV02", property="xlev02", jdbcType=JdbcType.NCHAR),
            @Result(column="XLUSER", property="xluser", jdbcType=JdbcType.NCHAR),
            @Result(column="XLPID", property="xlpid", jdbcType=JdbcType.NCHAR),
            @Result(column="XLUPMJ", property="xlupmj", jdbcType=JdbcType.DECIMAL),
            @Result(column="XLTDAY", property="xltday", jdbcType=JdbcType.DECIMAL),
            @Result(column="XLAOD", property="xlaod", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="XLDS50", property="xlds50", jdbcType=JdbcType.NCHAR)
    })
    Fe8wms05 selectFe8wms05ByDoco(@Param("xldoco")BigDecimal xldoco,@Param("xlkcoo") String xlkcoo, @Param("xldcto") String xldcto);
}
