package com.el.cfg.mapper;

import com.el.cfg.domain.F4101;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

public interface F4101Mapper4 {
    @Select({
        "select",
        "IMITM, IMLITM, IMAITM, IMDSC1, IMDSC2, IMSRTX, IMALN, IMSRP1, IMSRP2, IMSRP3, ",
        "IMSRP4, IMSRP5, IMSRP6, IMSRP7, IMSRP8, IMSRP9, IMSRP0, IMPRP1, IMPRP2, IMPRP3, ",
        "IMPRP4, IMPRP5, IMPRP6, IMPRP7, IMPRP8, IMPRP9, IMPRP0, IMCDCD, IMPDGR, IMDSGP, ",
        "IMPRGR, IMRPRC, IMORPR, IMBUYR, IMDRAW, IMRVNO, IMDSZE, IMVCUD, IMCARS, IMCARP, ",
        "IMSHCN, IMSHCM,	 IMUOM1, IMUOM2, IMUOM3, IMUOM4, IMUOM6, IMUOM8, IMUOM9, IMUWUM, ",
        "IMUVM1, IMSUTM, IMUMVW, IMCYCL, IMGLPT, IMPLEV, IMPPLV, IMCLEV, IMPRPO, IMCKAV, ",
        "IMBPFG, IMSRCE, IMOT1Y, IMOT2Y, IMSTDP, IMFRMP, IMTHRP, IMSTDG, IMFRGD, IMTHGD, ",
        "IMCOTY, IMSTKT, IMLNTY, IMCONT, IMBACK, IMIFLA, IMTFLA, IMINMG, IMABCS, IMABCM, ",
        "IMABCI, IMOVR, IMWARR, IMCMCG, IMSRNR, IMPMTH, IMFIFO, IMLOTS, IMSLD, IMANPL, ",
        "IMMPST, IMPCTM, IMMMPC, IMPTSC, IMSNS, IMLTLV, IMLTMF, IMLTCM, IMOPC, IMOPV, ",
        "IMACQ, IMMLQ, IMLTPU, IMMPSP, IMMRPP, IMITC, IMORDW, IMMTF1, IMMTF2, IMMTF3, ",
        "IMMTF4, IMMTF5, IMEXPD, IMDEFD, IMSFLT, IMMAKE, IMCOBY, IMLLX, IMCMGL, IMCOMH, ",
        "IMURCD, IMURDT, IMURAT, IMURAB, IMURRF, IMUSER, IMPID, IMJOBN, IMUPMJ, IMTDAY, ",
        "IMUPCN, IMSCC0, IMUMUP, IMUMDF, IMUMS0, IMUMS1, IMUMS2, IMUMS3, IMUMS4, IMUMS5, ",
        "IMUMS6, IMUMS7, IMUMS8, IMPOC, IMAVRT, IMEQTY, IMWTRQ, IMTMPL, IMSEG1, IMSEG2, ",
        "IMSEG3, IMSEG4, IMSEG5, IMSEG6, IMSEG7, IMSEG8, IMSEG9, IMSEG0, IMMIC, IMAING, ",
        "IMBBDD, IMCMDM, IMLECM, IMLEDD, IMPEFD, IMSBDD, IMU1DD, IMU2DD, IMU3DD, IMU4DD, ",
        "IMU5DD, IMDLTL, IMDPPO, IMDUAL, IMXDCK, IMLAF, IMLTFM, IMRWLA, IMLNPA, IMLOTC, ",
        "IMAPSC, IMAUOM, IMCONB, IMGCMP, IMPRI1, IMPRI2, IMASHL, IMVMINV, IMCMETH, IMEXPI, ",
        "IMOPTH, IMCUTH, IMUMTH, IMLMFG, IMLINE, IMDFTPCT, IMKBIT, IMDFENDITM, IMKANEXLL, ",
        "IMSCPSELL, IMMOPTH, IMMCUTH, IMCUMTH, IMATPRN, IMATPCA, IMATPAC, IMCOORE, IMVCPFC, ",
        "IMPNYN",
        "from F4101",
        "where IMITM = #{imitm,jdbcType=DECIMAL}"
    })
    @Results({
        @Result(column="IMITM", property="imitm", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="IMLITM", property="imlitm", jdbcType=JdbcType.NCHAR),
        @Result(column="IMAITM", property="imaitm", jdbcType=JdbcType.NCHAR),
        @Result(column="IMDSC1", property="imdsc1", jdbcType=JdbcType.NCHAR),
        @Result(column="IMDSC2", property="imdsc2", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSRTX", property="imsrtx", jdbcType=JdbcType.NCHAR),
        @Result(column="IMALN", property="imaln", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSRP1", property="imsrp1", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSRP2", property="imsrp2", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSRP3", property="imsrp3", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSRP4", property="imsrp4", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSRP5", property="imsrp5", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSRP6", property="imsrp6", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSRP7", property="imsrp7", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSRP8", property="imsrp8", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSRP9", property="imsrp9", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSRP0", property="imsrp0", jdbcType=JdbcType.NCHAR),
        @Result(column="IMPRP1", property="imprp1", jdbcType=JdbcType.NCHAR),
        @Result(column="IMPRP2", property="imprp2", jdbcType=JdbcType.NCHAR),
        @Result(column="IMPRP3", property="imprp3", jdbcType=JdbcType.NCHAR),
        @Result(column="IMPRP4", property="imprp4", jdbcType=JdbcType.NCHAR),
        @Result(column="IMPRP5", property="imprp5", jdbcType=JdbcType.NCHAR),
        @Result(column="IMPRP6", property="imprp6", jdbcType=JdbcType.NCHAR),
        @Result(column="IMPRP7", property="imprp7", jdbcType=JdbcType.NCHAR),
        @Result(column="IMPRP8", property="imprp8", jdbcType=JdbcType.NCHAR),
        @Result(column="IMPRP9", property="imprp9", jdbcType=JdbcType.NCHAR),
        @Result(column="IMPRP0", property="imprp0", jdbcType=JdbcType.NCHAR),
        @Result(column="IMCDCD", property="imcdcd", jdbcType=JdbcType.NCHAR),
        @Result(column="IMPDGR", property="impdgr", jdbcType=JdbcType.NCHAR),
        @Result(column="IMDSGP", property="imdsgp", jdbcType=JdbcType.NCHAR),
        @Result(column="IMPRGR", property="imprgr", jdbcType=JdbcType.NCHAR),
        @Result(column="IMRPRC", property="imrprc", jdbcType=JdbcType.NCHAR),
        @Result(column="IMORPR", property="imorpr", jdbcType=JdbcType.NCHAR),
        @Result(column="IMBUYR", property="imbuyr", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMDRAW", property="imdraw", jdbcType=JdbcType.NCHAR),
        @Result(column="IMRVNO", property="imrvno", jdbcType=JdbcType.NCHAR),
        @Result(column="IMDSZE", property="imdsze", jdbcType=JdbcType.NCHAR),
        @Result(column="IMVCUD", property="imvcud", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMCARS", property="imcars", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMCARP", property="imcarp", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMSHCN", property="imshcn", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSHCM", property="imshcm", jdbcType=JdbcType.NCHAR),
        @Result(column="IMUOM1", property="imuom1", jdbcType=JdbcType.NCHAR),
        @Result(column="IMUOM2", property="imuom2", jdbcType=JdbcType.NCHAR),
        @Result(column="IMUOM3", property="imuom3", jdbcType=JdbcType.NCHAR),
        @Result(column="IMUOM4", property="imuom4", jdbcType=JdbcType.NCHAR),
        @Result(column="IMUOM6", property="imuom6", jdbcType=JdbcType.NCHAR),
        @Result(column="IMUOM8", property="imuom8", jdbcType=JdbcType.NCHAR),
        @Result(column="IMUOM9", property="imuom9", jdbcType=JdbcType.NCHAR),
        @Result(column="IMUWUM", property="imuwum", jdbcType=JdbcType.NCHAR),
        @Result(column="IMUVM1", property="imuvm1", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSUTM", property="imsutm", jdbcType=JdbcType.NCHAR),
        @Result(column="IMUMVW", property="imumvw", jdbcType=JdbcType.NCHAR),
        @Result(column="IMCYCL", property="imcycl", jdbcType=JdbcType.NCHAR),
        @Result(column="IMGLPT", property="imglpt", jdbcType=JdbcType.NCHAR),
        @Result(column="IMPLEV", property="implev", jdbcType=JdbcType.NCHAR),
        @Result(column="IMPPLV", property="impplv", jdbcType=JdbcType.NCHAR),
        @Result(column="IMCLEV", property="imclev", jdbcType=JdbcType.NCHAR),
        @Result(column="IMPRPO", property="imprpo", jdbcType=JdbcType.NCHAR),
        @Result(column="IMCKAV", property="imckav", jdbcType=JdbcType.NCHAR),
        @Result(column="IMBPFG", property="imbpfg", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSRCE", property="imsrce", jdbcType=JdbcType.NCHAR),
        @Result(column="IMOT1Y", property="imot1y", jdbcType=JdbcType.NCHAR),
        @Result(column="IMOT2Y", property="imot2y", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSTDP", property="imstdp", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMFRMP", property="imfrmp", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMTHRP", property="imthrp", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMSTDG", property="imstdg", jdbcType=JdbcType.NCHAR),
        @Result(column="IMFRGD", property="imfrgd", jdbcType=JdbcType.NCHAR),
        @Result(column="IMTHGD", property="imthgd", jdbcType=JdbcType.NCHAR),
        @Result(column="IMCOTY", property="imcoty", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSTKT", property="imstkt", jdbcType=JdbcType.NCHAR),
        @Result(column="IMLNTY", property="imlnty", jdbcType=JdbcType.NCHAR),
        @Result(column="IMCONT", property="imcont", jdbcType=JdbcType.NCHAR),
        @Result(column="IMBACK", property="imback", jdbcType=JdbcType.NCHAR),
        @Result(column="IMIFLA", property="imifla", jdbcType=JdbcType.NCHAR),
        @Result(column="IMTFLA", property="imtfla", jdbcType=JdbcType.NCHAR),
        @Result(column="IMINMG", property="iminmg", jdbcType=JdbcType.NCHAR),
        @Result(column="IMABCS", property="imabcs", jdbcType=JdbcType.NCHAR),
        @Result(column="IMABCM", property="imabcm", jdbcType=JdbcType.NCHAR),
        @Result(column="IMABCI", property="imabci", jdbcType=JdbcType.NCHAR),
        @Result(column="IMOVR", property="imovr", jdbcType=JdbcType.NCHAR),
        @Result(column="IMWARR", property="imwarr", jdbcType=JdbcType.NCHAR),
        @Result(column="IMCMCG", property="imcmcg", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSRNR", property="imsrnr", jdbcType=JdbcType.NCHAR),
        @Result(column="IMPMTH", property="impmth", jdbcType=JdbcType.NCHAR),
        @Result(column="IMFIFO", property="imfifo", jdbcType=JdbcType.NCHAR),
        @Result(column="IMLOTS", property="imlots", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSLD", property="imsld", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMANPL", property="imanpl", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMMPST", property="immpst", jdbcType=JdbcType.NCHAR),
        @Result(column="IMPCTM", property="impctm", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMMMPC", property="immmpc", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMPTSC", property="imptsc", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSNS", property="imsns", jdbcType=JdbcType.NCHAR),
        @Result(column="IMLTLV", property="imltlv", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMLTMF", property="imltmf", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMLTCM", property="imltcm", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMOPC", property="imopc", jdbcType=JdbcType.NCHAR),
        @Result(column="IMOPV", property="imopv", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMACQ", property="imacq", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMMLQ", property="immlq", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMLTPU", property="imltpu", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMMPSP", property="immpsp", jdbcType=JdbcType.NCHAR),
        @Result(column="IMMRPP", property="immrpp", jdbcType=JdbcType.NCHAR),
        @Result(column="IMITC", property="imitc", jdbcType=JdbcType.NCHAR),
        @Result(column="IMORDW", property="imordw", jdbcType=JdbcType.NCHAR),
        @Result(column="IMMTF1", property="immtf1", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMMTF2", property="immtf2", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMMTF3", property="immtf3", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMMTF4", property="immtf4", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMMTF5", property="immtf5", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMEXPD", property="imexpd", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMDEFD", property="imdefd", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMSFLT", property="imsflt", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMMAKE", property="immake", jdbcType=JdbcType.NCHAR),
        @Result(column="IMCOBY", property="imcoby", jdbcType=JdbcType.NCHAR),
        @Result(column="IMLLX", property="imllx", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMCMGL", property="imcmgl", jdbcType=JdbcType.NCHAR),
        @Result(column="IMCOMH", property="imcomh", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMURCD", property="imurcd", jdbcType=JdbcType.NCHAR),
        @Result(column="IMURDT", property="imurdt", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMURAT", property="imurat", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMURAB", property="imurab", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMURRF", property="imurrf", jdbcType=JdbcType.NCHAR),
        @Result(column="IMUSER", property="imuser", jdbcType=JdbcType.NCHAR),
        @Result(column="IMPID", property="impid", jdbcType=JdbcType.NCHAR),
        @Result(column="IMJOBN", property="imjobn", jdbcType=JdbcType.NCHAR),
        @Result(column="IMUPMJ", property="imupmj", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMTDAY", property="imtday", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMUPCN", property="imupcn", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSCC0", property="imscc0", jdbcType=JdbcType.NCHAR),
        @Result(column="IMUMUP", property="imumup", jdbcType=JdbcType.NCHAR),
        @Result(column="IMUMDF", property="imumdf", jdbcType=JdbcType.NCHAR),
        @Result(column="IMUMS0", property="imums0", jdbcType=JdbcType.NCHAR),
        @Result(column="IMUMS1", property="imums1", jdbcType=JdbcType.NCHAR),
        @Result(column="IMUMS2", property="imums2", jdbcType=JdbcType.NCHAR),
        @Result(column="IMUMS3", property="imums3", jdbcType=JdbcType.NCHAR),
        @Result(column="IMUMS4", property="imums4", jdbcType=JdbcType.NCHAR),
        @Result(column="IMUMS5", property="imums5", jdbcType=JdbcType.NCHAR),
        @Result(column="IMUMS6", property="imums6", jdbcType=JdbcType.NCHAR),
        @Result(column="IMUMS7", property="imums7", jdbcType=JdbcType.NCHAR),
        @Result(column="IMUMS8", property="imums8", jdbcType=JdbcType.NCHAR),
        @Result(column="IMPOC", property="impoc", jdbcType=JdbcType.NCHAR),
        @Result(column="IMAVRT", property="imavrt", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMEQTY", property="imeqty", jdbcType=JdbcType.NCHAR),
        @Result(column="IMWTRQ", property="imwtrq", jdbcType=JdbcType.NCHAR),
        @Result(column="IMTMPL", property="imtmpl", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSEG1", property="imseg1", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSEG2", property="imseg2", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSEG3", property="imseg3", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSEG4", property="imseg4", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSEG5", property="imseg5", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSEG6", property="imseg6", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSEG7", property="imseg7", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSEG8", property="imseg8", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSEG9", property="imseg9", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSEG0", property="imseg0", jdbcType=JdbcType.NCHAR),
        @Result(column="IMMIC", property="immic", jdbcType=JdbcType.NCHAR),
        @Result(column="IMAING", property="imaing", jdbcType=JdbcType.NCHAR),
        @Result(column="IMBBDD", property="imbbdd", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMCMDM", property="imcmdm", jdbcType=JdbcType.NCHAR),
        @Result(column="IMLECM", property="imlecm", jdbcType=JdbcType.NCHAR),
        @Result(column="IMLEDD", property="imledd", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMPEFD", property="impefd", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMSBDD", property="imsbdd", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMU1DD", property="imu1dd", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMU2DD", property="imu2dd", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMU3DD", property="imu3dd", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMU4DD", property="imu4dd", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMU5DD", property="imu5dd", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMDLTL", property="imdltl", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMDPPO", property="imdppo", jdbcType=JdbcType.NCHAR),
        @Result(column="IMDUAL", property="imdual", jdbcType=JdbcType.NCHAR),
        @Result(column="IMXDCK", property="imxdck", jdbcType=JdbcType.NCHAR),
        @Result(column="IMLAF", property="imlaf", jdbcType=JdbcType.NCHAR),
        @Result(column="IMLTFM", property="imltfm", jdbcType=JdbcType.NCHAR),
        @Result(column="IMRWLA", property="imrwla", jdbcType=JdbcType.NCHAR),
        @Result(column="IMLNPA", property="imlnpa", jdbcType=JdbcType.NCHAR),
        @Result(column="IMLOTC", property="imlotc", jdbcType=JdbcType.NCHAR),
        @Result(column="IMAPSC", property="imapsc", jdbcType=JdbcType.NCHAR),
        @Result(column="IMAUOM", property="imauom", jdbcType=JdbcType.NCHAR),
        @Result(column="IMCONB", property="imconb", jdbcType=JdbcType.NCHAR),
        @Result(column="IMGCMP", property="imgcmp", jdbcType=JdbcType.NCHAR),
        @Result(column="IMPRI1", property="impri1", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMPRI2", property="impri2", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMASHL", property="imashl", jdbcType=JdbcType.NCHAR),
        @Result(column="IMVMINV", property="imvminv", jdbcType=JdbcType.NCHAR),
        @Result(column="IMCMETH", property="imcmeth", jdbcType=JdbcType.NCHAR),
        @Result(column="IMEXPI", property="imexpi", jdbcType=JdbcType.NCHAR),
        @Result(column="IMOPTH", property="imopth", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMCUTH", property="imcuth", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMUMTH", property="imumth", jdbcType=JdbcType.NCHAR),
        @Result(column="IMLMFG", property="imlmfg", jdbcType=JdbcType.NCHAR),
        @Result(column="IMLINE", property="imline", jdbcType=JdbcType.NCHAR),
        @Result(column="IMDFTPCT", property="imdftpct", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMKBIT", property="imkbit", jdbcType=JdbcType.NCHAR),
        @Result(column="IMDFENDITM", property="imdfenditm", jdbcType=JdbcType.NCHAR),
        @Result(column="IMKANEXLL", property="imkanexll", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSCPSELL", property="imscpsell", jdbcType=JdbcType.NCHAR),
        @Result(column="IMMOPTH", property="immopth", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMMCUTH", property="immcuth", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMCUMTH", property="imcumth", jdbcType=JdbcType.NCHAR),
        @Result(column="IMATPRN", property="imatprn", jdbcType=JdbcType.NCHAR),
        @Result(column="IMATPCA", property="imatpca", jdbcType=JdbcType.NCHAR),
        @Result(column="IMATPAC", property="imatpac", jdbcType=JdbcType.NCHAR),
        @Result(column="IMCOORE", property="imcoore", jdbcType=JdbcType.NCHAR),
        @Result(column="IMVCPFC", property="imvcpfc", jdbcType=JdbcType.NCHAR),
        @Result(column="IMPNYN", property="impnyn", jdbcType=JdbcType.NCHAR)
    })
    F4101 selectByPrimaryKey(BigDecimal imitm);

    @Select({
        "select",
        "IMITM, IMLITM, IMAITM, IMDSC1, IMDSC2, IMSRTX, IMALN, IMSRP1, IMSRP2, IMSRP3, ",
        "IMSRP4, IMSRP5, IMSRP6, IMSRP7, IMSRP8, IMSRP9, IMSRP0, IMPRP1, IMPRP2, IMPRP3, ",
        "IMPRP4, IMPRP5, IMPRP6, IMPRP7, IMPRP8, IMPRP9, IMPRP0, IMCDCD, IMPDGR, IMDSGP, ",
        "IMPRGR, IMRPRC, IMORPR, IMBUYR, IMDRAW, IMRVNO, IMDSZE, IMVCUD, IMCARS, IMCARP, ",
        "IMSHCN, IMSHCM, IMUOM1, IMUOM2, IMUOM3, IMUOM4, IMUOM6, IMUOM8, IMUOM9, IMUWUM, ",
        "IMUVM1, IMSUTM, IMUMVW, IMCYCL, IMGLPT, IMPLEV, IMPPLV, IMCLEV, IMPRPO, IMCKAV, ",
        "IMBPFG, IMSRCE, IMOT1Y, IMOT2Y, IMSTDP, IMFRMP, IMTHRP, IMSTDG, IMFRGD, IMTHGD, ",
        "IMCOTY, IMSTKT, IMLNTY, IMCONT, IMBACK, IMIFLA, IMTFLA, IMINMG, IMABCS, IMABCM, ",
        "IMABCI, IMOVR, IMWARR, IMCMCG, IMSRNR, IMPMTH, IMFIFO, IMLOTS, IMSLD, IMANPL, ",
        "IMMPST, IMPCTM, IMMMPC, IMPTSC, IMSNS, IMLTLV, IMLTMF, IMLTCM, IMOPC, IMOPV, ",
        "IMACQ, IMMLQ, IMLTPU, IMMPSP, IMMRPP, IMITC, IMORDW, IMMTF1, IMMTF2, IMMTF3, ",
        "IMMTF4, IMMTF5, IMEXPD, IMDEFD, IMSFLT, IMMAKE, IMCOBY, IMLLX, IMCMGL, IMCOMH, ",
        "IMURCD, IMURDT, IMURAT, IMURAB, IMURRF, IMUSER, IMPID, IMJOBN, IMUPMJ, IMTDAY, ",
        "IMUPCN, IMSCC0, IMUMUP, IMUMDF, IMUMS0, IMUMS1, IMUMS2, IMUMS3, IMUMS4, IMUMS5, ",
        "IMUMS6, IMUMS7, IMUMS8, IMPOC, IMAVRT, IMEQTY, IMWTRQ, IMTMPL, IMSEG1, IMSEG2, ",
        "IMSEG3, IMSEG4, IMSEG5, IMSEG6, IMSEG7, IMSEG8, IMSEG9, IMSEG0, IMMIC, IMAING, ",
        "IMBBDD, IMCMDM, IMLECM, IMLEDD, IMPEFD, IMSBDD, IMU1DD, IMU2DD, IMU3DD, IMU4DD, ",
        "IMU5DD, IMDLTL, IMDPPO, IMDUAL, IMXDCK, IMLAF, IMLTFM, IMRWLA, IMLNPA, IMLOTC, ",
        "IMAPSC, IMAUOM, IMCONB, IMGCMP, IMPRI1, IMPRI2, IMASHL, IMVMINV, IMCMETH, IMEXPI, ",
        "IMOPTH, IMCUTH, IMUMTH, IMLMFG, IMLINE, IMDFTPCT, IMKBIT, IMDFENDITM, IMKANEXLL, ",
        "IMSCPSELL, IMMOPTH, IMMCUTH, IMCUMTH, IMATPRN, IMATPCA, IMATPAC, IMCOORE, IMVCPFC, ",
        "IMPNYN",
        "from F4101"
    })
    @Results({
        @Result(column="IMITM", property="imitm", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="IMLITM", property="imlitm", jdbcType=JdbcType.NCHAR),
        @Result(column="IMAITM", property="imaitm", jdbcType=JdbcType.NCHAR),
        @Result(column="IMDSC1", property="imdsc1", jdbcType=JdbcType.NCHAR),
        @Result(column="IMDSC2", property="imdsc2", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSRTX", property="imsrtx", jdbcType=JdbcType.NCHAR),
        @Result(column="IMALN", property="imaln", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSRP1", property="imsrp1", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSRP2", property="imsrp2", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSRP3", property="imsrp3", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSRP4", property="imsrp4", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSRP5", property="imsrp5", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSRP6", property="imsrp6", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSRP7", property="imsrp7", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSRP8", property="imsrp8", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSRP9", property="imsrp9", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSRP0", property="imsrp0", jdbcType=JdbcType.NCHAR),
        @Result(column="IMPRP1", property="imprp1", jdbcType=JdbcType.NCHAR),
        @Result(column="IMPRP2", property="imprp2", jdbcType=JdbcType.NCHAR),
        @Result(column="IMPRP3", property="imprp3", jdbcType=JdbcType.NCHAR),
        @Result(column="IMPRP4", property="imprp4", jdbcType=JdbcType.NCHAR),
        @Result(column="IMPRP5", property="imprp5", jdbcType=JdbcType.NCHAR),
        @Result(column="IMPRP6", property="imprp6", jdbcType=JdbcType.NCHAR),
        @Result(column="IMPRP7", property="imprp7", jdbcType=JdbcType.NCHAR),
        @Result(column="IMPRP8", property="imprp8", jdbcType=JdbcType.NCHAR),
        @Result(column="IMPRP9", property="imprp9", jdbcType=JdbcType.NCHAR),
        @Result(column="IMPRP0", property="imprp0", jdbcType=JdbcType.NCHAR),
        @Result(column="IMCDCD", property="imcdcd", jdbcType=JdbcType.NCHAR),
        @Result(column="IMPDGR", property="impdgr", jdbcType=JdbcType.NCHAR),
        @Result(column="IMDSGP", property="imdsgp", jdbcType=JdbcType.NCHAR),
        @Result(column="IMPRGR", property="imprgr", jdbcType=JdbcType.NCHAR),
        @Result(column="IMRPRC", property="imrprc", jdbcType=JdbcType.NCHAR),
        @Result(column="IMORPR", property="imorpr", jdbcType=JdbcType.NCHAR),
        @Result(column="IMBUYR", property="imbuyr", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMDRAW", property="imdraw", jdbcType=JdbcType.NCHAR),
        @Result(column="IMRVNO", property="imrvno", jdbcType=JdbcType.NCHAR),
        @Result(column="IMDSZE", property="imdsze", jdbcType=JdbcType.NCHAR),
        @Result(column="IMVCUD", property="imvcud", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMCARS", property="imcars", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMCARP", property="imcarp", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMSHCN", property="imshcn", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSHCM", property="imshcm", jdbcType=JdbcType.NCHAR),
        @Result(column="IMUOM1", property="imuom1", jdbcType=JdbcType.NCHAR),
        @Result(column="IMUOM2", property="imuom2", jdbcType=JdbcType.NCHAR),
        @Result(column="IMUOM3", property="imuom3", jdbcType=JdbcType.NCHAR),
        @Result(column="IMUOM4", property="imuom4", jdbcType=JdbcType.NCHAR),
        @Result(column="IMUOM6", property="imuom6", jdbcType=JdbcType.NCHAR),
        @Result(column="IMUOM8", property="imuom8", jdbcType=JdbcType.NCHAR),
        @Result(column="IMUOM9", property="imuom9", jdbcType=JdbcType.NCHAR),
        @Result(column="IMUWUM", property="imuwum", jdbcType=JdbcType.NCHAR),
        @Result(column="IMUVM1", property="imuvm1", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSUTM", property="imsutm", jdbcType=JdbcType.NCHAR),
        @Result(column="IMUMVW", property="imumvw", jdbcType=JdbcType.NCHAR),
        @Result(column="IMCYCL", property="imcycl", jdbcType=JdbcType.NCHAR),
        @Result(column="IMGLPT", property="imglpt", jdbcType=JdbcType.NCHAR),
        @Result(column="IMPLEV", property="implev", jdbcType=JdbcType.NCHAR),
        @Result(column="IMPPLV", property="impplv", jdbcType=JdbcType.NCHAR),
        @Result(column="IMCLEV", property="imclev", jdbcType=JdbcType.NCHAR),
        @Result(column="IMPRPO", property="imprpo", jdbcType=JdbcType.NCHAR),
        @Result(column="IMCKAV", property="imckav", jdbcType=JdbcType.NCHAR),
        @Result(column="IMBPFG", property="imbpfg", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSRCE", property="imsrce", jdbcType=JdbcType.NCHAR),
        @Result(column="IMOT1Y", property="imot1y", jdbcType=JdbcType.NCHAR),
        @Result(column="IMOT2Y", property="imot2y", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSTDP", property="imstdp", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMFRMP", property="imfrmp", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMTHRP", property="imthrp", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMSTDG", property="imstdg", jdbcType=JdbcType.NCHAR),
        @Result(column="IMFRGD", property="imfrgd", jdbcType=JdbcType.NCHAR),
        @Result(column="IMTHGD", property="imthgd", jdbcType=JdbcType.NCHAR),
        @Result(column="IMCOTY", property="imcoty", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSTKT", property="imstkt", jdbcType=JdbcType.NCHAR),
        @Result(column="IMLNTY", property="imlnty", jdbcType=JdbcType.NCHAR),
        @Result(column="IMCONT", property="imcont", jdbcType=JdbcType.NCHAR),
        @Result(column="IMBACK", property="imback", jdbcType=JdbcType.NCHAR),
        @Result(column="IMIFLA", property="imifla", jdbcType=JdbcType.NCHAR),
        @Result(column="IMTFLA", property="imtfla", jdbcType=JdbcType.NCHAR),
        @Result(column="IMINMG", property="iminmg", jdbcType=JdbcType.NCHAR),
        @Result(column="IMABCS", property="imabcs", jdbcType=JdbcType.NCHAR),
        @Result(column="IMABCM", property="imabcm", jdbcType=JdbcType.NCHAR),
        @Result(column="IMABCI", property="imabci", jdbcType=JdbcType.NCHAR),
        @Result(column="IMOVR", property="imovr", jdbcType=JdbcType.NCHAR),
        @Result(column="IMWARR", property="imwarr", jdbcType=JdbcType.NCHAR),
        @Result(column="IMCMCG", property="imcmcg", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSRNR", property="imsrnr", jdbcType=JdbcType.NCHAR),
        @Result(column="IMPMTH", property="impmth", jdbcType=JdbcType.NCHAR),
        @Result(column="IMFIFO", property="imfifo", jdbcType=JdbcType.NCHAR),
        @Result(column="IMLOTS", property="imlots", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSLD", property="imsld", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMANPL", property="imanpl", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMMPST", property="immpst", jdbcType=JdbcType.NCHAR),
        @Result(column="IMPCTM", property="impctm", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMMMPC", property="immmpc", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMPTSC", property="imptsc", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSNS", property="imsns", jdbcType=JdbcType.NCHAR),
        @Result(column="IMLTLV", property="imltlv", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMLTMF", property="imltmf", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMLTCM", property="imltcm", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMOPC", property="imopc", jdbcType=JdbcType.NCHAR),
        @Result(column="IMOPV", property="imopv", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMACQ", property="imacq", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMMLQ", property="immlq", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMLTPU", property="imltpu", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMMPSP", property="immpsp", jdbcType=JdbcType.NCHAR),
        @Result(column="IMMRPP", property="immrpp", jdbcType=JdbcType.NCHAR),
        @Result(column="IMITC", property="imitc", jdbcType=JdbcType.NCHAR),
        @Result(column="IMORDW", property="imordw", jdbcType=JdbcType.NCHAR),
        @Result(column="IMMTF1", property="immtf1", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMMTF2", property="immtf2", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMMTF3", property="immtf3", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMMTF4", property="immtf4", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMMTF5", property="immtf5", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMEXPD", property="imexpd", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMDEFD", property="imdefd", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMSFLT", property="imsflt", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMMAKE", property="immake", jdbcType=JdbcType.NCHAR),
        @Result(column="IMCOBY", property="imcoby", jdbcType=JdbcType.NCHAR),
        @Result(column="IMLLX", property="imllx", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMCMGL", property="imcmgl", jdbcType=JdbcType.NCHAR),
        @Result(column="IMCOMH", property="imcomh", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMURCD", property="imurcd", jdbcType=JdbcType.NCHAR),
        @Result(column="IMURDT", property="imurdt", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMURAT", property="imurat", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMURAB", property="imurab", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMURRF", property="imurrf", jdbcType=JdbcType.NCHAR),
        @Result(column="IMUSER", property="imuser", jdbcType=JdbcType.NCHAR),
        @Result(column="IMPID", property="impid", jdbcType=JdbcType.NCHAR),
        @Result(column="IMJOBN", property="imjobn", jdbcType=JdbcType.NCHAR),
        @Result(column="IMUPMJ", property="imupmj", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMTDAY", property="imtday", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMUPCN", property="imupcn", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSCC0", property="imscc0", jdbcType=JdbcType.NCHAR),
        @Result(column="IMUMUP", property="imumup", jdbcType=JdbcType.NCHAR),
        @Result(column="IMUMDF", property="imumdf", jdbcType=JdbcType.NCHAR),
        @Result(column="IMUMS0", property="imums0", jdbcType=JdbcType.NCHAR),
        @Result(column="IMUMS1", property="imums1", jdbcType=JdbcType.NCHAR),
        @Result(column="IMUMS2", property="imums2", jdbcType=JdbcType.NCHAR),
        @Result(column="IMUMS3", property="imums3", jdbcType=JdbcType.NCHAR),
        @Result(column="IMUMS4", property="imums4", jdbcType=JdbcType.NCHAR),
        @Result(column="IMUMS5", property="imums5", jdbcType=JdbcType.NCHAR),
        @Result(column="IMUMS6", property="imums6", jdbcType=JdbcType.NCHAR),
        @Result(column="IMUMS7", property="imums7", jdbcType=JdbcType.NCHAR),
        @Result(column="IMUMS8", property="imums8", jdbcType=JdbcType.NCHAR),
        @Result(column="IMPOC", property="impoc", jdbcType=JdbcType.NCHAR),
        @Result(column="IMAVRT", property="imavrt", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMEQTY", property="imeqty", jdbcType=JdbcType.NCHAR),
        @Result(column="IMWTRQ", property="imwtrq", jdbcType=JdbcType.NCHAR),
        @Result(column="IMTMPL", property="imtmpl", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSEG1", property="imseg1", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSEG2", property="imseg2", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSEG3", property="imseg3", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSEG4", property="imseg4", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSEG5", property="imseg5", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSEG6", property="imseg6", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSEG7", property="imseg7", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSEG8", property="imseg8", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSEG9", property="imseg9", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSEG0", property="imseg0", jdbcType=JdbcType.NCHAR),
        @Result(column="IMMIC", property="immic", jdbcType=JdbcType.NCHAR),
        @Result(column="IMAING", property="imaing", jdbcType=JdbcType.NCHAR),
        @Result(column="IMBBDD", property="imbbdd", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMCMDM", property="imcmdm", jdbcType=JdbcType.NCHAR),
        @Result(column="IMLECM", property="imlecm", jdbcType=JdbcType.NCHAR),
        @Result(column="IMLEDD", property="imledd", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMPEFD", property="impefd", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMSBDD", property="imsbdd", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMU1DD", property="imu1dd", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMU2DD", property="imu2dd", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMU3DD", property="imu3dd", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMU4DD", property="imu4dd", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMU5DD", property="imu5dd", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMDLTL", property="imdltl", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMDPPO", property="imdppo", jdbcType=JdbcType.NCHAR),
        @Result(column="IMDUAL", property="imdual", jdbcType=JdbcType.NCHAR),
        @Result(column="IMXDCK", property="imxdck", jdbcType=JdbcType.NCHAR),
        @Result(column="IMLAF", property="imlaf", jdbcType=JdbcType.NCHAR),
        @Result(column="IMLTFM", property="imltfm", jdbcType=JdbcType.NCHAR),
        @Result(column="IMRWLA", property="imrwla", jdbcType=JdbcType.NCHAR),
        @Result(column="IMLNPA", property="imlnpa", jdbcType=JdbcType.NCHAR),
        @Result(column="IMLOTC", property="imlotc", jdbcType=JdbcType.NCHAR),
        @Result(column="IMAPSC", property="imapsc", jdbcType=JdbcType.NCHAR),
        @Result(column="IMAUOM", property="imauom", jdbcType=JdbcType.NCHAR),
        @Result(column="IMCONB", property="imconb", jdbcType=JdbcType.NCHAR),
        @Result(column="IMGCMP", property="imgcmp", jdbcType=JdbcType.NCHAR),
        @Result(column="IMPRI1", property="impri1", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMPRI2", property="impri2", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMASHL", property="imashl", jdbcType=JdbcType.NCHAR),
        @Result(column="IMVMINV", property="imvminv", jdbcType=JdbcType.NCHAR),
        @Result(column="IMCMETH", property="imcmeth", jdbcType=JdbcType.NCHAR),
        @Result(column="IMEXPI", property="imexpi", jdbcType=JdbcType.NCHAR),
        @Result(column="IMOPTH", property="imopth", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMCUTH", property="imcuth", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMUMTH", property="imumth", jdbcType=JdbcType.NCHAR),
        @Result(column="IMLMFG", property="imlmfg", jdbcType=JdbcType.NCHAR),
        @Result(column="IMLINE", property="imline", jdbcType=JdbcType.NCHAR),
        @Result(column="IMDFTPCT", property="imdftpct", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMKBIT", property="imkbit", jdbcType=JdbcType.NCHAR),
        @Result(column="IMDFENDITM", property="imdfenditm", jdbcType=JdbcType.NCHAR),
        @Result(column="IMKANEXLL", property="imkanexll", jdbcType=JdbcType.NCHAR),
        @Result(column="IMSCPSELL", property="imscpsell", jdbcType=JdbcType.NCHAR),
        @Result(column="IMMOPTH", property="immopth", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMMCUTH", property="immcuth", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMCUMTH", property="imcumth", jdbcType=JdbcType.NCHAR),
        @Result(column="IMATPRN", property="imatprn", jdbcType=JdbcType.NCHAR),
        @Result(column="IMATPCA", property="imatpca", jdbcType=JdbcType.NCHAR),
        @Result(column="IMATPAC", property="imatpac", jdbcType=JdbcType.NCHAR),
        @Result(column="IMCOORE", property="imcoore", jdbcType=JdbcType.NCHAR),
        @Result(column="IMVCPFC", property="imvcpfc", jdbcType=JdbcType.NCHAR),
        @Result(column="IMPNYN", property="impnyn", jdbcType=JdbcType.NCHAR)
    })
    List<F4101> selectAll();
}