package com.el.cfg.mapper;

import com.el.cfg.domain.Fe84101;
import java.util.List;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

public interface Fe84101Mapper {
    @Select({
        "select",
        "SPLITM, SPEV01, SPDSC1, SPE8NAME, SPDSC2, SPE8JX, SPAITM, SPAN8, SPORIG, SPE8PZWH, ",
        "SPE8ZDYL, SPE8JHG, SPE8ZTW, SPE8GFG, SPE8PTYP, SPE8ATCDL, SPE8ATCXL, SPE8YYKS, ",
        "SPE8FXDJ, SPE8CCTJ, SPE8QTCC, SPE8JGG, SPE8SFFC, SPE8TYM, SPE8JDSJ, SPE8XLHGL, ",
        "SPE8ZDYH, SPE8YHZQ, SPE8BGBS, SPE8SPXZ, SPE8SHFLBM, SPE8YHNR, SPE8YHZC, SPE8LSL, ",
        "SPE8KCE, SPURCD, SPURDT, SPURAT, SPURAB, SPEV02, SPEV03, SPEV04, SPEV05, SPUSER, ",
        "SPPID, SPJOBN, SPUPMJ, SPUPMT, SPIDATE, SPDF01, SPRDATE, SPDF02, SPUKID, SPSTATUS, ",
        "SPFLAG, SPE8SCG, SPE8CPDL, SPE8TSFL, SPE8CPFL",
        "from FE84101",
        "where SPLITM = #{splitm,jdbcType=NCHAR}"
    })
    @Results({
        @Result(column="SPLITM", property="splitm", jdbcType=JdbcType.NCHAR, id=true),
        @Result(column="SPEV01", property="spev01", jdbcType=JdbcType.NCHAR),
        @Result(column="SPDSC1", property="spdsc1", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8NAME", property="spe8name", jdbcType=JdbcType.NCHAR),
        @Result(column="SPDSC2", property="spdsc2", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8JX", property="spe8jx", jdbcType=JdbcType.NCHAR),
        @Result(column="SPAITM", property="spaitm", jdbcType=JdbcType.NCHAR),
        @Result(column="SPAN8", property="span8", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPORIG", property="sporig", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8PZWH", property="spe8pzwh", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8ZDYL", property="spe8zdyl", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8JHG", property="spe8jhg", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8ZTW", property="spe8ztw", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8GFG", property="spe8gfg", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8PTYP", property="spe8ptyp", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8ATCDL", property="spe8atcdl", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8ATCXL", property="spe8atcxl", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8YYKS", property="spe8yyks", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8FXDJ", property="spe8fxdj", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8CCTJ", property="spe8cctj", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8QTCC", property="spe8qtcc", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8JGG", property="spe8jgg", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8SFFC", property="spe8sffc", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8TYM", property="spe8tym", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8JDSJ", property="spe8jdsj", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="SPE8XLHGL", property="spe8xlhgl", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8ZDYH", property="spe8zdyh", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8YHZQ", property="spe8yhzq", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPE8BGBS", property="spe8bgbs", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8SPXZ", property="spe8spxz", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8SHFLBM", property="spe8shflbm", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8YHNR", property="spe8yhnr", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8YHZC", property="spe8yhzc", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8LSL", property="spe8lsl", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8KCE", property="spe8kce", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPURCD", property="spurcd", jdbcType=JdbcType.NCHAR),
        @Result(column="SPURDT", property="spurdt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPURAT", property="spurat", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPURAB", property="spurab", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPEV02", property="spev02", jdbcType=JdbcType.NCHAR),
        @Result(column="SPEV03", property="spev03", jdbcType=JdbcType.NCHAR),
        @Result(column="SPEV04", property="spev04", jdbcType=JdbcType.NCHAR),
        @Result(column="SPEV05", property="spev05", jdbcType=JdbcType.NCHAR),
        @Result(column="SPUSER", property="spuser", jdbcType=JdbcType.NCHAR),
        @Result(column="SPPID", property="sppid", jdbcType=JdbcType.NCHAR),
        @Result(column="SPJOBN", property="spjobn", jdbcType=JdbcType.NCHAR),
        @Result(column="SPUPMJ", property="spupmj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPUPMT", property="spupmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPIDATE", property="spidate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="SPDF01", property="spdf01", jdbcType=JdbcType.NCHAR),
        @Result(column="SPRDATE", property="sprdate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="SPDF02", property="spdf02", jdbcType=JdbcType.NCHAR),
        @Result(column="SPUKID", property="spukid", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPSTATUS", property="spstatus", jdbcType=JdbcType.NCHAR),
        @Result(column="SPFLAG", property="spflag", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8SCG", property="spe8scg", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8CPDL", property="spe8cpdl", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8TSFL", property="spe8tsfl", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8CPFL", property="spe8cpfl", jdbcType=JdbcType.NCHAR)
    })
    Fe84101 selectByPrimaryKey(String splitm);

    @Select({
        "select",
        "SPLITM, SPEV01, SPDSC1, SPE8NAME, SPDSC2, SPE8JX, SPAITM, SPAN8, SPORIG, SPE8PZWH, ",
        "SPE8ZDYL, SPE8JHG, SPE8ZTW, SPE8GFG, SPE8PTYP, SPE8ATCDL, SPE8ATCXL, SPE8YYKS, ",
        "SPE8FXDJ, SPE8CCTJ, SPE8QTCC, SPE8JGG, SPE8SFFC, SPE8TYM, SPE8JDSJ, SPE8XLHGL, ",
        "SPE8ZDYH, SPE8YHZQ, SPE8BGBS, SPE8SPXZ, SPE8SHFLBM, SPE8YHNR, SPE8YHZC, SPE8LSL, ",
        "SPE8KCE, SPURCD, SPURDT, SPURAT, SPURAB, SPEV02, SPEV03, SPEV04, SPEV05, SPUSER, ",
        "SPPID, SPJOBN, SPUPMJ, SPUPMT, SPIDATE, SPDF01, SPRDATE, SPDF02, SPUKID, SPSTATUS, ",
        "SPFLAG, SPE8SCG, SPE8CPDL, SPE8TSFL, SPE8CPFL",
        "from FE84101"
    })
    @Results({
        @Result(column="SPLITM", property="splitm", jdbcType=JdbcType.NCHAR, id=true),
        @Result(column="SPEV01", property="spev01", jdbcType=JdbcType.NCHAR),
        @Result(column="SPDSC1", property="spdsc1", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8NAME", property="spe8name", jdbcType=JdbcType.NCHAR),
        @Result(column="SPDSC2", property="spdsc2", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8JX", property="spe8jx", jdbcType=JdbcType.NCHAR),
        @Result(column="SPAITM", property="spaitm", jdbcType=JdbcType.NCHAR),
        @Result(column="SPAN8", property="span8", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPORIG", property="sporig", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8PZWH", property="spe8pzwh", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8ZDYL", property="spe8zdyl", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8JHG", property="spe8jhg", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8ZTW", property="spe8ztw", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8GFG", property="spe8gfg", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8PTYP", property="spe8ptyp", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8ATCDL", property="spe8atcdl", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8ATCXL", property="spe8atcxl", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8YYKS", property="spe8yyks", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8FXDJ", property="spe8fxdj", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8CCTJ", property="spe8cctj", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8QTCC", property="spe8qtcc", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8JGG", property="spe8jgg", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8SFFC", property="spe8sffc", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8TYM", property="spe8tym", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8JDSJ", property="spe8jdsj", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="SPE8XLHGL", property="spe8xlhgl", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8ZDYH", property="spe8zdyh", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8YHZQ", property="spe8yhzq", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPE8BGBS", property="spe8bgbs", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8SPXZ", property="spe8spxz", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8SHFLBM", property="spe8shflbm", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8YHNR", property="spe8yhnr", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8YHZC", property="spe8yhzc", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8LSL", property="spe8lsl", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8KCE", property="spe8kce", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPURCD", property="spurcd", jdbcType=JdbcType.NCHAR),
        @Result(column="SPURDT", property="spurdt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPURAT", property="spurat", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPURAB", property="spurab", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPEV02", property="spev02", jdbcType=JdbcType.NCHAR),
        @Result(column="SPEV03", property="spev03", jdbcType=JdbcType.NCHAR),
        @Result(column="SPEV04", property="spev04", jdbcType=JdbcType.NCHAR),
        @Result(column="SPEV05", property="spev05", jdbcType=JdbcType.NCHAR),
        @Result(column="SPUSER", property="spuser", jdbcType=JdbcType.NCHAR),
        @Result(column="SPPID", property="sppid", jdbcType=JdbcType.NCHAR),
        @Result(column="SPJOBN", property="spjobn", jdbcType=JdbcType.NCHAR),
        @Result(column="SPUPMJ", property="spupmj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPUPMT", property="spupmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPIDATE", property="spidate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="SPDF01", property="spdf01", jdbcType=JdbcType.NCHAR),
        @Result(column="SPRDATE", property="sprdate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="SPDF02", property="spdf02", jdbcType=JdbcType.NCHAR),
        @Result(column="SPUKID", property="spukid", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPSTATUS", property="spstatus", jdbcType=JdbcType.NCHAR),
        @Result(column="SPFLAG", property="spflag", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8SCG", property="spe8scg", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8CPDL", property="spe8cpdl", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8TSFL", property="spe8tsfl", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8CPFL", property="spe8cpfl", jdbcType=JdbcType.NCHAR)
    })
    List<Fe84101> selectAll();
}