package com.el.cfg.mapper;

import com.el.cmic.domain.goods.Fe8nt001;
import java.util.List;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

public interface Fe8nt001Mapper {
    @Select({
        "select",
        "SPAITM, SPLITM, SPITM, SPDSC1, SPDSC2, SPE8TYM, SPUOM1, SPDL01, SPGLPT, SPDL02, ",
        "SPMMCU, SPAN8, SPE8NAME, SPORIG, SPE8FXDJ, SPDL03, SPE8CCTJ, SPDL04, SPE8QTCC, ",
        "SPE8XLHGL, SPE8ZDYH, SPE8YHZQ, SPE8CPFL, SPE8ZZLXA, SPE8ZZBM, SPEFTJ, SPEXDJ, ",
        "SPE8PATH, SPIR01, SPIR02, SPIR03, SPIR04, SPIR05, SPHRB, SPPSAL, SPIPAY, SPTDSC, ",
        "SPEFHR, SPCRTJ, SPDIVJ, SPAFDJ, SPCKDT, SPUSER, SPUPMJ, SPTDAY, SPPID, SPJOBN, ",
        "SPURCD, SPURDT, SPURAT, SPURAB, SPURRF, SPFLAG, SPEDSP, SPEV01, SPEV02, SPEV03",
        "from CRPDTA.FE8NT001",
        "where SPAITM = #{spaitm,jdbcType=NCHAR}"
    })
    @Results({
        @Result(column="SPAITM", property="spaitm", jdbcType=JdbcType.NCHAR, id=true),
        @Result(column="SPLITM", property="splitm", jdbcType=JdbcType.NCHAR),
        @Result(column="SPITM", property="spitm", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPDSC1", property="spdsc1", jdbcType=JdbcType.NCHAR),
        @Result(column="SPDSC2", property="spdsc2", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8TYM", property="spe8tym", jdbcType=JdbcType.NCHAR),
        @Result(column="SPUOM1", property="spuom1", jdbcType=JdbcType.NCHAR),
        @Result(column="SPDL01", property="spdl01", jdbcType=JdbcType.NCHAR),
        @Result(column="SPGLPT", property="spglpt", jdbcType=JdbcType.NCHAR),
        @Result(column="SPDL02", property="spdl02", jdbcType=JdbcType.NCHAR),
        @Result(column="SPMMCU", property="spmmcu", jdbcType=JdbcType.NCHAR),
        @Result(column="SPAN8", property="span8", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPE8NAME", property="spe8name", jdbcType=JdbcType.NCHAR),
        @Result(column="SPORIG", property="sporig", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8FXDJ", property="spe8fxdj", jdbcType=JdbcType.NCHAR),
        @Result(column="SPDL03", property="spdl03", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8CCTJ", property="spe8cctj", jdbcType=JdbcType.NCHAR),
        @Result(column="SPDL04", property="spdl04", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8QTCC", property="spe8qtcc", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8XLHGL", property="spe8xlhgl", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8ZDYH", property="spe8zdyh", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8YHZQ", property="spe8yhzq", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPE8CPFL", property="spe8cpfl", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8ZZLXA", property="spe8zzlxa", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8ZZBM", property="spe8zzbm", jdbcType=JdbcType.NCHAR),
        @Result(column="SPEFTJ", property="speftj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPEXDJ", property="spexdj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPE8PATH", property="spe8path", jdbcType=JdbcType.NCHAR),
        @Result(column="SPIR01", property="spir01", jdbcType=JdbcType.NCHAR),
        @Result(column="SPIR02", property="spir02", jdbcType=JdbcType.NCHAR),
        @Result(column="SPIR03", property="spir03", jdbcType=JdbcType.NCHAR),
        @Result(column="SPIR04", property="spir04", jdbcType=JdbcType.NCHAR),
        @Result(column="SPIR05", property="spir05", jdbcType=JdbcType.NCHAR),
        @Result(column="SPHRB", property="sphrb", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPPSAL", property="sppsal", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPIPAY", property="spipay", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPTDSC", property="sptdsc", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPEFHR", property="spefhr", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPCRTJ", property="spcrtj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPDIVJ", property="spdivj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPAFDJ", property="spafdj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPCKDT", property="spckdt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPUSER", property="spuser", jdbcType=JdbcType.NCHAR),
        @Result(column="SPUPMJ", property="spupmj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPTDAY", property="sptday", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPPID", property="sppid", jdbcType=JdbcType.NCHAR),
        @Result(column="SPJOBN", property="spjobn", jdbcType=JdbcType.NCHAR),
        @Result(column="SPURCD", property="spurcd", jdbcType=JdbcType.NCHAR),
        @Result(column="SPURDT", property="spurdt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPURAT", property="spurat", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPURAB", property="spurab", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPURRF", property="spurrf", jdbcType=JdbcType.NCHAR),
        @Result(column="SPFLAG", property="spflag", jdbcType=JdbcType.NCHAR),
        @Result(column="SPEDSP", property="spedsp", jdbcType=JdbcType.NCHAR),
        @Result(column="SPEV01", property="spev01", jdbcType=JdbcType.NCHAR),
        @Result(column="SPEV02", property="spev02", jdbcType=JdbcType.NCHAR),
        @Result(column="SPEV03", property="spev03", jdbcType=JdbcType.NCHAR)
    })
    Fe8nt001 selectByPrimaryKey(String spaitm);

    @Select({
        "select",
        "SPAITM, SPLITM, SPITM, SPDSC1, SPDSC2, SPE8TYM, SPUOM1, SPDL01, SPGLPT, SPDL02, ",
        "SPMMCU, SPAN8, SPE8NAME, SPORIG, SPE8FXDJ, SPDL03, SPE8CCTJ, SPDL04, SPE8QTCC, ",
        "SPE8XLHGL, SPE8ZDYH, SPE8YHZQ, SPE8CPFL, SPE8ZZLXA, SPE8ZZBM, SPEFTJ, SPEXDJ, ",
        "SPE8PATH, SPIR01, SPIR02, SPIR03, SPIR04, SPIR05, SPHRB, SPPSAL, SPIPAY, SPTDSC, ",
        "SPEFHR, SPCRTJ, SPDIVJ, SPAFDJ, SPCKDT, SPUSER, SPUPMJ, SPTDAY, SPPID, SPJOBN, ",
        "SPURCD, SPURDT, SPURAT, SPURAB, SPURRF, SPFLAG, SPEDSP, SPEV01, SPEV02, SPEV03",
        "from CRPDTA.FE8NT001"
    })
    @Results({
        @Result(column="SPAITM", property="spaitm", jdbcType=JdbcType.NCHAR, id=true),
        @Result(column="SPLITM", property="splitm", jdbcType=JdbcType.NCHAR),
        @Result(column="SPITM", property="spitm", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPDSC1", property="spdsc1", jdbcType=JdbcType.NCHAR),
        @Result(column="SPDSC2", property="spdsc2", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8TYM", property="spe8tym", jdbcType=JdbcType.NCHAR),
        @Result(column="SPUOM1", property="spuom1", jdbcType=JdbcType.NCHAR),
        @Result(column="SPDL01", property="spdl01", jdbcType=JdbcType.NCHAR),
        @Result(column="SPGLPT", property="spglpt", jdbcType=JdbcType.NCHAR),
        @Result(column="SPDL02", property="spdl02", jdbcType=JdbcType.NCHAR),
        @Result(column="SPMMCU", property="spmmcu", jdbcType=JdbcType.NCHAR),
        @Result(column="SPAN8", property="span8", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPE8NAME", property="spe8name", jdbcType=JdbcType.NCHAR),
        @Result(column="SPORIG", property="sporig", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8FXDJ", property="spe8fxdj", jdbcType=JdbcType.NCHAR),
        @Result(column="SPDL03", property="spdl03", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8CCTJ", property="spe8cctj", jdbcType=JdbcType.NCHAR),
        @Result(column="SPDL04", property="spdl04", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8QTCC", property="spe8qtcc", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8XLHGL", property="spe8xlhgl", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8ZDYH", property="spe8zdyh", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8YHZQ", property="spe8yhzq", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPE8CPFL", property="spe8cpfl", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8ZZLXA", property="spe8zzlxa", jdbcType=JdbcType.NCHAR),
        @Result(column="SPE8ZZBM", property="spe8zzbm", jdbcType=JdbcType.NCHAR),
        @Result(column="SPEFTJ", property="speftj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPEXDJ", property="spexdj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPE8PATH", property="spe8path", jdbcType=JdbcType.NCHAR),
        @Result(column="SPIR01", property="spir01", jdbcType=JdbcType.NCHAR),
        @Result(column="SPIR02", property="spir02", jdbcType=JdbcType.NCHAR),
        @Result(column="SPIR03", property="spir03", jdbcType=JdbcType.NCHAR),
        @Result(column="SPIR04", property="spir04", jdbcType=JdbcType.NCHAR),
        @Result(column="SPIR05", property="spir05", jdbcType=JdbcType.NCHAR),
        @Result(column="SPHRB", property="sphrb", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPPSAL", property="sppsal", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPIPAY", property="spipay", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPTDSC", property="sptdsc", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPEFHR", property="spefhr", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPCRTJ", property="spcrtj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPDIVJ", property="spdivj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPAFDJ", property="spafdj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPCKDT", property="spckdt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPUSER", property="spuser", jdbcType=JdbcType.NCHAR),
        @Result(column="SPUPMJ", property="spupmj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPTDAY", property="sptday", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPPID", property="sppid", jdbcType=JdbcType.NCHAR),
        @Result(column="SPJOBN", property="spjobn", jdbcType=JdbcType.NCHAR),
        @Result(column="SPURCD", property="spurcd", jdbcType=JdbcType.NCHAR),
        @Result(column="SPURDT", property="spurdt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPURAT", property="spurat", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPURAB", property="spurab", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPURRF", property="spurrf", jdbcType=JdbcType.NCHAR),
        @Result(column="SPFLAG", property="spflag", jdbcType=JdbcType.NCHAR),
        @Result(column="SPEDSP", property="spedsp", jdbcType=JdbcType.NCHAR),
        @Result(column="SPEV01", property="spev01", jdbcType=JdbcType.NCHAR),
        @Result(column="SPEV02", property="spev02", jdbcType=JdbcType.NCHAR),
        @Result(column="SPEV03", property="spev03", jdbcType=JdbcType.NCHAR)
    })
    List<Fe8nt001> selectAll();
}