package com.el.cfg.mapper;

import com.el.cfg.domain.Fe841001;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

public interface Fe841001Mapper {
    @Select({
        "select",
        "SQUKIDP, SQKCOO, SQLITM, SQITM, SQEV01, SQAITM, SQDSC1, SQE8NAME, SQDSC2, SQE8JX, ",
        "SQSRTX, SQACLT, SQACPL, SQAN8, SQAC28, SQE8SCXKZ, SQE8SCBAH, SQORIG, SQE8PZWH, ",
        "SQE8ZDYL, SQE8JHG, SQE8ZTW, SQE8GFG, SQE8PTYP, SQE8ATCDL, SQE8ATCXL, SQE8YYKS, ",
        "SQE8FXDJ, SQE8CCTJ, SQE8QTCC, SQE8JGG, SQVR01, SQIR01, SQVR02, SQIR02, SQVR03, ",
        "SQDSC3, SQVR04, SQIR04, SQSRP3, SQDSE3, SQSRP4, SQBFNM, SQDSE4, SQSRP5, SQBFNN, ",
        "SQDSE5, SQUOM1, SQDL01, SQBFNU, SQBFPL, SQUKID, SQURCD, SQURDT, SQURAT, SQURAB, ",
        "SQEV02, SQEV03, SQEV04, SQEV05, SQUSER, SQPID, SQJOBN, SQUPMJ, SQUPMT, SQIDATE, ",
        "SQDF01, SQRDATE, SQDF02, SQSTATUS, SQFLAG, SQFIL2, SQBFPM, SQAIT1, SQAIT2, SQA001, ",
        "SQA002, SQFIL3, SQA003, SQA004, SQCJ01, SQACTF, SQCJ02, SQCJ03, SQAA06, SQCJ04, ",
        "SQCJ05, SQA201, SQADLM, SQA202, SQPP01, SQA203, SQA204, SQE8CPDL, SQE8TSFL, ",
        "SQE8CPFL, SQGK01, SQGK02, SQGK03",
        "from FE841001",
        "where SQUKIDP = #{squkidp,jdbcType=DECIMAL}"
    })
    @Results({
        @Result(column="SQUKIDP", property="squkidp", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="SQKCOO", property="sqkcoo", jdbcType=JdbcType.NCHAR),
        @Result(column="SQLITM", property="sqlitm", jdbcType=JdbcType.NCHAR),
        @Result(column="SQITM", property="sqitm", jdbcType=JdbcType.DECIMAL),
        @Result(column="SQEV01", property="sqev01", jdbcType=JdbcType.NCHAR),
        @Result(column="SQAITM", property="sqaitm", jdbcType=JdbcType.NCHAR),
        @Result(column="SQDSC1", property="sqdsc1", jdbcType=JdbcType.NCHAR),
        @Result(column="SQE8NAME", property="sqe8name", jdbcType=JdbcType.NCHAR),
        @Result(column="SQDSC2", property="sqdsc2", jdbcType=JdbcType.NCHAR),
        @Result(column="SQE8JX", property="sqe8jx", jdbcType=JdbcType.NCHAR),
        @Result(column="SQSRTX", property="sqsrtx", jdbcType=JdbcType.NCHAR),
        @Result(column="SQACLT", property="sqaclt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SQACPL", property="sqacpl", jdbcType=JdbcType.DECIMAL),
        @Result(column="SQAN8", property="sqan8", jdbcType=JdbcType.DECIMAL),
        @Result(column="SQAC28", property="sqac28", jdbcType=JdbcType.NCHAR),
        @Result(column="SQE8SCXKZ", property="sqe8scxkz", jdbcType=JdbcType.NCHAR),
        @Result(column="SQE8SCBAH", property="sqe8scbah", jdbcType=JdbcType.NCHAR),
        @Result(column="SQORIG", property="sqorig", jdbcType=JdbcType.NCHAR),
        @Result(column="SQE8PZWH", property="sqe8pzwh", jdbcType=JdbcType.NCHAR),
        @Result(column="SQE8ZDYL", property="sqe8zdyl", jdbcType=JdbcType.NCHAR),
        @Result(column="SQE8JHG", property="sqe8jhg", jdbcType=JdbcType.NCHAR),
        @Result(column="SQE8ZTW", property="sqe8ztw", jdbcType=JdbcType.NCHAR),
        @Result(column="SQE8GFG", property="sqe8gfg", jdbcType=JdbcType.NCHAR),
        @Result(column="SQE8PTYP", property="sqe8ptyp", jdbcType=JdbcType.NCHAR),
        @Result(column="SQE8ATCDL", property="sqe8atcdl", jdbcType=JdbcType.NCHAR),
        @Result(column="SQE8ATCXL", property="sqe8atcxl", jdbcType=JdbcType.NCHAR),
        @Result(column="SQE8YYKS", property="sqe8yyks", jdbcType=JdbcType.NCHAR),
        @Result(column="SQE8FXDJ", property="sqe8fxdj", jdbcType=JdbcType.NCHAR),
        @Result(column="SQE8CCTJ", property="sqe8cctj", jdbcType=JdbcType.NCHAR),
        @Result(column="SQE8QTCC", property="sqe8qtcc", jdbcType=JdbcType.NCHAR),
        @Result(column="SQE8JGG", property="sqe8jgg", jdbcType=JdbcType.NCHAR),
        @Result(column="SQVR01", property="sqvr01", jdbcType=JdbcType.NCHAR),
        @Result(column="SQIR01", property="sqir01", jdbcType=JdbcType.NCHAR),
        @Result(column="SQVR02", property="sqvr02", jdbcType=JdbcType.NCHAR),
        @Result(column="SQIR02", property="sqir02", jdbcType=JdbcType.NCHAR),
        @Result(column="SQVR03", property="sqvr03", jdbcType=JdbcType.NCHAR),
        @Result(column="SQDSC3", property="sqdsc3", jdbcType=JdbcType.NCHAR),
        @Result(column="SQVR04", property="sqvr04", jdbcType=JdbcType.NCHAR),
        @Result(column="SQIR04", property="sqir04", jdbcType=JdbcType.NCHAR),
        @Result(column="SQSRP3", property="sqsrp3", jdbcType=JdbcType.NCHAR),
        @Result(column="SQDSE3", property="sqdse3", jdbcType=JdbcType.NCHAR),
        @Result(column="SQSRP4", property="sqsrp4", jdbcType=JdbcType.NCHAR),
        @Result(column="SQBFNM", property="sqbfnm", jdbcType=JdbcType.NCHAR),
        @Result(column="SQDSE4", property="sqdse4", jdbcType=JdbcType.NCHAR),
        @Result(column="SQSRP5", property="sqsrp5", jdbcType=JdbcType.NCHAR),
        @Result(column="SQBFNN", property="sqbfnn", jdbcType=JdbcType.NCHAR),
        @Result(column="SQDSE5", property="sqdse5", jdbcType=JdbcType.NCHAR),
        @Result(column="SQUOM1", property="squom1", jdbcType=JdbcType.NCHAR),
        @Result(column="SQDL01", property="sqdl01", jdbcType=JdbcType.NCHAR),
        @Result(column="SQBFNU", property="sqbfnu", jdbcType=JdbcType.NCHAR),
        @Result(column="SQBFPL", property="sqbfpl", jdbcType=JdbcType.NCHAR),
        @Result(column="SQUKID", property="squkid", jdbcType=JdbcType.DECIMAL),
        @Result(column="SQURCD", property="squrcd", jdbcType=JdbcType.NCHAR),
        @Result(column="SQURDT", property="squrdt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SQURAT", property="squrat", jdbcType=JdbcType.DECIMAL),
        @Result(column="SQURAB", property="squrab", jdbcType=JdbcType.DECIMAL),
        @Result(column="SQEV02", property="sqev02", jdbcType=JdbcType.NCHAR),
        @Result(column="SQEV03", property="sqev03", jdbcType=JdbcType.NCHAR),
        @Result(column="SQEV04", property="sqev04", jdbcType=JdbcType.NCHAR),
        @Result(column="SQEV05", property="sqev05", jdbcType=JdbcType.NCHAR),
        @Result(column="SQUSER", property="squser", jdbcType=JdbcType.NCHAR),
        @Result(column="SQPID", property="sqpid", jdbcType=JdbcType.NCHAR),
        @Result(column="SQJOBN", property="sqjobn", jdbcType=JdbcType.NCHAR),
        @Result(column="SQUPMJ", property="squpmj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SQUPMT", property="squpmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SQIDATE", property="sqidate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="SQDF01", property="sqdf01", jdbcType=JdbcType.NCHAR),
        @Result(column="SQRDATE", property="sqrdate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="SQDF02", property="sqdf02", jdbcType=JdbcType.NCHAR),
        @Result(column="SQSTATUS", property="sqstatus", jdbcType=JdbcType.NCHAR),
        @Result(column="SQFLAG", property="sqflag", jdbcType=JdbcType.NCHAR),
        @Result(column="SQFIL2", property="sqfil2", jdbcType=JdbcType.NCHAR),
        @Result(column="SQBFPM", property="sqbfpm", jdbcType=JdbcType.NCHAR),
        @Result(column="SQAIT1", property="sqait1", jdbcType=JdbcType.DECIMAL),
        @Result(column="SQAIT2", property="sqait2", jdbcType=JdbcType.DECIMAL),
        @Result(column="SQA001", property="sqa001", jdbcType=JdbcType.NCHAR),
        @Result(column="SQA002", property="sqa002", jdbcType=JdbcType.NCHAR),
        @Result(column="SQFIL3", property="sqfil3", jdbcType=JdbcType.NCHAR),
        @Result(column="SQA003", property="sqa003", jdbcType=JdbcType.NCHAR),
        @Result(column="SQA004", property="sqa004", jdbcType=JdbcType.NCHAR),
        @Result(column="SQCJ01", property="sqcj01", jdbcType=JdbcType.NCHAR),
        @Result(column="SQACTF", property="sqactf", jdbcType=JdbcType.NCHAR),
        @Result(column="SQCJ02", property="sqcj02", jdbcType=JdbcType.NCHAR),
        @Result(column="SQCJ03", property="sqcj03", jdbcType=JdbcType.NCHAR),
        @Result(column="SQAA06", property="sqaa06", jdbcType=JdbcType.NCHAR),
        @Result(column="SQCJ04", property="sqcj04", jdbcType=JdbcType.NCHAR),
        @Result(column="SQCJ05", property="sqcj05", jdbcType=JdbcType.NCHAR),
        @Result(column="SQA201", property="sqa201", jdbcType=JdbcType.NCHAR),
        @Result(column="SQADLM", property="sqadlm", jdbcType=JdbcType.DECIMAL),
        @Result(column="SQA202", property="sqa202", jdbcType=JdbcType.NCHAR),
        @Result(column="SQPP01", property="sqpp01", jdbcType=JdbcType.NCHAR),
        @Result(column="SQA203", property="sqa203", jdbcType=JdbcType.NCHAR),
        @Result(column="SQA204", property="sqa204", jdbcType=JdbcType.NCHAR),
        @Result(column="SQE8CPDL", property="sqe8cpdl", jdbcType=JdbcType.NCHAR),
        @Result(column="SQE8TSFL", property="sqe8tsfl", jdbcType=JdbcType.NCHAR),
        @Result(column="SQE8CPFL", property="sqe8cpfl", jdbcType=JdbcType.NCHAR),
        @Result(column="SQGK01", property="sqgk01", jdbcType=JdbcType.NCHAR),
        @Result(column="SQGK02", property="sqgk02", jdbcType=JdbcType.NCHAR),
        @Result(column="SQGK03", property="sqgk03", jdbcType=JdbcType.NCHAR)
    })
    Fe841001 selectByPrimaryKey(BigDecimal squkidp);

    @Select({
        "select",
        "SQUKIDP, SQKCOO, SQLITM, SQITM, SQEV01, SQAITM, SQDSC1, SQE8NAME, SQDSC2, SQE8JX, ",
        "SQSRTX, SQACLT, SQACPL, SQAN8, SQAC28, SQE8SCXKZ, SQE8SCBAH, SQORIG, SQE8PZWH, ",
        "SQE8ZDYL, SQE8JHG, SQE8ZTW, SQE8GFG, SQE8PTYP, SQE8ATCDL, SQE8ATCXL, SQE8YYKS, ",
        "SQE8FXDJ, SQE8CCTJ, SQE8QTCC, SQE8JGG, SQVR01, SQIR01, SQVR02, SQIR02, SQVR03, ",
        "SQDSC3, SQVR04, SQIR04, SQSRP3, SQDSE3, SQSRP4, SQBFNM, SQDSE4, SQSRP5, SQBFNN, ",
        "SQDSE5, SQUOM1, SQDL01, SQBFNU, SQBFPL, SQUKID, SQURCD, SQURDT, SQURAT, SQURAB, ",
        "SQEV02, SQEV03, SQEV04, SQEV05, SQUSER, SQPID, SQJOBN, SQUPMJ, SQUPMT, SQIDATE, ",
        "SQDF01, SQRDATE, SQDF02, SQSTATUS, SQFLAG, SQFIL2, SQBFPM, SQAIT1, SQAIT2, SQA001, ",
        "SQA002, SQFIL3, SQA003, SQA004, SQCJ01, SQACTF, SQCJ02, SQCJ03, SQAA06, SQCJ04, ",
        "SQCJ05, SQA201, SQADLM, SQA202, SQPP01, SQA203, SQA204, SQE8CPDL, SQE8TSFL, ",
        "SQE8CPFL, SQGK01, SQGK02, SQGK03",
        "from FE841001"
    })
    @Results({
        @Result(column="SQUKIDP", property="squkidp", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="SQKCOO", property="sqkcoo", jdbcType=JdbcType.NCHAR),
        @Result(column="SQLITM", property="sqlitm", jdbcType=JdbcType.NCHAR),
        @Result(column="SQITM", property="sqitm", jdbcType=JdbcType.DECIMAL),
        @Result(column="SQEV01", property="sqev01", jdbcType=JdbcType.NCHAR),
        @Result(column="SQAITM", property="sqaitm", jdbcType=JdbcType.NCHAR),
        @Result(column="SQDSC1", property="sqdsc1", jdbcType=JdbcType.NCHAR),
        @Result(column="SQE8NAME", property="sqe8name", jdbcType=JdbcType.NCHAR),
        @Result(column="SQDSC2", property="sqdsc2", jdbcType=JdbcType.NCHAR),
        @Result(column="SQE8JX", property="sqe8jx", jdbcType=JdbcType.NCHAR),
        @Result(column="SQSRTX", property="sqsrtx", jdbcType=JdbcType.NCHAR),
        @Result(column="SQACLT", property="sqaclt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SQACPL", property="sqacpl", jdbcType=JdbcType.DECIMAL),
        @Result(column="SQAN8", property="sqan8", jdbcType=JdbcType.DECIMAL),
        @Result(column="SQAC28", property="sqac28", jdbcType=JdbcType.NCHAR),
        @Result(column="SQE8SCXKZ", property="sqe8scxkz", jdbcType=JdbcType.NCHAR),
        @Result(column="SQE8SCBAH", property="sqe8scbah", jdbcType=JdbcType.NCHAR),
        @Result(column="SQORIG", property="sqorig", jdbcType=JdbcType.NCHAR),
        @Result(column="SQE8PZWH", property="sqe8pzwh", jdbcType=JdbcType.NCHAR),
        @Result(column="SQE8ZDYL", property="sqe8zdyl", jdbcType=JdbcType.NCHAR),
        @Result(column="SQE8JHG", property="sqe8jhg", jdbcType=JdbcType.NCHAR),
        @Result(column="SQE8ZTW", property="sqe8ztw", jdbcType=JdbcType.NCHAR),
        @Result(column="SQE8GFG", property="sqe8gfg", jdbcType=JdbcType.NCHAR),
        @Result(column="SQE8PTYP", property="sqe8ptyp", jdbcType=JdbcType.NCHAR),
        @Result(column="SQE8ATCDL", property="sqe8atcdl", jdbcType=JdbcType.NCHAR),
        @Result(column="SQE8ATCXL", property="sqe8atcxl", jdbcType=JdbcType.NCHAR),
        @Result(column="SQE8YYKS", property="sqe8yyks", jdbcType=JdbcType.NCHAR),
        @Result(column="SQE8FXDJ", property="sqe8fxdj", jdbcType=JdbcType.NCHAR),
        @Result(column="SQE8CCTJ", property="sqe8cctj", jdbcType=JdbcType.NCHAR),
        @Result(column="SQE8QTCC", property="sqe8qtcc", jdbcType=JdbcType.NCHAR),
        @Result(column="SQE8JGG", property="sqe8jgg", jdbcType=JdbcType.NCHAR),
        @Result(column="SQVR01", property="sqvr01", jdbcType=JdbcType.NCHAR),
        @Result(column="SQIR01", property="sqir01", jdbcType=JdbcType.NCHAR),
        @Result(column="SQVR02", property="sqvr02", jdbcType=JdbcType.NCHAR),
        @Result(column="SQIR02", property="sqir02", jdbcType=JdbcType.NCHAR),
        @Result(column="SQVR03", property="sqvr03", jdbcType=JdbcType.NCHAR),
        @Result(column="SQDSC3", property="sqdsc3", jdbcType=JdbcType.NCHAR),
        @Result(column="SQVR04", property="sqvr04", jdbcType=JdbcType.NCHAR),
        @Result(column="SQIR04", property="sqir04", jdbcType=JdbcType.NCHAR),
        @Result(column="SQSRP3", property="sqsrp3", jdbcType=JdbcType.NCHAR),
        @Result(column="SQDSE3", property="sqdse3", jdbcType=JdbcType.NCHAR),
        @Result(column="SQSRP4", property="sqsrp4", jdbcType=JdbcType.NCHAR),
        @Result(column="SQBFNM", property="sqbfnm", jdbcType=JdbcType.NCHAR),
        @Result(column="SQDSE4", property="sqdse4", jdbcType=JdbcType.NCHAR),
        @Result(column="SQSRP5", property="sqsrp5", jdbcType=JdbcType.NCHAR),
        @Result(column="SQBFNN", property="sqbfnn", jdbcType=JdbcType.NCHAR),
        @Result(column="SQDSE5", property="sqdse5", jdbcType=JdbcType.NCHAR),
        @Result(column="SQUOM1", property="squom1", jdbcType=JdbcType.NCHAR),
        @Result(column="SQDL01", property="sqdl01", jdbcType=JdbcType.NCHAR),
        @Result(column="SQBFNU", property="sqbfnu", jdbcType=JdbcType.NCHAR),
        @Result(column="SQBFPL", property="sqbfpl", jdbcType=JdbcType.NCHAR),
        @Result(column="SQUKID", property="squkid", jdbcType=JdbcType.DECIMAL),
        @Result(column="SQURCD", property="squrcd", jdbcType=JdbcType.NCHAR),
        @Result(column="SQURDT", property="squrdt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SQURAT", property="squrat", jdbcType=JdbcType.DECIMAL),
        @Result(column="SQURAB", property="squrab", jdbcType=JdbcType.DECIMAL),
        @Result(column="SQEV02", property="sqev02", jdbcType=JdbcType.NCHAR),
        @Result(column="SQEV03", property="sqev03", jdbcType=JdbcType.NCHAR),
        @Result(column="SQEV04", property="sqev04", jdbcType=JdbcType.NCHAR),
        @Result(column="SQEV05", property="sqev05", jdbcType=JdbcType.NCHAR),
        @Result(column="SQUSER", property="squser", jdbcType=JdbcType.NCHAR),
        @Result(column="SQPID", property="sqpid", jdbcType=JdbcType.NCHAR),
        @Result(column="SQJOBN", property="sqjobn", jdbcType=JdbcType.NCHAR),
        @Result(column="SQUPMJ", property="squpmj", jdbcType=JdbcType.DECIMAL),
        @Result(column="SQUPMT", property="squpmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SQIDATE", property="sqidate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="SQDF01", property="sqdf01", jdbcType=JdbcType.NCHAR),
        @Result(column="SQRDATE", property="sqrdate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="SQDF02", property="sqdf02", jdbcType=JdbcType.NCHAR),
        @Result(column="SQSTATUS", property="sqstatus", jdbcType=JdbcType.NCHAR),
        @Result(column="SQFLAG", property="sqflag", jdbcType=JdbcType.NCHAR),
        @Result(column="SQFIL2", property="sqfil2", jdbcType=JdbcType.NCHAR),
        @Result(column="SQBFPM", property="sqbfpm", jdbcType=JdbcType.NCHAR),
        @Result(column="SQAIT1", property="sqait1", jdbcType=JdbcType.DECIMAL),
        @Result(column="SQAIT2", property="sqait2", jdbcType=JdbcType.DECIMAL),
        @Result(column="SQA001", property="sqa001", jdbcType=JdbcType.NCHAR),
        @Result(column="SQA002", property="sqa002", jdbcType=JdbcType.NCHAR),
        @Result(column="SQFIL3", property="sqfil3", jdbcType=JdbcType.NCHAR),
        @Result(column="SQA003", property="sqa003", jdbcType=JdbcType.NCHAR),
        @Result(column="SQA004", property="sqa004", jdbcType=JdbcType.NCHAR),
        @Result(column="SQCJ01", property="sqcj01", jdbcType=JdbcType.NCHAR),
        @Result(column="SQACTF", property="sqactf", jdbcType=JdbcType.NCHAR),
        @Result(column="SQCJ02", property="sqcj02", jdbcType=JdbcType.NCHAR),
        @Result(column="SQCJ03", property="sqcj03", jdbcType=JdbcType.NCHAR),
        @Result(column="SQAA06", property="sqaa06", jdbcType=JdbcType.NCHAR),
        @Result(column="SQCJ04", property="sqcj04", jdbcType=JdbcType.NCHAR),
        @Result(column="SQCJ05", property="sqcj05", jdbcType=JdbcType.NCHAR),
        @Result(column="SQA201", property="sqa201", jdbcType=JdbcType.NCHAR),
        @Result(column="SQADLM", property="sqadlm", jdbcType=JdbcType.DECIMAL),
        @Result(column="SQA202", property="sqa202", jdbcType=JdbcType.NCHAR),
        @Result(column="SQPP01", property="sqpp01", jdbcType=JdbcType.NCHAR),
        @Result(column="SQA203", property="sqa203", jdbcType=JdbcType.NCHAR),
        @Result(column="SQA204", property="sqa204", jdbcType=JdbcType.NCHAR),
        @Result(column="SQE8CPDL", property="sqe8cpdl", jdbcType=JdbcType.NCHAR),
        @Result(column="SQE8TSFL", property="sqe8tsfl", jdbcType=JdbcType.NCHAR),
        @Result(column="SQE8CPFL", property="sqe8cpfl", jdbcType=JdbcType.NCHAR),
        @Result(column="SQGK01", property="sqgk01", jdbcType=JdbcType.NCHAR),
        @Result(column="SQGK02", property="sqgk02", jdbcType=JdbcType.NCHAR),
        @Result(column="SQGK03", property="sqgk03", jdbcType=JdbcType.NCHAR)
    })
    List<Fe841001> selectAll();
}